import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21263_10294.json"
const rolesSourceUrl = "https://clocktower.gstonegames.com/ct/grimoireRoleJson/"
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: "Ji Meng Ta Xiang", setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const jiMengTaXiangRoles = [
  role({"id": "qintianjian", "name": "钦天监", "officialName": "钦天监", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知离你最近的邪恶玩家位于你的哪一侧（左/右/相同）。如果与你邻近的玩家中有邪恶阵营，你会得知错误信息。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4484677694761_241d43f7.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Learns left, right, or same side for nearest evil player."], "highRiskNotes": ["Neighbor evil condition can force false information."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "dianxiaoer", "name": "店小二", "officialName": "店小二", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两名善良玩家。他们之中会有一人醉酒，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_8586487694761_0ecde168.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Learns two good players; one of them is drunk even if Dianxiaoer is dead."], "stateChanges": ["One named good player is drunk."], "highRiskNotes": ["Drunk selection is ST-confirmed and should be tracked manually."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "yinyangshi", "name": "阴阳师", "officialName": "阴阳师", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两个善良角色和两个邪恶角色。其中有且只有两个角色在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4630967694761_bd56d041.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Learns two good roles and two evil roles; exactly two are in play."], "highRiskNotes": ["Role set is ST-authored; AI can suggest balance, not decide final list."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "villageidiot", "name": "村夫", "officialName": "Village Idiot", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名玩家：你会得知他的阵营。[+0~2村夫，复数村夫中有一人醉酒]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1710949285_197011_408.png", "inputKinds": ["player"], "setupImpact": ["May add zero to two extra Village Idiots; if multiple, one Village Idiot is drunk."], "possibleOutcomes": ["Each Village Idiot learns a chosen player's alignment."], "stateChanges": ["One Village Idiot is drunk if more than one is in play."], "highRiskNotes": ["Kept out of first normal templates to avoid duplicate-role setup drift."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "empath", "name": "共情者", "officialName": "共情者", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["number"], "possibleOutcomes": ["Learns number of evil living neighbors."], "highRiskNotes": ["Registration exceptions and dead-neighbor skipping remain ST-confirmed."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "dreamer", "name": "筑梦师", "officialName": "筑梦师", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你及旅行者以外的一名玩家：你会得知一个善良角色和一个邪恶角色，该玩家是其中一个角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/dreamer.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Chooses a non-self, non-Traveler player and learns one good and one evil character, one of which is that player."], "highRiskNotes": ["Role pair is ST-authored and should remain editable."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "yinluren", "name": "引路人", "officialName": "引路人", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知今晚是否有邪恶玩家的能力选择或影响了他们之中的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_2147287694761_01761fcb.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Chooses two players and learns whether an evil player's ability chose or affected either tonight."], "highRiskNotes": ["Consider direct choices and indirect effects; ST confirms final yes/no."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "exorcist", "name": "驱魔人", "officialName": "驱魔人", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家（与上个夜晚不同）：如果你选中了恶魔，他会得知你是驱魔人，但他当晚不会因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/exorcist.png", "inputKinds": ["player"], "possibleOutcomes": ["If Exorcist chooses the Demon, Demon learns Exorcist and does not wake from own ability tonight."], "stateChanges": ["May block Demon wake/action for the night."], "playerMessageTemplates": ["If the Demon is chosen, tell the Demon: Exorcist chose you."], "highRiskNotes": ["Must choose different player than previous night; do not auto-skip Demon action."], "setupImpact": [], "identityChanges": [], "teamChanges": []}),
  role({"id": "undertaker", "name": "送葬者", "officialName": "送葬者", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天白天死于处决的玩家的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/undertaker.png", "inputKinds": ["role"], "possibleOutcomes": ["Learns the character of the player executed today."], "highRiskNotes": ["False registration and execution record remain ST-confirmed."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "gossip", "name": "造谣者", "officialName": "造谣者", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "possibleOutcomes": ["If public statement is true, one player dies tonight."], "stateChanges": ["May cause one night death."], "highRiskNotes": ["ST decides truth and death; tool only reminds and drafts."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "geling", "name": "歌伶", "officialName": "歌伶", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以提议所有玩家观看你的演出，并从同意参加的玩家中选择你的观众。如果恶魔成为了观众，你会在当晚死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_3570909608961_efc2d989.jpg", "inputKinds": ["players", "text"], "possibleOutcomes": ["Once per game proposes performance; if Demon is in audience, Geling dies that night."], "stateChanges": ["May die at night if Demon was an audience member."], "highRiskNotes": ["Audience consent and Demon check are manual."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "banxian", "name": "半仙", "officialName": "半仙", "team": "townsfolk", "abilityText": "任何在夜晚使用自身能力选择你的其他玩家，会改为选中另一名邪恶玩家作为替代。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_3833755308961_7e6f7e09.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Night abilities that would choose Banxian are redirected to another evil player."], "highRiskNotes": ["Retargeting is an interrupting reminder; do not silently rewrite targets."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "chongfei", "name": "宠妃", "officialName": "宠妃", "team": "townsfolk", "abilityText": "每局游戏限一次，说书人会在关于你的事情上打破规则。随后，你会秘密得知说书人为此做了什么。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_3373896816071_be9c7270.jpg", "inputKinds": ["text"], "possibleOutcomes": ["Once per game ST breaks a rule about her, then secretly tells what was done."], "highRiskNotes": ["This is deliberate ST discretion; tool only records explanation and message draft."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "nichen", "name": "逆臣", "officialName": "逆臣", "team": "outsider", "abilityText": "在你的首个夜晚，你要选择除你以外的一名玩家：如果他先死于处决，你转变为邪恶；如果你先死于处决，他转变为邪恶。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_6302887694761_9ba8a0f3.jpg", "inputKinds": ["player"], "possibleOutcomes": ["First night chooses another player; when either is first executed, the other becomes evil."], "teamChanges": ["Linked player may become evil after first execution among the pair."], "highRiskNotes": ["Do not auto-change alignment; ST confirms execution order."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "playerMessageTemplates": []}),
  role({"id": "acrobat", "name": "杂技演员", "officialName": "杂技演员", "team": "outsider", "abilityText": "每个夜晚*，如果与你邻近的存活善良玩家之一醉酒或中毒，你死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/acrobat.png", "inputKinds": ["none"], "possibleOutcomes": ["If a living good neighbor is drunk or poisoned, Acrobat dies."], "stateChanges": ["May die from neighboring good player being drunk/poisoned."], "highRiskNotes": ["Neighbor, good status, and poison/drunk source are ST-confirmed."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "plaguedoctor", "name": "瘟疫医生", "officialName": "Plague Doctor", "team": "outsider", "abilityText": "如果你死亡，说书人获得一个不在场的爪牙能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9614144308961_fe5074b8.jpg", "inputKinds": ["role"], "possibleOutcomes": ["On death, ST gains a not-in-play Minion ability."], "identityChanges": ["ST may gain a Minion ability as a rule reminder."], "highRiskNotes": ["ST ability choice is manual and not assigned to a player automatically."], "setupImpact": [], "stateChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "barber", "name": "理发师", "officialName": "理发师", "team": "outsider", "abilityText": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png", "inputKinds": ["players"], "possibleOutcomes": ["On death, Demon may swap two non-Demon players' characters."], "identityChanges": ["Two non-Demon players may swap characters."], "highRiskNotes": ["Never auto-swap identities; ST confirms Demon choice and notifications."], "setupImpact": [], "stateChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "gudiao", "name": "蛊雕", "officialName": "蛊雕", "team": "minion", "abilityText": "蛊雕：每个夜晚，你要选择左或右：将你的飞行标记从当前位置移动到这个方向上的下一名存活善良玩家。他中毒且可能被当作邪恶阵营和爪牙角色，你会知道他原本的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4078497694761_5c6ddcce.jpg", "inputKinds": ["player", "text"], "possibleOutcomes": ["Poison marker moves to next living good player in chosen direction; target may register evil/minion."], "stateChanges": ["A good player may be poisoned."], "highRiskNotes": ["Direction, poison target and false registration are manual."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "assassin", "name": "刺客", "officialName": "刺客", "team": "minion", "abilityText": "每局游戏限一次，在夜晚时*，你可以选择一名玩家：他死亡，即使因为任何原因让他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/assassin.png", "inputKinds": ["player"], "possibleOutcomes": ["Once per game chooses a player to die, even if protected."], "stateChanges": ["May cause unstoppable death."], "highRiskNotes": ["Use-once and death are manual."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "洗脑师", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["text"], "possibleOutcomes": ["Follow the source ability text; ST confirms the final result."], "highRiskNotes": ["AI can draft reminders only; authority state changes require ST confirmation."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "ganshiren", "name": "赶尸人", "officialName": "赶尸人", "team": "minion", "abilityText": "与你邻近的两名镇民玩家会在其首次死亡时被当作仍然存活。[-1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4215797694761_97f10b13.jpg", "inputKinds": ["none"], "setupImpact": ["Reduce Outsider count by one."], "possibleOutcomes": ["Neighboring Townsfolk are treated as alive the first time they die."], "stateChanges": ["Neighboring Townsfolk may be treated alive after first death."], "highRiskNotes": ["Kept out of first normal templates; fake-alive handling is manual."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "jianning", "name": "奸佞", "officialName": "奸佞", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你今天白天没有投票，今晚你可以行动两次。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_6705607816071_60588424.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Chooses a player to die; may choose twice if no one voted today."], "stateChanges": ["May cause one or two deaths."], "highRiskNotes": ["Vote condition and deaths are ST-confirmed."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "hundun", "name": "混沌", "officialName": "混沌", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式杀死了一名与你邻近的镇民玩家，所有善良玩家会中毒直到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9149178608961_89693def.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Kills a player; if killing a neighboring Townsfolk, all good players are poisoned until dusk."], "stateChanges": ["May kill target and poison all good players until dusk."], "highRiskNotes": ["Neighbor and Townsfolk check are ST-confirmed."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "dianyuzhang", "name": "典狱长", "officialName": "典狱长", "team": "demon", "abilityText": "每个夜晚，你要选择至多三名玩家：如果明天白天他们之一死于处决，被你上次选择的其他玩家会在当晚死亡。否则，当晚他们之中会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_5570117816071_2f5793fd.jpg", "inputKinds": ["players", "text"], "possibleOutcomes": ["Chooses up to three prisoners; deaths are resolved by the custom timing."], "stateChanges": ["May cause delayed or immediate death."], "highRiskNotes": ["Prisoners and death timing are manual."], "setupImpact": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "djinn", "name": "灯神", "officialName": "灯神", "team": "fabled", "abilityText": "使用灯神的相克规则。所有玩家都会知道其内容。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/djinn.png", "inputKinds": ["none"], "possibleOutcomes": ["Fabled jinx reminder only."], "highRiskNotes": ["Does not enter normal setup templates."], "setupImpact": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": []}),
  role({"id": "kazali", "name": "卡扎力", "officialName": "Kazali", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。[由你决定谁是什么爪牙，-或+任意数量外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1710949285_197011_4173.png", "inputKinds": ["player", "players", "role"], "setupImpact": ["At setup, Kazali chooses which players are which Minions.", "May add or remove any number of Outsiders."], "possibleOutcomes": ["Each later night chooses a player to die."], "stateChanges": ["May cause night death."], "identityChanges": ["Opening Minion assignments are storyteller-confirmed."], "highRiskNotes": ["Kept out of first normal templates; no automatic identity or outsider-count changes."], "teamChanges": [], "playerMessageTemplates": []}),
] as const satisfies readonly SmartRoleDefinition[]
