import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "ji-meng-ta-xiang"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const jiMengTaXiangSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "gudiao", "jianning"], bluffs: ["yinluren", "exorcist", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["yinluren", "exorcist", "undertaker", "gossip", "geling", "assassin", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "banxian"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["banxian", "chongfei", "empath", "dreamer", "gossip", "cerenovus", "dianyuzhang"], bluffs: ["yinyangshi", "geling", "acrobat"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "nichen", "gudiao", "jianning"], bluffs: ["yinluren", "exorcist", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["yinluren", "exorcist", "undertaker", "gossip", "geling", "acrobat", "assassin", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "banxian"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "nichen", "acrobat", "gudiao", "jianning"], bluffs: ["yinluren", "exorcist", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["yinluren", "exorcist", "undertaker", "gossip", "geling", "plaguedoctor", "barber", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "banxian"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "undertaker", "gudiao", "assassin", "jianning"], bluffs: ["exorcist", "gossip", "geling"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "geling", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "banxian"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["qintianjian", "dianxiaoer", "gossip", "geling", "banxian", "chongfei", "yinyangshi", "gudiao", "cerenovus", "dianyuzhang"], bluffs: ["empath", "dreamer", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "undertaker", "nichen", "gudiao", "assassin", "jianning"], bluffs: ["exorcist", "gossip", "geling"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["empath", "dreamer", "exorcist", "undertaker", "gossip", "geling", "banxian", "acrobat", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "yinluren"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "undertaker", "nichen", "acrobat", "gudiao", "assassin", "jianning"], bluffs: ["exorcist", "gossip", "geling"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["empath", "dreamer", "exorcist", "undertaker", "gossip", "geling", "banxian", "plaguedoctor", "barber", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "yinluren"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "gossip", "geling", "banxian", "chongfei", "nichen", "barber", "gudiao", "cerenovus", "dianyuzhang"], bluffs: ["empath", "dreamer", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "gudiao", "assassin", "cerenovus", "jianning"], bluffs: ["geling", "banxian", "chongfei"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "geling", "banxian", "chongfei", "gudiao", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "yinyangshi"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "nichen", "gudiao", "assassin", "cerenovus", "jianning"], bluffs: ["geling", "banxian", "chongfei"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "geling", "banxian", "chongfei", "barber", "gudiao", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "yinyangshi"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "nichen", "acrobat", "gudiao", "assassin", "cerenovus", "jianning"], bluffs: ["geling", "banxian", "chongfei"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["empath", "dreamer", "yinluren", "exorcist", "undertaker", "gossip", "geling", "banxian", "chongfei", "plaguedoctor", "barber", "gudiao", "assassin", "cerenovus", "hundun"], bluffs: ["qintianjian", "dianxiaoer", "yinyangshi"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["qintianjian", "dianxiaoer", "yinyangshi", "empath", "gossip", "geling", "banxian", "chongfei", "dreamer", "nichen", "barber", "gudiao", "assassin", "cerenovus", "dianyuzhang"], bluffs: ["yinluren", "exorcist", "undertaker"], note: "Verified setup; Village Idiot, Ganshiren and Kazali setup-changing paths stay out of first normal templates; Nichen/Barber/Gudiao/Cerenovus/Hundun/Dianyuzhang death, madness, poison and alignment outcomes remain ST-confirmed." }),
]
