import type { SetupRule } from '../../types'

export const haoShiDuoMoSetupRules: readonly SetupRule[] = [
  {"id": "drunk-setup", "roleId": "drunk", "summary": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "fanggu-setup", "roleId": "fanggu", "summary": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "snakecharmer-high-risk", "roleId": "snakecharmer", "summary": "Snake Charmer/Demon identity and alignment swap happens only after ST confirmation; the new Snake Charmer is drunk and does not use the Demon ability that night.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "cerenovus-high-risk", "roleId": "cerenovus", "summary": "Cerenovus creates a madness prompt; record the chosen player and good character, but consequences remain ST-confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "gambler-high-risk", "roleId": "gambler", "summary": "Gambler death only if the guessed role is wrong; AI may compare draft guess with known role but ST confirms before marking death.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "poppygrower-high-risk", "roleId": "poppygrower", "summary": "Poppy Grower changes evil info flow; if dead, evil recognition is a night reminder, not automatic messaging.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "heretic-high-risk", "roleId": "heretic", "summary": "Heretic reverses win/loss; the tool never declares victory automatically.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "lleech-high-risk", "roleId": "lleech", "summary": "Lleech host starts poisoned and Demon death depends on host death; both are manual status/state confirmations.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
  {"id": "imp-high-risk", "roleId": "imp", "summary": "Imp self-kill handoff to a Minion is a manual identity change and wake-up reminder.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20749_59939.json"], "reviewedAt": "2026-07-22"},
]
