import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "bao-yue-chu-sheng"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const baoYueChuShengSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "widow", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "cerenovus", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["gambler", "professor", "ravenkeeper", "cannibal", "mayor", "goblin", "po"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "recluse", "widow", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "barber", "cerenovus", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "recluse", "mutant", "widow", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "barber", "recluse", "cerenovus", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "widow", "cerenovus", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "cerenovus", "widow", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["gambler", "professor", "ravenkeeper", "cannibal", "mayor", "snakecharmer", "pixie", "goblin", "widow", "po"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "recluse", "widow", "cerenovus", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "barber", "cerenovus", "widow", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "recluse", "mutant", "widow", "cerenovus", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "barber", "recluse", "cerenovus", "widow", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["gambler", "professor", "ravenkeeper", "cannibal", "mayor", "snakecharmer", "pixie", "mutant", "barber", "goblin", "widow", "po"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "ravenkeeper", "cannibal", "widow", "cerenovus", "goblin", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "professor", "cannibal", "cerenovus", "widow", "goblin", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "ravenkeeper", "cannibal", "recluse", "widow", "cerenovus", "goblin", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "professor", "cannibal", "barber", "cerenovus", "widow", "goblin", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["grandmother", "pixie", "king", "chambermaid", "gambler", "professor", "seamstress", "ravenkeeper", "cannibal", "recluse", "mutant", "widow", "cerenovus", "goblin", "pukka"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["pixie", "snakecharmer", "seamstress", "chambermaid", "king", "grandmother", "ravenkeeper", "professor", "cannibal", "barber", "recluse", "cerenovus", "widow", "goblin", "shabaloth"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["gambler", "professor", "ravenkeeper", "cannibal", "mayor", "snakecharmer", "pixie", "chambermaid", "seamstress", "mutant", "barber", "goblin", "widow", "cerenovus", "po"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "Verified normal setup; Balloonist, Choirboy, Drunk, Godfather and Lil' Monsta setup or hidden-identity paths stay manual. Pukka, Shabaloth, Po, Widow, Cerenovus, Goblin, Barber, Snake Charmer, Professor, Gambler and Mayor outcomes remain ST-confirmed."}),
]
