import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21506_04125.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Zi Gui Qi Ming', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const ziGuiQiMingRoles = [
  role({"id": "chef", "name": "厨师", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png", "inputKinds": ["number"], "possibleOutcomes": ["Tell number of adjacent evil pairs."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Count adjacent evil pairs; false registration may apply."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "possibleOutcomes": ["Tell whether either chosen player registers as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Red herring good player registers as Demon for this ability."], "playerMessageTemplates": [], "highRiskNotes": ["Track red herring privately."], "setupImpact": []}),
  role({"id": "empath", "name": "共情者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["number"], "possibleOutcomes": ["Tell 0, 1, or 2 evil living neighbors."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Skip dead players before counting."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players", "number"], "possibleOutcomes": ["Tell how many chosen living players woke due to own ability tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only own-ability wake counts."], "setupImpact": []}),
  role({"id": "undertaker", "name": "送葬者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天白天死于处决的玩家的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/undertaker.png", "inputKinds": ["role"], "possibleOutcomes": ["Learn the role of the player executed today."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["The executed player was role X."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "bingbi", "name": "秉笔", "officialName": "custom", "team": "townsfolk", "abilityText": "如果你在白天死亡，当晚你会得知一名善良玩家。如果你在夜晚死亡，当晚你会得知一名邪恶玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_5918227760171_7f310c1b.jpg", "inputKinds": ["none"], "possibleOutcomes": ["If died by day, learn a good player; if died by night, learn an evil player."], "stateChanges": ["Trigger depends on death timing."], "identityChanges": [], "teamChanges": ["Given player must match current alignment."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "daoke", "name": "刀客", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你得知一个在场的爪牙角色。每局游戏限一次，你可以在白天公开选择一名玩家：如果他是你得知的角色，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_5751437760171_79dd1401.jpg", "inputKinds": ["role", "player"], "possibleOutcomes": ["First night learn an in-play Minion role; once by day publicly choose a player, if that role, they die."], "stateChanges": ["May kill public target once."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track learned Minion role and once-per-game public shot."], "setupImpact": []}),
  role({"id": "fangshi", "name": "方士", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你要选择一个数字。在该数字对应的那一个夜晚，你会得知对应数量的在场角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_9290087694761_94c7b6f3.jpg", "inputKinds": ["number", "role"], "possibleOutcomes": ["First night choose a number; on that numbered night learn that many in-play roles."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track chosen night number and prepare role list later."], "setupImpact": []}),
  role({"id": "xuncha", "name": "巡察", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的两个善良角色：如果他们都存活，他们当晚不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_7108682943171_ed7a0042.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Choose two good roles; if both alive, they do not die tonight."], "stateChanges": ["May protect role holders from death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Targets are roles, not seats."], "setupImpact": []}),
  role({"id": "yinyangshi", "name": "阴阳师", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两个善良角色和两个邪恶角色。其中有且只有两个角色在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4630967694761_bd56d041.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Learn two good roles and two evil roles; exactly two are in play."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Exactly two roles from four are in play."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "yishi", "name": "驿使", "officialName": "custom", "team": "townsfolk", "abilityText": "每个白天，你可以公开声明一个角色。在当晚，你会得知该角色是否在场。如果你因此得知了否，你失去此能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_9168557760171_8ae6a36c.jpg", "inputKinds": ["role", "text"], "possibleOutcomes": ["Publicly claim a role by day; at night learn whether it is in play; if no, lose ability."], "stateChanges": ["May lose ability after no result."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "zhen", "name": "鸩", "officialName": "custom", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时*，你可以选择一个镇民角色：如果他在场，他醉酒并死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_1134823943171_5fc42e52.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Once per game choose a Townsfolk role; if in play, that player is drunk and dies."], "stateChanges": ["Role holder may become drunk and die."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Target is role, not seat; ST confirms result."], "setupImpact": []}),
  role({"id": "tixingguan", "name": "提刑官", "officialName": "custom", "team": "townsfolk", "abilityText": "在你首次提名玩家后，你会在当晚得知他的角色。外来者会被你的能力当作爪牙或恶魔角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_7402377694761_cd9eb282.jpg", "inputKinds": ["role", "text"], "possibleOutcomes": ["At night learn role of first nominated player."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Outsiders are treated as Minion or Demon roles."], "setupImpact": []}),
  role({"id": "shutong", "name": "书童", "officialName": "custom", "team": "outsider", "abilityText": "在你的首个夜晚，你要选择除你以外的一名玩家：除首个夜晚以外，当他被邪恶玩家的能力选择或影响时，你会在当晚死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_2027903943171_36d374a5.jpg", "inputKinds": ["player"], "possibleOutcomes": ["First night choose a player; after first night, die if that player is chosen or affected by evil ability."], "stateChanges": ["May die at night after evil effect."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track first-night anchor."], "setupImpact": []}),
  role({"id": "recluse", "name": "陌客", "officialName": "custom", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "possibleOutcomes": ["May register as evil, Minion, or Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": ["False registration may affect info roles."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "custom", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["role"], "possibleOutcomes": ["Player thinks they are a Townsfolk but has no real ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track false identity privately."], "setupImpact": []}),
  role({"id": "plaguedoctor", "name": "瘟疫医生", "officialName": "custom", "team": "outsider", "abilityText": "如果你死亡，说书人获得一个爪牙能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9614144308961_fe5074b8.jpg", "inputKinds": ["none"], "possibleOutcomes": ["If dies, ST gains a Minion ability."], "stateChanges": ["ST may gain Minion ability."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "harpy", "name": "鹰身女妖", "officialName": "custom", "team": "minion", "abilityText": "每个夜晚，你要选择两名玩家：明天第一名玩家需要“疯狂”地证明第二名玩家是邪恶的，否则他们之中可能会有人死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202307/c_4331482099861_0db1bfaf.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Choose two players; first must be mad second is evil or one/both may die."], "stateChanges": ["Madness penalty may cause death."], "identityChanges": [], "teamChanges": ["Second is madness claim target, not necessarily evil."], "playerMessageTemplates": [], "highRiskNotes": ["Madness and penalty are ST discretion."], "setupImpact": []}),
  role({"id": "godfather", "name": "教父", "officialName": "custom", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Learn in-play Outsiders; if Outsider dies by day, choose a player to die tonight."], "stateChanges": ["May cause extra death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates to avoid count adjustment drift."], "setupImpact": ["May add or remove 1 Outsider."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "custom", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["role"], "possibleOutcomes": ["Thinks they are good but is evil; Demon knows Marionette."], "stateChanges": [], "identityChanges": ["False good identity shown."], "teamChanges": ["Actual alignment is evil."], "playerMessageTemplates": [], "highRiskNotes": ["Adjacency and false identity are private ST records."], "setupImpact": ["Must neighbor the Demon."]}),
  role({"id": "gudiao", "name": "蛊雕", "officialName": "custom", "team": "minion", "abilityText": "每个夜晚，你要选择左或右：你得知该方向上的下一名存活善良玩家的角色，他中毒且其他善良玩家以为他是邪恶的蛊雕，直到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4078497694761_5c6ddcce.jpg", "inputKinds": ["text", "role"], "possibleOutcomes": ["Choose left/right; learn next living good player role, poison them, and good players may think they are evil Gudiao."], "stateChanges": ["Chosen good player poisoned until next dusk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Perception/madness part is reminder; poison requires confirmation."], "setupImpact": []}),
  role({"id": "yanluo", "name": "阎罗", "officialName": "custom", "team": "demon", "abilityText": "在你的首个夜晚，你能查看魔典并选择一名玩家：他在第三个夜晚死亡，即使因为任何原因让他不会死亡。每个夜晚，你要选择一名玩家：上个夜晚被你选择的玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_2190498760171_1c483826.jpg", "inputKinds": ["player"], "possibleOutcomes": ["First night view Grimoire and choose a player to die on night three; each night chosen player from previous night dies."], "stateChanges": ["Delayed and rolling death chain."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track delayed night-three target and previous-night selection carefully."], "setupImpact": []}),
  role({"id": "guhuoniao", "name": "姑获鸟", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。你可能会拥有上一个死于处决的爪牙的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_3002932943171_72f4def0.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Choose a player to die; may have ability of last executed Minion."], "stateChanges": ["Target dies; may gain Minion ability."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Check last executed Minion before applying extra ability."], "setupImpact": []}),
  role({"id": "dianyuzhang", "name": "典狱长", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚，你要选择至多三名玩家：如果明天白天他们之一死于处决，上次被你选择的其他玩家会在当晚死亡。否则，当晚他们之中会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_5570117816071_2f5793fd.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Choose up to three players; if one is executed tomorrow, others die that night; otherwise one chosen player dies."], "stateChanges": ["Conditional delayed deaths."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track marked players and next-day execution result."], "setupImpact": []}),
  role({"id": "lilmonsta", "name": "小怪宝", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，会有一名玩家死亡。[+1爪牙]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lil_monsta.png", "inputKinds": ["player"], "possibleOutcomes": ["Minions choose babysitter who is Demon; each night a player might die."], "stateChanges": ["Babysitter and death may change nightly."], "identityChanges": ["Babysitter is Demon for that night."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Setup-changing Demon; kept out of normal templates."], "setupImpact": ["Adds one Minion."]}),
] as const satisfies readonly SmartRoleDefinition[]
