import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "zi-gui-qi-ming"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const ziGuiQiMingSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["fangshi", "xuncha", "yinyangshi", "yishi", "zhen", "marionette", "guhuoniao"], bluffs: ["tixingguan", "chef", "fortuneteller"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["xuncha", "yinyangshi", "yishi", "zhen", "tixingguan", "gudiao", "dianyuzhang"], bluffs: ["chef", "fortuneteller", "empath"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["yinyangshi", "yishi", "zhen", "tixingguan", "chef", "harpy", "yanluo"], bluffs: ["fortuneteller", "empath", "chambermaid"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["xuncha", "yinyangshi", "yishi", "zhen", "tixingguan", "shutong", "gudiao", "dianyuzhang"], bluffs: ["chef", "fortuneteller", "empath"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["yinyangshi", "yishi", "zhen", "tixingguan", "chef", "recluse", "harpy", "yanluo"], bluffs: ["fortuneteller", "empath", "chambermaid"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["yinyangshi", "yishi", "zhen", "tixingguan", "chef", "recluse", "drunk", "harpy", "yanluo"], bluffs: ["fortuneteller", "empath", "chambermaid"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["yishi", "zhen", "tixingguan", "chef", "fortuneteller", "drunk", "plaguedoctor", "marionette", "guhuoniao"], bluffs: ["empath", "chambermaid", "undertaker"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["yishi", "zhen", "tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "marionette", "gudiao", "guhuoniao"], bluffs: ["undertaker", "bingbi", "daoke"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["zhen", "tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "undertaker", "gudiao", "harpy", "dianyuzhang"], bluffs: ["bingbi", "daoke", "fangshi"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "harpy", "marionette", "yanluo"], bluffs: ["daoke", "fangshi", "xuncha"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["zhen", "tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "undertaker", "plaguedoctor", "gudiao", "harpy", "dianyuzhang"], bluffs: ["bingbi", "daoke", "fangshi"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "shutong", "harpy", "marionette", "yanluo"], bluffs: ["daoke", "fangshi", "xuncha"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["tixingguan", "chef", "fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "shutong", "recluse", "harpy", "marionette", "yanluo"], bluffs: ["daoke", "fangshi", "xuncha"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["chef", "fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "daoke", "recluse", "drunk", "marionette", "gudiao", "guhuoniao"], bluffs: ["fangshi", "xuncha", "yinyangshi"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "drunk", "plaguedoctor", "gudiao", "harpy", "dianyuzhang"], bluffs: ["xuncha", "yinyangshi", "yishi"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["chef", "fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "marionette", "gudiao", "harpy", "guhuoniao"], bluffs: ["yinyangshi", "yishi", "zhen"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "gudiao", "harpy", "marionette", "dianyuzhang"], bluffs: ["yishi", "zhen", "tixingguan"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["fortuneteller", "empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "drunk", "gudiao", "harpy", "marionette", "dianyuzhang"], bluffs: ["yishi", "zhen", "tixingguan"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "yishi", "plaguedoctor", "harpy", "marionette", "gudiao", "yanluo"], bluffs: ["zhen", "tixingguan", "chef"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["empath", "chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "yishi", "plaguedoctor", "shutong", "harpy", "marionette", "gudiao", "yanluo"], bluffs: ["zhen", "tixingguan", "chef"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["chambermaid", "undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "yishi", "zhen", "shutong", "recluse", "marionette", "gudiao", "harpy", "guhuoniao"], bluffs: ["tixingguan", "chef", "fortuneteller"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["undertaker", "bingbi", "daoke", "fangshi", "xuncha", "yinyangshi", "yishi", "zhen", "tixingguan", "recluse", "drunk", "gudiao", "harpy", "marionette", "dianyuzhang"], bluffs: ["chef", "fortuneteller", "empath"], note: "Verified setup; Lil Monsta and Godfather setup-changing paths stay out of normal templates; delayed deaths and madness outcomes remain ST-confirmed." }),
]
