import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21530_04126.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Ri Yue Xie Wang', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const riYueXieWangRoles = [
  role({"id": "chef", "name": "厨师", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png", "inputKinds": ["number"], "possibleOutcomes": ["Tell number of adjacent evil pairs."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Count adjacent evil pairs at setup/current alignment snapshot."], "playerMessageTemplates": ["There are X adjacent evil pairs."], "highRiskNotes": ["Recluse/false registration may affect what is shown."], "setupImpact": []}),
  role({"id": "investigator", "name": "调查员", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两名玩家和一个爪牙角色：这两名玩家之一是该角色（或者你会得知没有爪牙在场）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/investigator.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Tell two players and one Minion role; one is that role, or no Minion in play."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["One of these two players is the Minion role X, or no Minion is in play."], "highRiskNotes": ["Can include false positive; do not expose full grimoire."], "setupImpact": []}),
  role({"id": "empath", "name": "共情者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["number"], "possibleOutcomes": ["Tell 0, 1, or 2 evil living neighbors."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Skip dead players, then count evil living neighbors."], "playerMessageTemplates": ["Your living neighbors include 0 / 1 / 2 evil players."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "possibleOutcomes": ["Tell whether either chosen player registers as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Red herring good player registers as Demon for this ability."], "playerMessageTemplates": ["One of them is Demon: yes / no."], "highRiskNotes": ["Track red herring privately; Vortox forces false info."], "setupImpact": []}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players", "number"], "possibleOutcomes": ["Tell how many selected living players woke due to own ability tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Among them, X woke due to their own ability tonight."], "highRiskNotes": ["Only own ability wake counts; being woken by ST or other roles does not count.", "Drunk/poisoned targets who woke due to their own ability still count; a false number only comes from the Chambermaid herself being drunk/poisoned."], "setupImpact": []}),
  role({"id": "gossip", "name": "造谣者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "possibleOutcomes": ["If public statement is true, a player may die tonight."], "stateChanges": ["May cause extra death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Record public statement and verify it tonight."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "custom", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["players", "text"], "possibleOutcomes": ["Once per game, tell whether two chosen players share alignment."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Compare current confirmed alignment of two targets."], "playerMessageTemplates": ["They are the same alignment: yes / no."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "savant", "name": "博学者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "possibleOutcomes": ["Give two statements: one true and one false."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Statement A / Statement B, exactly one is true."], "highRiskNotes": ["AI can draft pairs, but ST chooses final truth/false balance."], "setupImpact": []}),
  role({"id": "ranfangfangzhu", "name": "染坊坊主", "officialName": "custom", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，恶魔的能力变成“每个夜晚*，可能会有一名玩家死亡。”", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_0616062943171_bbdbbb4c.jpg", "inputKinds": ["role"], "possibleOutcomes": ["If killed at night, Demon ability becomes may-kill-one-player each night."], "stateChanges": ["Changes Demon kill cadence after night death."], "identityChanges": ["No Demon identity change; only ability effect changes."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only night death triggers this ability."], "setupImpact": []}),
  role({"id": "xuncha", "name": "巡察", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的两个善良角色：如果他们都存活，他们当晚不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_7108682943171_ed7a0042.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Choose two good roles; if both alive, they do not die tonight."], "stateChanges": ["May protect chosen good-role players from death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Targets are roles, not seats; verify both are good roles and alive."], "setupImpact": []}),
  role({"id": "yinluren", "name": "引路人", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择至多三名玩家：你会得知今晚是否有邪恶玩家的能力选择或影响了他们之中的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_2147287694761_01761fcb.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Tell whether evil ability chose or affected one selected target tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Check evil ability choice and effect scope."], "playerMessageTemplates": ["Did evil ability choose or affect one of them tonight: yes / no."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "qintianjian", "name": "钦天监", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知离你最近的邪恶玩家位于你的哪一侧（左/右/相同）。如果与你邻近的玩家中有邪恶阵营，你会得知错误信息。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4484677694761_241d43f7.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Tell left, right, or same side for nearest evil player."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Check evil seat positions."], "playerMessageTemplates": ["Nearest evil player is on: left / right / same."], "highRiskNotes": ["If a neighboring player is evil (alive or dead), the info MUST be false: pick an answer among left/right/same that differs from the correct one.", "Dead players also count when measuring distance to the nearest evil player."], "setupImpact": []}),
  role({"id": "zhifu", "name": "知府", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天是否有非镇民且非旅行者玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_2565080943171_2bd68241.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Tell whether a non-Townsfolk non-Traveler died today.", "\"Today\" covers all deaths of the day including night deaths before Zhifu wakes, regardless of cause.", "Judge by the character type at the moment of death, even if the character changed afterwards.", "Zhifu wakes even if nobody died today."], "stateChanges": ["Depends on the full death log for the day, including night deaths before Zhifu wakes."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Did a non-Townsfolk non-Traveler die today: yes / no."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "custom", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["role"], "possibleOutcomes": ["Player thinks they are a Townsfolk but has no real ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Send false Townsfolk identity, not Drunk."], "highRiskNotes": ["Track false identity privately."], "setupImpact": []}),
  role({"id": "shutong", "name": "书童", "officialName": "custom", "team": "outsider", "abilityText": "在你的首个夜晚，你要选择除你以外的一名玩家：除首个夜晚以外，当他被邪恶玩家的能力选择或影响时，你会在当晚死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_2027903943171_36d374a5.jpg", "inputKinds": ["player"], "possibleOutcomes": ["First night choose a player; after first night, die if that player is chosen or affected by evil ability."], "stateChanges": ["May die at night after evil choice/effect."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Record first-night anchor target and check later evil choices/effects."], "setupImpact": []}),
  role({"id": "recluse", "name": "陌客", "officialName": "custom", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "possibleOutcomes": ["May register as evil, Minion, or Demon, even when dead."], "stateChanges": [], "identityChanges": [], "teamChanges": ["False registration can affect info roles."], "playerMessageTemplates": [], "highRiskNotes": ["ST discretion; AI should only flag possible Recluse registration."], "setupImpact": []}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "custom", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["When learning death, publicly choose a living player; if evil, the Klutz's own team loses (if the Klutz has become evil and chooses an evil player, good wins instead)."], "stateChanges": ["Death triggers public choice."], "identityChanges": [], "teamChanges": ["Check chosen player current alignment."], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss remains ST authority."], "setupImpact": []}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "custom", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["role"], "possibleOutcomes": ["If Demon dies with 5+ players alive, become that Demon."], "stateChanges": ["May preserve Demon line."], "identityChanges": ["Scarlet Woman becomes Demon role."], "teamChanges": ["Scarlet Woman becomes evil Demon."], "playerMessageTemplates": [], "highRiskNotes": ["Only if 5+ non-Traveler players alive; ST confirms before identity change."], "setupImpact": []}),
  role({"id": "assassin", "name": "刺客", "officialName": "custom", "team": "minion", "abilityText": "每局游戏限一次，在夜晚时*，你可以选择一名玩家：他死亡，即使因为任何原因让他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/assassin.png", "inputKinds": ["player"], "possibleOutcomes": ["Once per game choose a player to die even if protected."], "stateChanges": ["Target dies unless ST rules otherwise."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Once per game; bypasses many protections but ST confirms final death."], "setupImpact": []}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "custom", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["role"], "possibleOutcomes": ["Thinks they are good, but is evil; Demon knows Marionette."], "stateChanges": [], "identityChanges": ["False good role shown to Marionette."], "teamChanges": ["Actual alignment is evil."], "playerMessageTemplates": [], "highRiskNotes": ["Setup adjacency constraint and false identity must be tracked privately."], "setupImpact": ["Marionette neighbors the Demon."]}),
  role({"id": "niangjiushi", "name": "酿酒师", "officialName": "custom", "team": "minion", "abilityText": "每个夜晚，你要选择一个镇民角色：当他下一次通过自身能力获取信息时，改为得知你给出的信息。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_3356597694761_0a4b67e6.jpg", "inputKinds": ["role", "text"], "possibleOutcomes": ["Choose a Townsfolk role; next time they gain info, they receive brewer-provided info instead."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Next info for chosen Townsfolk role is replaced by your message."], "highRiskNotes": ["Track role target and consume on next self-ability info gain."], "setupImpact": []}),
  role({"id": "aohe", "name": "奥赫", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一个角色：他死亡。如果该角色不在场，则由说书人来决定谁会被你杀死。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_6886084308961_f221dd48.jpg", "inputKinds": ["role"], "possibleOutcomes": ["Choose a role to die; if role is not in play, ST chooses who is killed."], "stateChanges": ["Chosen in-play role dies, or ST-selected fallback dies."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Target is role, not seat; if absent, storyteller chooses death."], "setupImpact": []}),
  role({"id": "baojun", "name": "暴君", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你杀死了与爪牙邻近的玩家，下个夜晚你可以选择至多两名玩家：他们死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_6000301943171_d2f257a6.jpg", "inputKinds": ["players", "number"], "possibleOutcomes": ["Each night* choose one player: they die.", "If Baojun killed a player neighboring a Minion last night, tonight Baojun may choose up to two players to die; choosing only one or none is allowed."], "stateChanges": ["Kills one player each night; up to two players the night after killing a Minion-adjacent player."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Rampage (up to two kills) triggers only if the Minion-adjacent target actually died; if that player survived for any reason, Baojun may only choose one player. Track with a rampage reminder."], "setupImpact": []}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["players"], "possibleOutcomes": ["Choose one player to die; nearest two Townsfolk are poisoned."], "stateChanges": ["Target dies; nearest Townsfolk poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Check nearest Townsfolk by seats; do not auto-apply without confirmation."], "setupImpact": []}),
  role({"id": "vortox", "name": "涡流", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。镇民玩家的能力都会产生错误信息。如果白天没人被处决，邪恶阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vortox.png", "inputKinds": ["player"], "possibleOutcomes": ["Choose one player to die; Townsfolk info is false."], "stateChanges": ["Target dies; no execution can affect win condition."], "identityChanges": [], "teamChanges": ["All Townsfolk info abilities must be false."], "playerMessageTemplates": [], "highRiskNotes": ["AI can remind false info; ST confirms win/loss."], "setupImpact": []}),
] as const satisfies readonly SmartRoleDefinition[]
