import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "ri-yue-xie-wang"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const riYueXieWangSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["savant", "ranfangfangzhu", "xuncha", "yinluren", "qintianjian", "assassin", "vortox"], bluffs: ["zhifu", "chef", "investigator"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["ranfangfangzhu", "xuncha", "yinluren", "qintianjian", "zhifu", "niangjiushi", "aohe"], bluffs: ["chef", "investigator", "empath"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["xuncha", "yinluren", "qintianjian", "zhifu", "chef", "scarletwoman", "baojun"], bluffs: ["investigator", "empath", "fortuneteller"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["ranfangfangzhu", "xuncha", "yinluren", "qintianjian", "zhifu", "drunk", "niangjiushi", "aohe"], bluffs: ["chef", "investigator", "empath"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["xuncha", "yinluren", "qintianjian", "zhifu", "chef", "shutong", "scarletwoman", "baojun"], bluffs: ["investigator", "empath", "fortuneteller"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["xuncha", "yinluren", "qintianjian", "zhifu", "chef", "shutong", "recluse", "scarletwoman", "baojun"], bluffs: ["investigator", "empath", "fortuneteller"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["yinluren", "qintianjian", "zhifu", "chef", "investigator", "recluse", "klutz", "assassin", "nodashii"], bluffs: ["empath", "fortuneteller", "chambermaid"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["yinluren", "qintianjian", "zhifu", "chef", "investigator", "empath", "fortuneteller", "assassin", "niangjiushi", "nodashii"], bluffs: ["chambermaid", "gossip", "seamstress"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["qintianjian", "zhifu", "chef", "investigator", "empath", "fortuneteller", "chambermaid", "niangjiushi", "scarletwoman", "vortox"], bluffs: ["gossip", "seamstress", "savant"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["zhifu", "chef", "investigator", "empath", "fortuneteller", "chambermaid", "gossip", "scarletwoman", "assassin", "aohe"], bluffs: ["seamstress", "savant", "ranfangfangzhu"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["qintianjian", "zhifu", "chef", "investigator", "empath", "fortuneteller", "chambermaid", "klutz", "niangjiushi", "scarletwoman", "vortox"], bluffs: ["gossip", "seamstress", "savant"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["zhifu", "chef", "investigator", "empath", "fortuneteller", "chambermaid", "gossip", "drunk", "scarletwoman", "assassin", "aohe"], bluffs: ["seamstress", "savant", "ranfangfangzhu"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["zhifu", "chef", "investigator", "empath", "fortuneteller", "chambermaid", "gossip", "drunk", "shutong", "scarletwoman", "assassin", "aohe"], bluffs: ["seamstress", "savant", "ranfangfangzhu"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["chef", "investigator", "empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "shutong", "recluse", "assassin", "niangjiushi", "baojun"], bluffs: ["savant", "ranfangfangzhu", "xuncha"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["investigator", "empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "recluse", "klutz", "niangjiushi", "scarletwoman", "nodashii"], bluffs: ["ranfangfangzhu", "xuncha", "yinluren"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["chef", "investigator", "empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "assassin", "niangjiushi", "scarletwoman", "baojun"], bluffs: ["xuncha", "yinluren", "qintianjian"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["investigator", "empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "niangjiushi", "scarletwoman", "assassin", "nodashii"], bluffs: ["yinluren", "qintianjian", "zhifu"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["investigator", "empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "recluse", "niangjiushi", "scarletwoman", "assassin", "nodashii"], bluffs: ["yinluren", "qintianjian", "zhifu"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "yinluren", "klutz", "scarletwoman", "assassin", "niangjiushi", "vortox"], bluffs: ["qintianjian", "zhifu", "chef"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["empath", "fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "yinluren", "klutz", "drunk", "scarletwoman", "assassin", "niangjiushi", "vortox"], bluffs: ["qintianjian", "zhifu", "chef"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["fortuneteller", "chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "yinluren", "qintianjian", "drunk", "shutong", "assassin", "niangjiushi", "scarletwoman", "aohe"], bluffs: ["zhifu", "chef", "investigator"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["chambermaid", "gossip", "seamstress", "savant", "ranfangfangzhu", "xuncha", "yinluren", "qintianjian", "zhifu", "shutong", "recluse", "niangjiushi", "scarletwoman", "assassin", "baojun"], bluffs: ["chef", "investigator", "empath"], note: "Verified setup; Marionette adjacency, Scarlet Woman continuity, Vortox false info, and Demon kill variants remain storyteller-confirmed reminders." }),
]
