import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "hu-yan-luan-yu"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const huYanLuanYuSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["highpriestess", "poppygrower", "grandmother", "yinyangshi", "bianlianshi", "yangguren", "dianyuzhang"], bluffs: ["gossip", "langzhong", "gambler"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "yangguren", "dianyuzhang"], bluffs: ["slayer", "courtier", "chambermaid"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["langzhong", "gambler", "slayer", "courtier", "chambermaid", "yangguren", "dianyuzhang"], bluffs: ["savant", "lunatic", "drunk"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["poppygrower", "grandmother", "yinyangshi", "bianlianshi", "gossip", "drunk", "scarletwoman", "yaggababble"], bluffs: ["langzhong", "gambler", "slayer"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["bianlianshi", "gossip", "langzhong", "gambler", "slayer", "lunatic", "scarletwoman", "yaggababble"], bluffs: ["courtier", "chambermaid", "savant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "mutant", "golem", "cerenovus", "nodashii"], bluffs: ["gambler", "slayer", "courtier"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["gossip", "langzhong", "gambler", "slayer", "courtier", "drunk", "mutant", "cerenovus", "nodashii"], bluffs: ["chambermaid", "savant", "lunatic"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["highpriestess", "poppygrower", "grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "yangguren", "scarletwoman", "dianyuzhang"], bluffs: ["gambler", "slayer", "courtier"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "yangguren", "scarletwoman", "dianyuzhang"], bluffs: ["chambermaid", "savant", "lunatic"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["langzhong", "gambler", "slayer", "courtier", "chambermaid", "savant", "highpriestess", "yangguren", "scarletwoman", "dianyuzhang"], bluffs: ["drunk", "mutant", "golem"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["poppygrower", "grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "drunk", "scarletwoman", "cerenovus", "yaggababble"], bluffs: ["slayer", "courtier", "chambermaid"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "lunatic", "scarletwoman", "cerenovus", "yaggababble"], bluffs: ["savant", "drunk", "mutant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "mutant", "golem", "cerenovus", "yangguren", "nodashii"], bluffs: ["courtier", "chambermaid", "savant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "savant", "drunk", "mutant", "cerenovus", "yangguren", "nodashii"], bluffs: ["lunatic", "golem", "highpriestess"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["slayer", "courtier", "chambermaid", "savant", "highpriestess", "poppygrower", "grandmother", "lunatic", "drunk", "cerenovus", "yangguren", "nodashii"], bluffs: ["bianlianshi", "gossip", "langzhong"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["highpriestess", "poppygrower", "grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "yangguren", "scarletwoman", "cerenovus", "dianyuzhang"], bluffs: ["courtier", "chambermaid", "savant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "savant", "yangguren", "scarletwoman", "cerenovus", "dianyuzhang"], bluffs: ["lunatic", "drunk", "mutant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "mutant", "cerenovus", "yangguren", "scarletwoman", "nodashii"], bluffs: ["savant", "lunatic", "drunk"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "savant", "highpriestess", "poppygrower", "drunk", "cerenovus", "yangguren", "scarletwoman", "nodashii"], bluffs: ["golem", "grandmother", "yinyangshi"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["poppygrower", "grandmother", "yinyangshi", "bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "drunk", "mutant", "scarletwoman", "cerenovus", "yangguren", "yaggababble"], bluffs: ["chambermaid", "savant", "lunatic"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["bianlianshi", "gossip", "langzhong", "gambler", "slayer", "courtier", "chambermaid", "savant", "highpriestess", "lunatic", "drunk", "scarletwoman", "cerenovus", "yangguren", "yaggababble"], bluffs: ["golem", "poppygrower", "grandmother"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["gambler", "slayer", "courtier", "chambermaid", "savant", "highpriestess", "poppygrower", "grandmother", "yinyangshi", "golem", "lunatic", "scarletwoman", "cerenovus", "yangguren", "yaggababble"], bluffs: ["langzhong", "drunk", "mutant"], note: "Verified setup; Village Idiot, Fang Gu and Marionette setup-changing paths stay out of normal templates; Poppy Grower, Cerenovus, Gambler, Yaggababble, No Dashii and custom demon outcomes remain ST-confirmed." }),
]
