import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20725_52289.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Tian Tang Hua Yuan', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const tianTangHuaYuanRoles = [
  role({"id": "clockmaker", "name": "钟表匠", "officialName": "Clockmaker", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知恶魔与爪牙之间最近的距离。（邻座的玩家距离为1）", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/clockmaker.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Clockmaker distance information is calculated from confirmed evil positions; answer stays ST-confirmed."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Pixie learned role, madness and later gained ability are manual reminders only."]}),
  role({"id": "empath", "name": "共情者", "officialName": "Empath", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Empath number can be affected by drunk, poison and registration; answer stays ST-confirmed."]}),
  role({"id": "dreamer", "name": "筑梦师", "officialName": "Dreamer", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你及旅行者以外的一名玩家：你会得知一个善良角色和一个邪恶角色，该玩家是其中一个角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/dreamer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Dreamer receives one good and one evil character for the target; poisoning and registration can affect the pair."]}),
  role({"id": "king", "name": "国王", "officialName": "King", "team": "townsfolk", "abilityText": "每个夜晚，如果死亡的玩家数量大于或等于存活的玩家数量，你会得知一个存活的角色。恶魔知道你是国王。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/king.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "King information and Demon knowledge of the King are private/manual; do not auto-message evil team."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Fortune Teller uses red herring and Demon registration; yes/no answer stays ST-confirmed."]}),
  role({"id": "gambler", "name": "赌徒", "officialName": "Gambler", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家并猜测他的角色：如果你猜错了，你会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gambler.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Gambler guess may kill the Gambler if wrong; death is only a candidate until ST confirms."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Oracle dead-evil count depends on confirmed deaths, alignment and registration; answer stays ST-confirmed."]}),
  role({"id": "innkeeper", "name": "旅店老板", "officialName": "Innkeeper", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择两名玩家：他们当晚不会死亡，但其中一人会醉酒到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/innkeeper.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Innkeeper protects chosen players and makes one drunk; protection/drunk state remains candidate-only."]}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "Chambermaid", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Chambermaid count depends on who woke due to their ability; answer stays ST-confirmed."]}),
  role({"id": "slayer", "name": "猎手", "officialName": "Slayer", "team": "townsfolk", "abilityText": "每局游戏限一次，你可以在白天时公开选择一名玩家：如果他是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/slayer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Slayer shot can kill the Demon once per game; death remains ST-confirmed."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Philosopher gains a good character ability and can make the real holder drunk; ability/drunk changes are manual."]}),
  role({"id": "choirboy", "name": "唱诗男孩", "officialName": "Choirboy", "team": "townsfolk", "abilityText": "如果恶魔杀死了国王，你会得知哪名玩家是恶魔。[+国王]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/choirboy.png", "inputKinds": ["none"], "setupImpact": ["[国王在场]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Choirboy is a setup path tied to King presence and Demon killing the King; excluded from first normal templates."]}),
  role({"id": "recluse", "name": "陌客", "officialName": "Recluse", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Recluse may register as evil, Minion or Demon; AI may remind but never decides registration automatically."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["[隐藏酒鬼身份]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Drunk hidden real identity and shown Townsfolk are manual/private; excluded from first normal templates."]}),
  role({"id": "goon", "name": "莽夫", "officialName": "Goon", "team": "outsider", "abilityText": "每个夜晚，首个使用其自身能力选择了你的玩家会醉酒直到下个黄昏。你会转变为他的阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/goon.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Goon can drunk the first chooser and become their alignment; alignment/drunk changes are manual."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Klutz death choice can make the Klutz's team lose if an evil player is chosen (an evil Klutz choosing an evil player makes good win); never auto-judge loss."]}),
  role({"id": "barber", "name": "理发师", "officialName": "Barber", "team": "outsider", "abilityText": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Barber death may let the Demon swap two player characters; identity changes affect later night order only after confirmation."]}),
  role({"id": "witch", "name": "女巫", "officialName": "Witch", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：如果他明天白天发起提名，他死亡。如果只有三名存活的玩家，你失去此能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/witch.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Witch curse can kill a nominated target; death remains ST-confirmed and public flow stays manual."]}),
  role({"id": "spy", "name": "间谍", "officialName": "Spy", "team": "minion", "abilityText": "每个夜晚，你能查看魔典。你可能会被当作善良阵营、镇民角色或外来者角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/spy.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Spy sees the grimoire and may register as good or Townsfolk; no player data is auto-exposed."]}),
  role({"id": "baron", "name": "男爵", "officialName": "Baron", "team": "minion", "abilityText": "会有额外的外来者在场。[+2 外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/baron.png", "inputKinds": ["none"], "setupImpact": ["[+2外来者]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Baron adds two Outsiders; excluded from first normal templates until ST chooses that setup path."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "Marionette", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["none"], "setupImpact": ["[隐藏爪牙相邻恶魔]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Marionette hidden Minion setup and Demon adjacency are manual/private; excluded from first normal templates."]}),
  role({"id": "vizier", "name": "维齐尔", "officialName": "Vizier", "team": "minion", "abilityText": "所有玩家都知道你是维齐尔。你在白天时不会死亡。如果一次提名中有善良玩家投票，你可以让被提名者立即被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202304/c_8651385151861_48d3dd5d.jpg", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Vizier public presence and day execution option are manual; never auto-execute or auto-win."]}),
  role({"id": "alhadikhia", "name": "哈迪寂亚", "officialName": "Al-Hadikhia", "team": "demon", "abilityText": "每个夜晚*，你可以选择三名玩家（所有玩家都会得知你选了谁）：他们分别秘密决定自己的生死，然后如果他们都存活则都死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/al-hadikhia.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution or drunk/poison state."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Al-Hadikhia chooses three targets and death/revival choices are complex; all state changes remain ST-confirmed.", "Al-Hadikhia may decline to choose; if so, the storyteller makes no announcement and no one dies from this ability that night."]}),
] as const satisfies readonly SmartRoleDefinition[]
