import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "tian-tang-hua-yuan"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const tianTangHuaYuanSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["slayer", "gambler", "innkeeper", "empath", "dreamer", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "recluse", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "goon", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "recluse", "goon", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "goon", "barber", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "witch", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "spy", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["slayer", "gambler", "innkeeper", "empath", "dreamer", "fortuneteller", "pixie", "vizier", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "recluse", "witch", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "goon", "spy", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "recluse", "goon", "witch", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "goon", "barber", "spy", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["slayer", "gambler", "innkeeper", "empath", "dreamer", "fortuneteller", "pixie", "klutz", "barber", "vizier", "witch", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "oracle", "innkeeper", "witch", "spy", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "chambermaid", "oracle", "spy", "witch", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "oracle", "innkeeper", "recluse", "witch", "spy", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "chambermaid", "oracle", "goon", "spy", "witch", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "dreamer", "king", "fortuneteller", "gambler", "oracle", "innkeeper", "recluse", "goon", "witch", "spy", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["pixie", "dreamer", "fortuneteller", "philosopher", "king", "clockmaker", "empath", "chambermaid", "oracle", "goon", "barber", "spy", "witch", "vizier", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["slayer", "gambler", "innkeeper", "empath", "dreamer", "fortuneteller", "pixie", "oracle", "chambermaid", "klutz", "barber", "vizier", "witch", "spy", "alhadikhia"], "bluffs": ["choirboy", "drunk", "baron"], "note": "Verified normal setup; Choirboy, Drunk, Baron and Marionette setup/hidden-identity paths stay manual. Al-Hadikhia, Vizier, Witch, Barber, Goon, Gambler, Innkeeper, Philosopher, Pixie, Slayer and Klutz outcomes remain ST-confirmed."}),
]
