import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20747_59942.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Hui Xuan Mi Zhen', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const huiXuanMiZhenRoles = [
  role({"id": "investigator", "name": "调查员", "officialName": "Investigator", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两名玩家和一个爪牙角色：这两名玩家之一是该角色（或者你会得知没有爪牙在场）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/investigator.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Investigator result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "chef", "name": "厨师", "officialName": "Chef", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Chef result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Pixie result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "empath", "name": "共情者", "officialName": "Empath", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Empath result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Fortune Teller result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "towncrier", "name": "城镇公告员", "officialName": "Town Crier", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知在今天白天时是否有爪牙发起过提名。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/town_crier.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Town Crier result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Oracle result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Savant result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Fisherman result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Seamstress result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Philosopher result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "farmer", "name": "农夫", "officialName": "Farmer", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，一名存活的善良玩家会变成农夫。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/farmer.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Farmer result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Cannibal result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "butler", "name": "管家", "officialName": "Butler", "team": "outsider", "abilityText": "每个夜晚，你要选择除你以外的一名玩家：明天白天，只有他投票时你才能投票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/butler.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Butler result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "recluse", "name": "陌客", "officialName": "Recluse", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Recluse result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "mutant", "name": "畸形秀演员", "officialName": "Mutant", "team": "outsider", "abilityText": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mutant.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Mutant result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["Source setup reminder", "[Hidden Drunk identity]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Drunk hidden identity is manual/private; excluded from first normal templates."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["none"], "setupImpact": ["[-1或+1外来者]", "[Outsider count may change]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Godfather Outsider count path stays manual; excluded from first normal templates."]}),
  role({"id": "widow", "name": "寡妇", "officialName": "Widow", "team": "minion", "abilityText": "在你的首个夜晚，你能查看魔典并选择一名玩家：他中毒。随后，始终会有一名善良玩家知道寡妇在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/widow.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Widow result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "Cerenovus", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Cerenovus result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "Marionette", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["none"], "setupImpact": ["[提线木偶会与恶魔邻座]", "[Hidden Minion adjacent to Demon]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Marionette can appear in high-player templates only with storyteller adjacency/hidden identity check."]}),
  role({"id": "lilmonsta", "name": "小怪宝", "officialName": "Lil' Monsta", "team": "demon", "abilityText": "每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，可能会有一名玩家死亡。[+1爪牙]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lil_monsta.png", "inputKinds": ["none"], "setupImpact": ["[+1爪牙]", "[Special Demon setup]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Lil' Monsta special Demon babysitter setup stays manual; excluded from first normal templates."]}),
  role({"id": "vigormortis", "name": "亡骨魔", "officialName": "Vigormortis", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vigormortis.png", "inputKinds": ["none"], "setupImpact": ["[-1外来者]", "[Minion-killed setup/poison reminder]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Vigormortis setup/neighbor poison path stays manual; excluded from first normal templates."]}),
  role({"id": "vortox", "name": "涡流", "officialName": "Vortox", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。镇民玩家的能力都会产生错误信息。如果白天没人被处决，邪恶阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vortox.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Vortox result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "legion", "name": "军团", "officialName": "Legion", "team": "demon", "abilityText": "每个夜晚*，可能有一名玩家死亡。如果一项提名只有邪恶玩家投票，投票无效。你也会被当作是爪牙。[半数以上玩家为军团]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/legion.png", "inputKinds": ["none"], "setupImpact": ["[半数以上玩家为军团]", "[Special Legion setup]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Legion special setup/voting path stays manual; excluded from first normal templates."]}),
  role({"id": "barista", "name": "咖啡师", "officialName": "Barista", "team": "traveler", "abilityText": "每个夜晚，直至下个黄昏，由说书人二选一：1）一名玩家解除并免受醉酒和中毒影响，且会得知正确信息；2）一名玩家的能力可以生效两次。该玩家会得知是哪个效果。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barista.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Traveler roles never enter normal setup templates or demon bluffs.", "Traveler roles never enter normal setup templates or demon bluffs."]}),
  role({"id": "apprentice", "name": "学徒", "officialName": "Apprentice", "team": "traveler", "abilityText": "在你的首个夜晚，如果你是善良的，你会获得一个镇民角色的能力；如果你是邪恶的，你会获得一个爪牙角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/apprentice.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Traveler roles never enter normal setup templates or demon bluffs.", "Traveler roles never enter normal setup templates or demon bluffs."]}),
  role({"id": "beggar", "name": "乞丐", "officialName": "Beggar", "team": "traveler", "abilityText": "你只能使用投票标记投票。死亡的玩家可以将他的投票标记给你，如果他这么做，你会得知他的阵营。你不会中毒和醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/beggar.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Traveler roles never enter normal setup templates or demon bluffs.", "Traveler roles never enter normal setup templates or demon bluffs."]}),
  role({"id": "scapegoat", "name": "替罪羊", "officialName": "Scapegoat", "team": "traveler", "abilityText": "如果你的阵营的一名玩家被处决，你可能会代替他被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scapegoat.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Traveler roles never enter normal setup templates or demon bluffs.", "Traveler roles never enter normal setup templates or demon bluffs."]}),
  role({"id": "voudon", "name": "巫毒师", "officialName": "Voudon", "team": "traveler", "abilityText": "只有你和死亡的玩家可以投票，且投票不需要使用投票标记。忽略票数需要过半的要求。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/voudon.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Traveler roles never enter normal setup templates or demon bluffs.", "Traveler roles never enter normal setup templates or demon bluffs."]}),
] as const satisfies readonly SmartRoleDefinition[]
