import { expect, test } from '@playwright/test'

test('game end prototype saves an archive and opens AI historical review', async ({ page }) => {
  await page.setViewportSize({ width: 1180, height: 900 })
  await page.goto('/')
  await page.evaluate(() => window.localStorage.clear())
  await page.reload()

  await page.locator('.dashboard__end-entry').click()
  await expect(page.locator('.game-end')).toBeVisible()
  await page.locator('.game-end__winner-grid button').first().click()
  await page.getByRole('button', { name: '保存本局' }).click()
  await expect(page.locator('.game-end__notice')).toContainText('本局已保存到本机浏览器')
  await expect(page.getByLabel('当前归档存储位置')).toContainText('已保存：本机浏览器')
  const resetStep = page.locator('.game-end__finish-step--danger')
  await expect(resetStep.getByRole('button', { name: '重置游戏' })).toBeDisabled()
  await page.screenshot({ path: 'artifacts/screenshots/game-end-2026-07-16/01-game-end-page.png', fullPage: false })

  await page.getByRole('button', { name: '历史复盘' }).click()
  await expect(page.locator('.game-review')).toBeVisible()
  await expect(page.locator('.game-review__filter')).toContainText('选择日期')
  await expect(page.locator('.game-review__filter select')).toHaveValue('all')
  await expect(page.locator('.game-review__list button')).toHaveCount(1)
  await expect(page.locator('.game-review__detail')).toContainText('善良获胜')
  await expect(page.locator('.game-review__detail')).not.toContainText('对局详情')
  await expect(page.locator('.game-review__log-section')).toContainText('当局日志')
  await expect(page.locator('.game-ai-review')).toContainText('AI复盘草稿')
  await expect(page.locator('.game-ai-review')).toContainText('玩家评分草稿')
  await expect(page.locator('.game-ai-review')).toContainText('锐评')
  await expect(page.locator('.game-ai-review')).toContainText('当局评价')
  await expect(page.locator('.game-ai-review')).toContainText('整局复盘')
  await page.screenshot({ path: 'artifacts/screenshots/game-end-2026-07-16/02-game-review-history.png', fullPage: false })

  await page.reload()
  await page.locator('.dashboard__review-entry').click()
  await expect(page.locator('.game-review__list button')).toHaveCount(1)
  await expect(page.locator('.game-ai-review')).toContainText('AI复盘草稿')

  await page.getByLabel('关闭').click()
  await page.locator('.dashboard__end-entry').click()
  await page.getByRole('button', { name: '保存本局' }).click()
  await page.getByLabel('我已保存本局，确认重置游戏').check()
  await page.locator('.game-end__finish-step--danger').getByRole('button', { name: '重置游戏' }).click()
  await expect(page.locator('.dashboard')).toBeVisible()
  await expect(page.locator('.game-end')).toBeHidden()
  await expect(page.getByRole('heading', { name: 'AI配板与调整' })).toBeVisible()
  await expect(page.getByText('选择人数')).toBeVisible()
  const resetState = await page.evaluate(() => JSON.parse(window.localStorage.getItem('botc-copilot-session-v1') ?? '{}'))
  expect(resetState.playerCount).toBe(0)
  expect(resetState.seats).toEqual({})
  expect(resetState.initialPlayerStates).toEqual({})
  expect(resetState.timeline).toEqual([])
  expect(resetState.phaseSegments).toEqual([])
  expect(resetState.nightRuns).toEqual({})
  expect(resetState.activeNightRunId).toBeNull()
  expect(resetState.dayVoteDraft).toBeNull()
  expect(resetState.dayActionDraft).toBeNull()

  await page.getByRole('button', { name: '关闭AI配板与调整' }).click()
  await expect(page.locator('.dashboard__player-empty')).toContainText('暂无玩家')
  await expect(page.locator('.dashboard__stage-overview')).toContainText('待配板')
  await page.locator('.dashboard__script-switch').click()
  await expect(page.locator('.script-library')).toBeVisible()
  await page.locator('.script-library__script-actions .ui-button--primary').first().click()
  await expect(page.locator('.script-library')).toBeHidden()
  await expect(page.getByRole('heading', { name: 'AI配板与调整' })).toBeVisible()
  await page.getByLabel('开局板子').selectOption('quick-maths')
  await expect(page.getByLabel('开局板子')).toHaveValue('quick-maths')
  await page.getByLabel('开局板子').selectOption('devout-theists')
  await expect(page.getByLabel('开局板子')).toHaveValue('devout-theists')
  await page.getByRole('button', { name: '12人' }).click()
  await page.getByRole('button', { name: '开始配板' }).click()
  const setupShell = await page.evaluate(() => JSON.parse(window.localStorage.getItem('botc-copilot-session-v1') ?? '{}'))
  expect(setupShell.playerCount).toBe(12)
  expect(setupShell.scriptId).toBe('devout-theists')
  expect(Object.keys(setupShell.seats)).toHaveLength(12)
  expect(Object.keys(setupShell.initialPlayerStates)).toHaveLength(12)
  expect(setupShell.timeline).toEqual([])
  expect(setupShell.phaseSegments).toEqual([])

  await expect(page.locator('.setup-panel__candidates')).toBeVisible()
  await expect(page.locator('.setup-candidate')).toHaveCount(3)
  await page.locator('.setup-candidate .setup-candidate__actions .ui-button--secondary').first().click()
  await expect(page.locator('.setup-panel__draft')).toBeVisible()
  await page.locator('.setup-panel__footer .ui-button--primary').click()
  await expect(page.locator('.setup-panel')).toBeHidden()
  const confirmedSetup = await page.evaluate(() => JSON.parse(window.localStorage.getItem('botc-copilot-session-v1') ?? '{}'))
  const setupEntry = confirmedSetup.timeline.find((entry: { kind: string }) => entry.kind === 'setup_confirmed')
  expect(setupEntry.setup.draft.assignments).toHaveLength(12)

  await page.locator('.dashboard__identity-entry').click()
  await expect(page.locator('.identity-deal__seat-grid button')).toHaveCount(12)
  await page.locator('.sheet-content--identity-deal .sheet-close').click()

  await page.locator('.dashboard__phase-button').first().click()
  await expect(page.locator('.night-workbench')).toBeVisible()
  const nightState = await page.evaluate(() => JSON.parse(window.localStorage.getItem('botc-copilot-session-v1') ?? '{}'))
  const run = nightState.nightRuns[nightState.activeNightRunId]
  const roleBySeat = new Map(setupEntry.setup.draft.assignments.map((assignment: { seatId: number; role: { id: string } }) => [assignment.seatId, assignment.role.id]))
  expect(run.phaseSegmentId).toBe(nightState.phaseSegments.find((segment: { kind: string }) => segment.kind === 'night').id)
  expect(run.queue.length).toBeGreaterThan(0)
  expect(run.queue.every((item: { seatId: number; roleId: string }) => roleBySeat.get(item.seatId) === item.roleId)).toBe(true)
})
