import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20941_46818.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-21'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return {
    id: input.id,
    name: input.name,
    officialName: input.officialName,
    team: input.team,
    abilityText: input.abilityText,
    iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`,
    inputKinds: input.inputKinds,
    knowledgeStatus: 'confirmed',
    research: research(input),
  }
}

function research(input: RoleInput): RoleResearchMetadata {
  return {
    edition: "妙山封仙",
    setupImpact: input.setupImpact ?? [],
    possibleOutcomes: input.possibleOutcomes ?? [],
    stateChanges: input.stateChanges ?? [],
    identityChanges: input.identityChanges ?? [],
    teamChanges: input.teamChanges ?? [],
    playerMessageTemplates: input.playerMessageTemplates ?? [],
    highRiskNotes: input.highRiskNotes ?? [],
    sourceUrls: [sourceUrl, rolesSourceUrl],
    reviewedAt,
  }
}

export const miaoShanFengXianRoles = [
  role({
    id: "shugenja",
    name: "修行者",
    officialName: "shugenja",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知距离最近的邪恶玩家位于你的顺时针还是逆时针方向。如果两侧的邪恶玩家与你距离相等，你得知的信息由说书人决定。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/1697467722_197011_6238.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn the nearest evil is {direction}."],
    highRiskNotes: ["First-night source reminder: 唤醒修行者，对其用拇指指向其左侧或右侧示意。"],
  }),
  role({
    id: "knight",
    name: "骑士",
    officialName: "knight",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知两名非恶魔玩家。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/knight.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn seats {seats} are not the Demon."],
    highRiskNotes: ["First-night source reminder: 唤醒骑士，然后指向标记了“得知”的两名玩家。"],
  }),
  role({
    id: "pixie",
    name: "小精灵",
    officialName: "pixie",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/pixie.png",
    inputKinds: ["none"],
    identityChanges: ["May gain shown Townsfolk ability after that role dies if madness was kept."],
    highRiskNotes: ["Pixie madness and later ability gain are manual reminders; do not auto-grant ability.", "First-night source reminder: 对小精灵展示一个在场的镇民角色。"],
  }),
  role({
    id: "sailor",
    name: "水手",
    officialName: "sailor",
    team: "townsfolk",
    abilityText: "每个夜晚，你要选择一名存活的玩家：你或他之一会醉酒直到下个黄昏。你不会死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/sailor.png",
    inputKinds: ["none"],
    stateChanges: ["Sailor or chosen player may be drunk until dusk."],
    highRiskNotes: ["Sailor drunkenness and death prevention require storyteller confirmation.", "First-night source reminder: 让水手选择一名存活玩家。标记那名玩家或水手醉酒。", "Other-night source reminder: 让水手选择一名存活玩家。标记那名玩家或水手醉酒。"],
  }),
  role({
    id: "mathematician",
    name: "数学家",
    officialName: "mathematician",
    team: "townsfolk",
    abilityText: "每个夜晚，你会得知有多少名玩家的能力因为其他角色的能力而未正常生效。(从上个黎明到你被唤醒时）",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/mathematician.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn: {number}."],
    highRiskNotes: ["First-night source reminder: 给他展示数字手势来告诉他在首个夜晚里有多少玩家的角色能力受他人影响而未正常生效。", "Other-night source reminder: 给他展示数字手势来告诉他从上个黎明到数学家醒来前有多少玩家的角色能力受他人影响而未正常生效。"],
  }),
  role({
    id: "highpriestess",
    name: "女祭司",
    officialName: "high_priestess",
    team: "townsfolk",
    abilityText: "每个夜晚，你会得知一名说书人认为你最应该与其交流的玩家。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/high_priestess.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You should talk to seat {seat}."],
    highRiskNotes: ["First-night source reminder: 唤醒女祭司，指向一名玩家。让女祭司重新入睡。", "Other-night source reminder: 唤醒女祭司，指向一名玩家。让女祭司重新入睡。"],
  }),
  role({
    id: "fortuneteller",
    name: "占卜师",
    officialName: "fortune_teller",
    team: "townsfolk",
    abilityText: "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/fortune_teller.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["Your answer is {yesNo}."],
    highRiskNotes: ["First-night source reminder: 让占卜师选择两名玩家。如果其中有恶魔或“干扰项”，点头示意，否则摇头。", "Other-night source reminder: 让占卜师选择两名玩家。如果其中有恶魔或“干扰项”，点头示意，否则摇头。"],
  }),
  role({
    id: "monk",
    name: "僧侣",
    officialName: "monk",
    team: "townsfolk",
    abilityText: "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/monk.png",
    inputKinds: ["none"],
    highRiskNotes: ["Other-night source reminder: 让僧侣选择除自己外的一名玩家。标记那名玩家被保护。"],
  }),
  role({
    id: "savant",
    name: "博学者",
    officialName: "savant",
    team: "townsfolk",
    abilityText: "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/savant.png",
    inputKinds: ["none"],
  }),
  role({
    id: "oracle",
    name: "神谕者",
    officialName: "oracle",
    team: "townsfolk",
    abilityText: "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/oracle.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn: {number}."],
    highRiskNotes: ["Other-night source reminder: 给他展示数字手势来告诉他当前已死亡的玩家中有多少玩家是邪恶的。"],
  }),
  role({
    id: "seamstress",
    name: "女裁缝",
    officialName: "seamstress",
    team: "townsfolk",
    abilityText: "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/seamstress.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["Your answer is {yesNo}."],
    highRiskNotes: ["First-night source reminder: 女裁缝可以选择除自己以外的两名玩家。如果她这么做了，对她点头或摇头示意这两名玩家是否为同一阵营，随后标记女裁缝失去能力。之后的夜晚无需再唤醒女裁缝。", "Other-night source reminder: 女裁缝可以选择除自己以外的两名玩家。如果她这么做了，对她点头或摇头示意这两名玩家是否为同一阵营，随后标记女裁缝失去能力。之后的夜晚无需再唤醒女裁缝。"],
  }),
  role({
    id: "engineer",
    name: "工程师",
    officialName: "engineer",
    team: "townsfolk",
    abilityText: "每局游戏限一次，在夜晚时，你可以选择让恶魔变成你选择的恶魔角色，或让所有爪牙变成你选择的爪牙角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/engineer.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May change Demon role or all Minions."],
    identityChanges: ["May change Demon or Minion characters."],
    highRiskNotes: ["Engineer may change Demon or all Minions; identity changes require confirmation.", "First-night source reminder: 工程师选择不使用能力，或在剧本列表中选择恶魔或爪牙角色。如果他选择爪牙角色，则需要选择对应数量的爪牙。然后将这些玩家依次唤醒，并告知他们变成了什么角色。", "Other-night source reminder: 工程师选择不使用能力，或在剧本列表中选择恶魔或爪牙角色。如果他选择爪牙角色，则需要选择对应数量的爪牙。然后将这些玩家依次唤醒，并告知他们变成了什么角色。"],
  }),
  role({
    id: "cannibal",
    name: "食人族",
    officialName: "cannibal",
    team: "townsfolk",
    abilityText: "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/cannibal.png",
    inputKinds: ["none"],
    highRiskNotes: ["Cannibal gains executed player ability and may be poisoned by evil execution; ability source remains manual."],
  }),
  role({
    id: "mutant",
    name: "畸形秀演员",
    officialName: "mutant",
    team: "outsider",
    abilityText: "如果你“疯狂”地证明自己是外来者，你可能被处决。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/mutant.png",
    inputKinds: ["none"],
    highRiskNotes: ["Mutant madness execution is storyteller discretion; do not auto-execute."],
  }),
  role({
    id: "barber",
    name: "理发师",
    officialName: "barber",
    team: "outsider",
    abilityText: "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/barber.png",
    inputKinds: ["none"],
    possibleOutcomes: ["Demon may swap two characters after Barber dies."],
    identityChanges: ["Demon may swap two characters after Barber dies."],
    highRiskNotes: ["Barber death may let Demon swap two characters; identity changes require confirmation.", "Other-night source reminder: 如果理发师今天死亡了，唤醒恶魔并展示“该角色的效果对你生效”信息标记和理发师角色标记。如果恶魔选择了两名玩家，将这两名玩家分别独自唤醒。对他们展示“你是”信息标记和他们的新角色标记。"],
  }),
  role({
    id: "drunk",
    name: "酒鬼",
    officialName: "drunk",
    team: "outsider",
    abilityText: "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/drunk.png",
    inputKinds: ["none"],
    setupImpact: ["Drunk is hidden and thinks they are a Townsfolk; assign and verify manually during setup."],
  }),
  role({
    id: "plaguedoctor",
    name: "瘟疫医生",
    officialName: "plague_doctor",
    team: "outsider",
    abilityText: "如果你死亡，说书人获得一个不在场的爪牙能力。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/1697467722_197011_3360.png",
    inputKinds: ["none"],
    highRiskNotes: ["Plague Doctor death gives storyteller a not-in-play Minion ability; choice remains manual."],
  }),
  role({
    id: "scarletwoman",
    name: "红唇女郎",
    officialName: "scarlet_woman",
    team: "minion",
    abilityText: "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/scarlet_woman.png",
    inputKinds: ["none"],
    identityChanges: ["May become the Demon if the Demon dies with five or more players alive."],
    highRiskNotes: ["Scarlet Woman may become the Demon under strict alive-count conditions; identity change requires confirmation.", "Other-night source reminder: 如果红唇女郎今天变成了小恶魔，对她展示“你是”信息标记，和小恶魔角色标记。"],
  }),
  role({
    id: "spy",
    name: "间谍",
    officialName: "spy",
    team: "minion",
    abilityText: "每个夜晚，你能查看魔典。你可能会被当作善良阵营、镇民角色或外来者角色，即使你已死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/spy.png",
    inputKinds: ["none"],
    highRiskNotes: ["Spy may register as good; grimoire viewing is a reminder only.", "First-night source reminder: 将魔典展示给间谍，他想看多久就看多久。", "Other-night source reminder: 将魔典展示给间谍，他想看多久就看多久。"],
  }),
  role({
    id: "psychopath",
    name: "精神病患者",
    officialName: "psychopath",
    team: "minion",
    abilityText: "每个白天，在提名开始前，你可以公开选择一名玩家：他死亡。如果你被处决，提名你的玩家需要和你猜拳，只有你输了你才会死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/psychopath.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May kill a chosen player publicly."],
    highRiskNotes: ["Psychopath public kill and roshambo survival are manual; do not auto-mark death."],
  }),
  role({
    id: "harpy",
    name: "鹰身女妖",
    officialName: "harpy",
    team: "minion",
    abilityText: "每个夜晚，你要选择两名玩家：明天第一名玩家需要“疯狂”地证明第二名玩家是邪恶的，否则他们可能会死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/202307/c_4331482099861_0db1bfaf.jpg",
    inputKinds: ["none"],
    highRiskNotes: ["Harpy madness and death threat are reminders; no automatic death.", "First-night source reminder: 唤醒鹰身女妖并让他依次指向两名玩家。标记第一名玩家“疯狂”，标记第二名玩家“第二名”。", "Other-night source reminder: 唤醒鹰身女妖并让他依次指向两名玩家。标记第一名玩家“疯狂”，标记第二名玩家“第二名”。"],
  }),
  role({
    id: "lleech",
    name: "痢蛭",
    officialName: "lleech",
    team: "demon",
    abilityText: "每个夜晚*，你要选择一名玩家：他死亡。在你的首个夜晚，你要选择一名存活的玩家：他中毒，只有他死亡时你才会一同死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/lleech.png",
    inputKinds: ["none"],
    possibleOutcomes: ["Chosen player may die; host death may kill Lleech."],
    stateChanges: ["Host is poisoned while Lleech lives."],
    highRiskNotes: ["Lleech host poison and Demon death dependency require manual host tracking.", "First-night source reminder: 寄生蛭指向一名玩家。放置寄生标记，那名玩家中毒。", "Other-night source reminder: 寄生蛭指向一名玩家。那名玩家死亡。"],
  }),
  role({
    id: "vigormortis",
    name: "亡骨魔",
    officialName: "vigormortis",
    team: "demon",
    abilityText: "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/vigormortis.png",
    inputKinds: ["none"],
    setupImpact: ["Vigormortis removes 1 Outsider and may keep killed Minion abilities; excluded from first templates here."],
    possibleOutcomes: ["Chosen player may die; killed Minion may keep ability."],
    stateChanges: ["One neighboring Townsfolk of a killed Minion may be poisoned after confirmation."],
    highRiskNotes: ["Vigormortis kill, Minion ability retention and neighbor poison are all manual confirmation drafts.", "Other-night source reminder: 让亡骨魔选择一名玩家。标记那名玩家死亡。如果该玩家是爪牙，标记该玩家保留能力，并标记与该玩家邻近的镇民玩家之一中毒。"],
  }),
  role({
    id: "fanggu",
    name: "方古",
    officialName: "fang_gu",
    team: "demon",
    abilityText: "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/fang_gu.png",
    inputKinds: ["none"],
    setupImpact: ["Fang Gu adds 1 Outsider and may jump to the first Outsider it kills; excluded from first templates here."],
    possibleOutcomes: ["Target may die; first Outsider killed by Fang Gu may become evil Fang Gu while old Fang Gu dies."],
    identityChanges: ["Outsider may become Fang Gu."],
    teamChanges: ["Jumped Outsider becomes evil."],
    highRiskNotes: ["Fang Gu jump happens once when Fang Gu kills an Outsider; old Demon death, new Demon identity and alignment require confirmation.", "Other-night source reminder: 让方古选择一名玩家。标记那名玩家死亡。如果他选择了外来者，且“首次”标记未放置在魔典中：用备用的方古角色标记替换那名外来者的角色标记。让方古重新入睡。唤醒方古的目标玩家。对该玩家展示“你是”信息标记和方古角色标记，并用拇指向下代表他阵营变为邪恶。将“首次”标记放置在魔典中。标记原本的方古玩家死亡，且他选择的玩家不会被标记为死亡。"],
  }),
  role({
    id: "vortox",
    name: "涡流",
    officialName: "vortox",
    team: "demon",
    abilityText: "每个夜晚*，你要选择一名玩家：他死亡。镇民玩家的能力都会产生错误信息。如果白天没⼈被处决，邪恶阵营获胜。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/vortox.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May create evil win candidate if nobody is executed."],
    highRiskNotes: ["Vortox false information and no-execution evil win remain storyteller-confirmed; never auto-declare victory.", "Other-night source reminder: 让涡流选择一名玩家。标记那名玩家死亡。"],
  }),
  role({
    id: "djinn",
    name: "灯神",
    officialName: "djinn",
    team: "fabled",
    abilityText: "使用灯神的相克规则。所有玩家都会知道其内容。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/web/icons/djinn.png",
    inputKinds: ["none"],
  })
] as const
