import type { SetupRule } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20941_46818.json"
const reviewedAt = '2026-07-21'

export const miaoShanFengXianSetupRules: readonly SetupRule[] = [
  {
    id: "miao-shan-feng-xian-drunk-reminder",
    roleId: "drunk",
    summary: "Drunk is hidden and thinks they are a Townsfolk; assign and verify manually during setup.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-vigormortis-reminder",
    roleId: "vigormortis",
    summary: "Vigormortis kill, Minion ability retention and neighbor poison are all manual confirmation drafts.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-fanggu-reminder",
    roleId: "fanggu",
    summary: "Fang Gu jump happens once when Fang Gu kills an Outsider; old Demon death, new Demon identity and alignment require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-pixie-reminder",
    roleId: "pixie",
    summary: "Pixie madness and later ability gain are manual reminders; do not auto-grant ability.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-sailor-reminder",
    roleId: "sailor",
    summary: "Sailor drunkenness and death prevention require storyteller confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-engineer-reminder",
    roleId: "engineer",
    summary: "Engineer may change Demon or all Minions; identity changes require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-cannibal-reminder",
    roleId: "cannibal",
    summary: "Cannibal gains executed player ability and may be poisoned by evil execution; ability source remains manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-mutant-reminder",
    roleId: "mutant",
    summary: "Mutant madness execution is storyteller discretion; do not auto-execute.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-barber-reminder",
    roleId: "barber",
    summary: "Barber death may let Demon swap two characters; identity changes require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-plaguedoctor-reminder",
    roleId: "plaguedoctor",
    summary: "Plague Doctor death gives storyteller a not-in-play Minion ability; choice remains manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-scarletwoman-reminder",
    roleId: "scarletwoman",
    summary: "Scarlet Woman may become the Demon under strict alive-count conditions; identity change requires confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-spy-reminder",
    roleId: "spy",
    summary: "Spy may register as good; grimoire viewing is a reminder only.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-psychopath-reminder",
    roleId: "psychopath",
    summary: "Psychopath public kill and roshambo survival are manual; do not auto-mark death.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-harpy-reminder",
    roleId: "harpy",
    summary: "Harpy madness and death threat are reminders; no automatic death.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-lleech-reminder",
    roleId: "lleech",
    summary: "Lleech host poison and Demon death dependency require manual host tracking.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "miao-shan-feng-xian-vortox-reminder",
    roleId: "vortox",
    summary: "Vortox false information and no-execution evil win remain storyteller-confirmed; never auto-declare victory.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
]
