import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "huo-shan-jiao-tuan"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const huoShanJiaoTuanSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["knight", "steward", "empath", "seamstress", "pacifist", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["king", "snakecharmer", "towncrier", "farmer", "cannibal", "cerenovus", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["knight", "snakecharmer", "oracle", "farmer", "cannibal", "goblin", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["knight", "steward", "empath", "oracle", "seamstress", "butler", "devilsadvocate", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["king", "snakecharmer", "towncrier", "pacifist", "cannibal", "mutant", "cerenovus", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["knight", "steward", "empath", "oracle", "seamstress", "butler", "saint", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["king", "snakecharmer", "towncrier", "pacifist", "farmer", "mutant", "butler", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["knight", "steward", "empath", "oracle", "towncrier", "seamstress", "pacifist", "devilsadvocate", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "towncrier", "seamstress", "farmer", "cannibal", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["knight", "snakecharmer", "empath", "oracle", "pacifist", "farmer", "cannibal", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["knight", "steward", "empath", "oracle", "towncrier", "seamstress", "pacifist", "butler", "devilsadvocate", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "towncrier", "seamstress", "farmer", "cannibal", "mutant", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "pressure", "count": 11, "style": "chaos", "roles": ["knight", "snakecharmer", "empath", "oracle", "pacifist", "farmer", "cannibal", "saint", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["knight", "steward", "empath", "oracle", "towncrier", "seamstress", "pacifist", "butler", "mutant", "devilsadvocate", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "towncrier", "seamstress", "farmer", "cannibal", "mutant", "saint", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["knight", "snakecharmer", "oracle", "towncrier", "pacifist", "farmer", "cannibal", "butler", "saint", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["knight", "steward", "king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "devilsadvocate", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "farmer", "cannibal", "devilsadvocate", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["knight", "steward", "king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "butler", "devilsadvocate", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "farmer", "cannibal", "mutant", "devilsadvocate", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["knight", "steward", "king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "butler", "mutant", "devilsadvocate", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["king", "snakecharmer", "empath", "oracle", "towncrier", "seamstress", "pacifist", "farmer", "cannibal", "mutant", "saint", "devilsadvocate", "cerenovus", "goblin", "lleech"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["knight", "snakecharmer", "empath", "oracle", "towncrier", "pacifist", "farmer", "cannibal", "seamstress", "butler", "saint", "devilsadvocate", "cerenovus", "poisoner", "vortox"], "bluffs": ["balloonist", "choirboy", "drunk"], "note": "已核对常规配板。气球驾驶员、唱诗男孩、酒鬼、方古、军团的配板与隐藏、特殊路径仍需人工处理；舞蛇人、涡流、痢蛭、洗脑师、魔鬼代言人、投毒者、哥布林、和平主义者、农夫、食人族的结果由说书人确认。"}),
]
