import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21286_26817.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-21'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: "十三行", setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const shiSanHangRoles = [
  role({"id": "grandmother", "name": "祖母", "officialName": "Grandmother", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名善良玩家和他的角色。如果恶魔杀死了他，你也会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/grandmother.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 祖母. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "sailor", "name": "水手", "officialName": "Sailor", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：你或他之一会醉酒直到下个黄昏。你不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sailor.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply drunk state or make an ability fail.", "May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 水手. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May apply or remove poisoned state.", "May cause, prevent, delay, or disguise death."], "teamChanges": ["May affect alignment or win/loss judgment."], "playerMessageTemplates": ["You are 食人族. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "Chambermaid", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players", "number"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "playerMessageTemplates": ["You are 侍女. Wait for the Storyteller to provide the current information."]}),
  role({"id": "yinluren", "name": "引路人", "officialName": "Yinluren", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知今晚是否有邪恶玩家的能力选择或影响了他们之中的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_2147287694761_01761fcb.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "playerMessageTemplates": ["You are 引路人. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "preacher", "name": "传教士", "officialName": "Preacher", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名玩家：如果选中了爪牙，他会得知被传教士选中。所有被你选中的爪牙失去能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/preacher.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May make an ability fail or become lost."], "playerMessageTemplates": ["You are 传教士. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "daoshi", "name": "道士", "officialName": "Daoshi", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家：如果你选中了恶魔，你死亡，然后他醉酒直到下个黎明。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_0866187694761_98fba0d5.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death.", "选中恶魔时：道士死亡，然后该恶魔醉酒直到下个黎明；如果道士的死亡被阻止，恶魔当晚不会醉酒。"], "playerMessageTemplates": ["You are 道士. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "simin", "name": "司民", "officialName": "Simin", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天是否有非镇民玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_0691847760171_5ab4159c.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 司民. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "gossip", "name": "造谣者", "officialName": "Gossip", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 造谣者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "teamChanges": ["May affect alignment or win/loss judgment."], "playerMessageTemplates": ["You are 渔夫. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "yishi", "name": "驿使", "officialName": "Yishi", "team": "townsfolk", "abilityText": "每个白天，你可以公开声明一个角色在场。在当晚，你会得知该声明是否正确。如果你得知过是和否，你失去此能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_9168557760171_8ae6a36c.jpg", "inputKinds": ["role", "text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May make an ability fail or become lost.", "驿使需要先后得知过“是”和“否”两种结果才失去能力（即使在醉酒或中毒时得知的结果也计入）；只得知过其中一种时仍每晚正常唤醒并给出信息。"], "playerMessageTemplates": ["You are 驿使. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "banxian", "name": "半仙", "officialName": "Banxian", "team": "townsfolk", "abilityText": "任何在夜晚使用自身能力选择你的其他玩家，会改为选中另一名邪恶玩家作为替代。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_3833755308961_7e6f7e09.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "playerMessageTemplates": ["You are 半仙. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "heshang", "name": "和尚", "officialName": "Heshang", "team": "townsfolk", "abilityText": "每个夜晚，当有邪恶玩家的能力首次选择或影响与你邻近的存活玩家时，改为此次能力不生效并持续至下个黎明，且你会得知你的能力被触发。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4432977694761_315f1863.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May make an ability fail or become lost."], "playerMessageTemplates": ["You are 和尚. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "acrobat", "name": "杂技演员", "officialName": "Acrobat", "team": "outsider", "abilityText": "每个夜晚*，你要选择一名玩家：如果当晚他醉酒或中毒，你死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/acrobat.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["Acrobat death (self only); the ability does not apply drunk/poison or affect other players' deaths."], "playerMessageTemplates": ["You are 杂技演员. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "goon", "name": "莽夫", "officialName": "Goon", "team": "outsider", "abilityText": "每个夜晚，首个使用其自身能力选择了你的玩家会醉酒直到下个黄昏。你会转变为他的阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/goon.png", "inputKinds": ["player"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May apply drunk state or make an ability fail."], "identityChanges": ["May involve character, registration, or special alive/dead state changes."], "teamChanges": ["May affect alignment or win/loss judgment."], "playerMessageTemplates": ["You are 莽夫. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "tinker", "name": "修补匠", "officialName": "Tinker", "team": "outsider", "abilityText": "你随时可能死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/tinker.png", "inputKinds": ["none"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 修补匠. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "damsel", "name": "落难少女", "officialName": "Damsel", "team": "outsider", "abilityText": "所有爪牙都知道落难少女在场。每局游戏限一次，任意爪牙可以公开猜测你是落难少女，如果猜对，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/damsel.png", "inputKinds": ["text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "teamChanges": ["May affect alignment or win/loss judgment."], "playerMessageTemplates": ["You are 落难少女. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "devilsadvocate", "name": "魔鬼代言人", "officialName": "Devil's Advocate", "team": "minion", "abilityText": "每个夜晚，你要选择一名存活的玩家（与上个夜晚不同）：如果明天白天他被处决，他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/devils_advocate.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 魔鬼代言人. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "huapi", "name": "画皮", "officialName": "Huapi", "team": "minion", "abilityText": "在你的首个夜晚，你要选择一名存活玩家：他死亡但会被当作存活。当他下一次即将死亡时，他重生，随后你重获能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_8796728760171_7caa0950.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death.", "画皮是阻止该玩家的下一次死亡并将其复活（不宣布死亡、不触发死亡触发能力），而非死亡发生后再复活；如果画皮无法阻止这次死亡，则无法复活该玩家，也不会重获能力。"], "playerMessageTemplates": ["You are 画皮. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "poisoner", "name": "投毒者", "officialName": "Poisoner", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：他在当晚和明天白天中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/poisoner.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply or remove poisoned state."], "playerMessageTemplates": ["You are 投毒者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["player"], "setupImpact": ["教父 has setup or composition impact; Storyteller confirms before play."], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 教父. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "pukka", "name": "普卡", "officialName": "Pukka", "team": "demon", "abilityText": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pukka.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply or remove poisoned state.", "May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 普卡. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "identityChanges": ["May involve character, registration, or special alive/dead state changes."], "playerMessageTemplates": ["You are 小恶魔. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "taotie", "name": "饕餮", "officialName": "Taotie", "team": "demon", "abilityText": "每个夜晚*，你要选择任意数量的非旅行者玩家或一名旅行者玩家：如果他们的角色类型均不相同，他们死亡。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_5897997694761_fbe1f00c.jpg", "inputKinds": ["players"], "setupImpact": ["饕餮 has setup or composition impact; Storyteller confirms before play."], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 饕餮. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
  role({"id": "dianyuzhang", "name": "典狱长", "officialName": "Dianyuzhang", "team": "demon", "abilityText": "每个夜晚，你要选择至多三名玩家：如果明天白天他们之一死于处决，被你上次选择的其他玩家会在当晚死亡。否则，当晚他们之中会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_5570117816071_2f5793fd.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 典狱长. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "Custom role from this script source; recheck against the source text before hosting."]}),
] as const satisfies readonly SmartRoleDefinition[]
