import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "shi-san-hang"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate { return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true } }

export const shiSanHangSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["simin", "gossip", "fisherman", "yishi", "banxian", "huapi", "imp"], bluffs: ["heshang", "grandmother", "sailor"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["fisherman", "yishi", "banxian", "heshang", "grandmother", "poisoner", "dianyuzhang"], bluffs: ["sailor", "cannibal", "chambermaid"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["banxian", "heshang", "grandmother", "sailor", "cannibal", "devilsadvocate", "pukka"], bluffs: ["chambermaid", "yinluren", "preacher"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["gossip", "fisherman", "yishi", "banxian", "heshang", "acrobat", "poisoner", "dianyuzhang"], bluffs: ["grandmother", "sailor", "cannibal"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["yishi", "banxian", "heshang", "grandmother", "sailor", "goon", "devilsadvocate", "pukka"], bluffs: ["cannibal", "chambermaid", "yinluren"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["fisherman", "yishi", "banxian", "heshang", "grandmother", "goon", "tinker", "devilsadvocate", "pukka"], bluffs: ["sailor", "cannibal", "chambermaid"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["banxian", "heshang", "grandmother", "sailor", "cannibal", "tinker", "damsel", "huapi", "imp"], bluffs: ["chambermaid", "yinluren", "preacher"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["yishi", "banxian", "heshang", "grandmother", "sailor", "cannibal", "chambermaid", "huapi", "poisoner", "imp"], bluffs: ["yinluren", "preacher", "daoshi"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["heshang", "grandmother", "sailor", "cannibal", "chambermaid", "yinluren", "preacher", "poisoner", "devilsadvocate", "dianyuzhang"], bluffs: ["daoshi", "simin", "gossip"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["sailor", "cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "devilsadvocate", "huapi", "pukka"], bluffs: ["gossip", "fisherman", "yishi"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["banxian", "heshang", "grandmother", "sailor", "cannibal", "chambermaid", "yinluren", "damsel", "poisoner", "devilsadvocate", "dianyuzhang"], bluffs: ["preacher", "daoshi", "simin"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["grandmother", "sailor", "cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "acrobat", "devilsadvocate", "huapi", "pukka"], bluffs: ["simin", "gossip", "fisherman"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["heshang", "grandmother", "sailor", "cannibal", "chambermaid", "yinluren", "preacher", "acrobat", "goon", "devilsadvocate", "huapi", "pukka"], bluffs: ["daoshi", "simin", "gossip"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["sailor", "cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "goon", "tinker", "huapi", "poisoner", "imp"], bluffs: ["gossip", "fisherman", "yishi"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "tinker", "damsel", "poisoner", "devilsadvocate", "dianyuzhang"], bluffs: ["yishi", "banxian", "heshang"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["grandmother", "sailor", "cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "huapi", "poisoner", "devilsadvocate", "imp"], bluffs: ["fisherman", "yishi", "banxian"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "yishi", "poisoner", "devilsadvocate", "huapi", "dianyuzhang"], bluffs: ["banxian", "heshang", "grandmother"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["sailor", "cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "tinker", "poisoner", "devilsadvocate", "huapi", "dianyuzhang"], bluffs: ["yishi", "banxian", "heshang"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "yishi", "banxian", "damsel", "devilsadvocate", "huapi", "poisoner", "pukka"], bluffs: ["heshang", "grandmother", "sailor"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["cannibal", "chambermaid", "yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "yishi", "damsel", "acrobat", "devilsadvocate", "huapi", "poisoner", "pukka"], bluffs: ["banxian", "heshang", "grandmother"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["yinluren", "preacher", "daoshi", "simin", "gossip", "fisherman", "yishi", "banxian", "heshang", "acrobat", "goon", "huapi", "poisoner", "devilsadvocate", "imp"], bluffs: ["grandmother", "sailor", "cannibal"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["daoshi", "simin", "gossip", "fisherman", "yishi", "banxian", "heshang", "grandmother", "sailor", "goon", "tinker", "poisoner", "devilsadvocate", "huapi", "dianyuzhang"], bluffs: ["cannibal", "chambermaid", "yinluren"], note: "Verified setup. Godfather/Taotie setup-changing paths stay out of first templates; custom role outcomes remain manual reminders." }),
]
