import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "zhi-shou-zhe-tian"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const zhiShouZheTianSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "devilsadvocate", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "vizier", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["gossip", "flowergirl", "general", "sailor", "innkeeper", "boomdandy", "nodashii"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "lunatic", "devilsadvocate", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "damsel", "vizier", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "lunatic", "moonchild", "devilsadvocate", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "damsel", "klutz", "vizier", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "devilsadvocate", "vizier", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "vizier", "devilsadvocate", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["gossip", "flowergirl", "general", "sailor", "innkeeper", "gambler", "tealady", "boomdandy", "devilsadvocate", "nodashii"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "lunatic", "devilsadvocate", "vizier", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "damsel", "vizier", "devilsadvocate", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "lunatic", "moonchild", "devilsadvocate", "vizier", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "damsel", "klutz", "vizier", "devilsadvocate", "lleech"], "bluffs": ["godfather", "pacifist", "tealady"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["gossip", "flowergirl", "general", "sailor", "innkeeper", "gambler", "tealady", "moonchild", "damsel", "boomdandy", "devilsadvocate", "nodashii"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "knight", "tealady", "devilsadvocate", "vizier", "boomdandy", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "pacifist", "general", "vizier", "devilsadvocate", "boomdandy", "lleech"], "bluffs": ["godfather", "tealady", "knight"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "knight", "tealady", "lunatic", "devilsadvocate", "vizier", "boomdandy", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "pacifist", "general", "damsel", "vizier", "devilsadvocate", "boomdandy", "lleech"], "bluffs": ["godfather", "tealady", "knight"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["sailor", "innkeeper", "gambler", "philosopher", "gossip", "flowergirl", "general", "knight", "tealady", "lunatic", "moonchild", "devilsadvocate", "vizier", "boomdandy", "pukka"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["philosopher", "gambler", "innkeeper", "sailor", "farmer", "cannibal", "fool", "pacifist", "general", "damsel", "klutz", "vizier", "devilsadvocate", "boomdandy", "lleech"], "bluffs": ["godfather", "tealady", "knight"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["gossip", "flowergirl", "general", "sailor", "innkeeper", "gambler", "tealady", "knight", "fool", "moonchild", "damsel", "boomdandy", "devilsadvocate", "vizier", "nodashii"], "bluffs": ["godfather", "farmer", "pacifist"], "note": "Verified normal setup; Godfather setup-changing path stays manual. Vizier, Boomdandy, No Dashii, Al-Hadikhia, Lleech, Pukka, Damsel, Klutz, Moonchild, Farmer, Philosopher, Gambler, Innkeeper, Gossip and Sailor outcomes remain ST-confirmed."}),
]
