import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "zui-ge-luan-wu"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const zuiGeLuanWuSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "poisoner", "nodashii"], "bluffs": ["bountyhunter", "pixie", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["pixie", "innkeeper", "savant", "amnesiac", "philosopher", "cerenovus", "nodashii"], "bluffs": ["noble", "clockmaker", "bountyhunter"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["clockmaker", "dreamer", "mathematician", "savant", "minstrel", "poisoner", "nodashii"], "bluffs": ["noble", "bountyhunter", "pixie"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "goon", "poisoner", "nodashii"], "bluffs": ["bountyhunter", "pixie", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["pixie", "innkeeper", "savant", "amnesiac", "philosopher", "mutant", "cerenovus", "nodashii"], "bluffs": ["noble", "clockmaker", "bountyhunter"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "goon", "mutant", "poisoner", "nodashii"], "bluffs": ["bountyhunter", "pixie", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["pixie", "innkeeper", "savant", "amnesiac", "philosopher", "damsel", "sweetheart", "cerenovus", "nodashii"], "bluffs": ["noble", "clockmaker", "bountyhunter"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "poisoner", "cerenovus", "nodashii"], "bluffs": ["bountyhunter", "pixie", "amnesiac"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["pixie", "amnesiac", "philosopher", "minstrel", "chambermaid", "dreamer", "clockmaker", "poisoner", "pithag", "nodashii"], "bluffs": ["noble", "bountyhunter", "mathematician"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["noble", "innkeeper", "savant", "amnesiac", "philosopher", "minstrel", "mathematician", "poisoner", "cerenovus", "nodashii"], "bluffs": ["clockmaker", "bountyhunter", "pixie"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "goon", "poisoner", "cerenovus", "nodashii"], "bluffs": ["bountyhunter", "pixie", "amnesiac"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["pixie", "amnesiac", "philosopher", "minstrel", "chambermaid", "dreamer", "clockmaker", "mutant", "poisoner", "pithag", "nodashii"], "bluffs": ["noble", "bountyhunter", "mathematician"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "goon", "mutant", "poisoner", "cerenovus", "nodashii"], "bluffs": ["bountyhunter", "pixie", "amnesiac"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["pixie", "amnesiac", "philosopher", "minstrel", "chambermaid", "dreamer", "clockmaker", "damsel", "sweetheart", "poisoner", "pithag", "nodashii"], "bluffs": ["noble", "bountyhunter", "mathematician"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["noble", "innkeeper", "savant", "amnesiac", "philosopher", "minstrel", "mathematician", "goon", "mutant", "poisoner", "cerenovus", "nodashii"], "bluffs": ["clockmaker", "bountyhunter", "pixie"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "amnesiac", "philosopher", "poisoner", "cerenovus", "pithag", "nodashii"], "bluffs": ["bountyhunter", "pixie", "huntsman"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["pixie", "chambermaid", "dreamer", "mathematician", "savant", "amnesiac", "philosopher", "minstrel", "clockmaker", "cerenovus", "pithag", "poisoner", "nodashii"], "bluffs": ["noble", "bountyhunter", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "amnesiac", "philosopher", "goon", "poisoner", "cerenovus", "pithag", "nodashii"], "bluffs": ["bountyhunter", "pixie", "huntsman"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["pixie", "chambermaid", "dreamer", "mathematician", "savant", "amnesiac", "philosopher", "minstrel", "clockmaker", "mutant", "cerenovus", "pithag", "poisoner", "nodashii"], "bluffs": ["noble", "bountyhunter", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "amnesiac", "philosopher", "goon", "mutant", "poisoner", "cerenovus", "pithag", "nodashii"], "bluffs": ["bountyhunter", "pixie", "huntsman"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["pixie", "chambermaid", "dreamer", "mathematician", "savant", "amnesiac", "philosopher", "minstrel", "clockmaker", "damsel", "sweetheart", "cerenovus", "pithag", "poisoner", "nodashii"], "bluffs": ["noble", "bountyhunter", "innkeeper"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["noble", "clockmaker", "chambermaid", "dreamer", "mathematician", "innkeeper", "savant", "amnesiac", "philosopher", "goon", "mutant", "poisoner", "cerenovus", "pithag", "nodashii"], "bluffs": ["bountyhunter", "pixie", "huntsman"], "note": "已核对常规配板。赏金猎人、巡山人、酒鬼、教父、亡骨魔、方古的配板或隐藏路径仍需人工处理；哲学家、洗脑师、麻脸巫婆、诺-达鲺、莽夫、吟游诗人、落难少女的结果由说书人确认。"}),
]
