import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = 'uncertain-death'

const godfatherPlusOutsiderAdjustment = {
  ruleId: 'godfather-outsider-adjustment',
  choiceId: 'add-one-outsider',
  compositionDelta: { townsfolk: -1, outsider: 1 },
  note: '教父：+1 外来者，通常替换 1 名镇民。',
} as const

const godfatherMinusOutsiderAdjustment = {
  ruleId: 'godfather-outsider-adjustment',
  choiceId: 'remove-one-outsider',
  compositionDelta: { townsfolk: 1, outsider: -1 },
  note: '教父：-1 外来者，通常增加 1 名镇民。',
} as const

type GodfatherAdjustment = 'plus' | 'minus'

type TemplateInput = {
  id: string
  count: PlayerCount
  style: SetupTemplateStyle
  roles: readonly RoleId[]
  bluffs: readonly RoleId[]
  note: string
  godfather?: GodfatherAdjustment
}

function template(input: TemplateInput): SetupTemplate {
  return {
    templateId: `uncertain-death-${input.count}-${input.id}`,
    scriptId,
    playerCount: input.count,
    style: input.style,
    roles: input.roles,
    bluffs: input.bluffs,
    setupAdjustments: input.godfather
      ? [input.godfather === 'plus' ? godfatherPlusOutsiderAdjustment : godfatherMinusOutsiderAdjustment]
      : undefined,
    notes: [input.note],
    verified: true,
  }
}

export const uncertainDeathSetupTemplates: readonly SetupTemplate[] = [
  template({
    id: 'clear-start',
    count: 7,
    style: 'beginner',
    roles: ['clockmaker', 'librarian', 'empath', 'monk', 'slayer', 'scarletwoman', 'nodashii'],
    bluffs: ['grandmother', 'fortuneteller', 'oracle'],
    note: '七人清晰局，保留毒与恶魔传递提醒。',
  }),
  template({
    id: 'hidden-evil',
    count: 7,
    style: 'balanced',
    roles: ['grandmother', 'fortuneteller', 'undertaker', 'artist', 'seamstress', 'marionette', 'pukka'],
    bluffs: ['clockmaker', 'empath', 'exorcist'],
    note: '提线木偶加普卡，适合练隐藏身份与延迟死亡记录。',
  }),
  template({
    id: 'godfather-lunatic',
    count: 7,
    style: 'chaos',
    roles: ['clockmaker', 'empath', 'exorcist', 'slayer', 'lunatic', 'godfather', 'pukka'],
    bluffs: ['librarian', 'grandmother', 'oracle'],
    note: '教父加一外来者，疯子信息必须由说书人手动设计。',
    godfather: 'plus',
  }),
  template({
    id: 'standard-eight',
    count: 8,
    style: 'beginner',
    roles: ['librarian', 'empath', 'flowergirl', 'undertaker', 'monk', 'recluse', 'assassin', 'nodashii'],
    bluffs: ['clockmaker', 'artist', 'seamstress'],
    note: '八人标准局，陌客误导与刺客额外死亡只做提醒。',
  }),
  template({
    id: 'godfather-minus',
    count: 8,
    style: 'balanced',
    roles: ['clockmaker', 'grandmother', 'fortuneteller', 'oracle', 'artist', 'seamstress', 'godfather', 'pukka'],
    bluffs: ['librarian', 'empath', 'monk'],
    note: '教父减少外来者，信息角色多，适合标准玩家。',
    godfather: 'minus',
  }),
  template({
    id: 'standard-nine',
    count: 9,
    style: 'balanced',
    roles: ['clockmaker', 'librarian', 'empath', 'undertaker', 'slayer', 'lunatic', 'mutant', 'scarletwoman', 'nodashii'],
    bluffs: ['grandmother', 'fortuneteller', 'oracle'],
    note: '疯子与畸形秀演员同场，信息真假和发言压力都有。',
  }),
  template({
    id: 'godfather-outsider-fog',
    count: 9,
    style: 'chaos',
    roles: ['grandmother', 'fortuneteller', 'oracle', 'monk', 'lunatic', 'recluse', 'sweetheart', 'godfather', 'pukka'],
    bluffs: ['clockmaker', 'empath', 'undertaker'],
    note: '三外来者教父局，心上人死亡后的醉酒只由说书人确认。',
    godfather: 'plus',
  }),
  template({
    id: 'no-outsider-ten',
    count: 10,
    style: 'beginner',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'flowergirl',
      'artist',
      'monk',
      'assassin',
      'scarletwoman',
      'nodashii',
    ],
    bluffs: ['fortuneteller', 'undertaker', 'seamstress'],
    note: '十人无外来者局，便于先练夜间顺序和死亡记录。',
  }),
  template({
    id: 'godfather-lunatic-ten',
    count: 10,
    style: 'chaos',
    roles: [
      'clockmaker',
      'fortuneteller',
      'exorcist',
      'oracle',
      'undertaker',
      'seamstress',
      'lunatic',
      'godfather',
      'marionette',
      'pukka',
    ],
    bluffs: ['librarian', 'empath', 'monk'],
    note: '疯子、教父、提线木偶同场，开局信息必须逐项核对。',
    godfather: 'plus',
  }),
  template({
    id: 'pukka-control',
    count: 10,
    style: 'long-game',
    roles: [
      'grandmother',
      'librarian',
      'empath',
      'flowergirl',
      'oracle',
      'slayer',
      'monk',
      'assassin',
      'marionette',
      'pukka',
    ],
    bluffs: ['clockmaker', 'fortuneteller', 'undertaker'],
    note: '普卡局适合练延迟死亡，但工具不自动处理死亡链。',
  }),
  template({
    id: 'balanced-eleven',
    count: 11,
    style: 'balanced',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'fortuneteller',
      'undertaker',
      'monk',
      'recluse',
      'assassin',
      'scarletwoman',
      'nodashii',
    ],
    bluffs: ['flowergirl', 'oracle', 'artist'],
    note: '十一人均衡局，陌客和诺达鲺相邻中毒都只做提醒。',
  }),
  template({
    id: 'godfather-minus-eleven',
    count: 11,
    style: 'balanced',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'flowergirl',
      'oracle',
      'artist',
      'seamstress',
      'godfather',
      'marionette',
      'pukka',
    ],
    bluffs: ['fortuneteller', 'undertaker', 'monk'],
    note: '教父减少外来者，提线木偶身份交接要单独核对。',
    godfather: 'minus',
  }),
  template({
    id: 'balanced-twelve',
    count: 12,
    style: 'balanced',
    roles: [
      'clockmaker',
      'librarian',
      'empath',
      'fortuneteller',
      'flowergirl',
      'undertaker',
      'monk',
      'lunatic',
      'recluse',
      'assassin',
      'scarletwoman',
      'nodashii',
    ],
    bluffs: ['grandmother', 'oracle', 'seamstress'],
    note: '十二人标准局，疯子和陌客提供误导但仍可控。',
  }),
  template({
    id: 'godfather-plus-twelve',
    count: 12,
    style: 'chaos',
    roles: [
      'grandmother',
      'librarian',
      'exorcist',
      'oracle',
      'artist',
      'seamstress',
      'lunatic',
      'mutant',
      'sweetheart',
      'godfather',
      'marionette',
      'pukka',
    ],
    bluffs: ['clockmaker', 'empath', 'fortuneteller'],
    note: '三外来者十二人局，疯狂、醉酒和假恶魔信息要分开记录。',
    godfather: 'plus',
  }),
  template({
    id: 'godfather-minus-twelve',
    count: 12,
    style: 'long-game',
    roles: [
      'clockmaker',
      'grandmother',
      'empath',
      'fortuneteller',
      'flowergirl',
      'undertaker',
      'slayer',
      'monk',
      'recluse',
      'godfather',
      'scarletwoman',
      'nodashii',
    ],
    bluffs: ['librarian', 'oracle', 'artist'],
    note: '教父减少外来者，红唇女郎传递只在条件满足时提醒。',
    godfather: 'minus',
  }),
  template({
    id: 'standard-thirteen',
    count: 13,
    style: 'balanced',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'fortuneteller',
      'exorcist',
      'undertaker',
      'artist',
      'monk',
      'assassin',
      'scarletwoman',
      'marionette',
      'pukka',
    ],
    bluffs: ['flowergirl', 'oracle', 'seamstress'],
    note: '十三人无外来者，隐藏邪恶和普卡链路是主要压力点。',
  }),
  template({
    id: 'godfather-plus-thirteen',
    count: 13,
    style: 'chaos',
    roles: [
      'clockmaker',
      'librarian',
      'empath',
      'flowergirl',
      'oracle',
      'undertaker',
      'slayer',
      'seamstress',
      'lunatic',
      'godfather',
      'assassin',
      'scarletwoman',
      'nodashii',
    ],
    bluffs: ['grandmother', 'fortuneteller', 'monk'],
    note: '十三人教父加外来者，疯子信息与恶魔信息要分开。',
    godfather: 'plus',
  }),
  template({
    id: 'standard-fourteen',
    count: 14,
    style: 'balanced',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'fortuneteller',
      'flowergirl',
      'oracle',
      'undertaker',
      'monk',
      'mutant',
      'assassin',
      'scarletwoman',
      'marionette',
      'nodashii',
    ],
    bluffs: ['exorcist', 'artist', 'seamstress'],
    note: '十四人标准局，疯狂和隐藏邪恶制造讨论张力。',
  }),
  template({
    id: 'godfather-plus-fourteen',
    count: 14,
    style: 'long-game',
    roles: [
      'clockmaker',
      'librarian',
      'empath',
      'exorcist',
      'flowergirl',
      'artist',
      'slayer',
      'seamstress',
      'lunatic',
      'recluse',
      'godfather',
      'assassin',
      'marionette',
      'pukka',
    ],
    bluffs: ['grandmother', 'fortuneteller', 'undertaker'],
    note: '教父加外来者，陌客误导和普卡链路都只做人工核对。',
    godfather: 'plus',
  }),
  template({
    id: 'balanced-fifteen',
    count: 15,
    style: 'balanced',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'fortuneteller',
      'flowergirl',
      'oracle',
      'undertaker',
      'monk',
      'lunatic',
      'recluse',
      'assassin',
      'scarletwoman',
      'marionette',
      'nodashii',
    ],
    bluffs: ['exorcist', 'artist', 'seamstress'],
    note: '十五人均衡局，信息足够多，适合完整长局。',
  }),
  template({
    id: 'godfather-plus-fifteen',
    count: 15,
    style: 'chaos',
    roles: [
      'clockmaker',
      'librarian',
      'empath',
      'exorcist',
      'flowergirl',
      'undertaker',
      'artist',
      'seamstress',
      'lunatic',
      'mutant',
      'sweetheart',
      'godfather',
      'assassin',
      'scarletwoman',
      'pukka',
    ],
    bluffs: ['grandmother', 'fortuneteller', 'oracle'],
    note: '三外来者十五人局，心上人死亡后醉酒必须手动确认。',
    godfather: 'plus',
  }),
  template({
    id: 'godfather-minus-fifteen',
    count: 15,
    style: 'long-game',
    roles: [
      'clockmaker',
      'grandmother',
      'librarian',
      'empath',
      'fortuneteller',
      'exorcist',
      'flowergirl',
      'oracle',
      'undertaker',
      'monk',
      'recluse',
      'godfather',
      'scarletwoman',
      'marionette',
      'nodashii',
    ],
    bluffs: ['artist', 'slayer', 'seamstress'],
    note: '教父减少外来者，隐藏邪恶多，适合老玩家长局。',
    godfather: 'minus',
  }),
]
