import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21365_21069.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Ku Mu Feng Chun', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const kuMuFengChunRoles = [
  role({"id": "shugenja", "name": "修行者", "officialName": "Shugenja", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知距离最近的邪恶玩家位于你的顺时针还是逆时针方向。如果两侧的邪恶玩家与你距离相等，你得知的信息由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9833664308961_ad73c43b.jpg", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Learns nearest evil direction; equidistant result is storyteller choice."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not infer direction automatically; use seating and ST judgment."]}),
  role({"id": "monk", "name": "僧侣", "officialName": "Monk", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "nightwatchman", "name": "守夜人", "officialName": "Nightwatchman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名玩家：他会得知你是守夜人。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/nightwatchman.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "banshee", "name": "报丧女妖", "officialName": "Banshee", "team": "townsfolk", "abilityText": "如果恶魔杀死了你，所有玩家都会得知此事。从现在开始，你每天可以发起两次提名，每次投票时可以投两票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1714210634_197011_2148.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If killed by the Demon, public Banshee state begins."], "stateChanges": ["Can gain extra nominations and votes after the trigger."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only confirmed Demon kill triggers Banshee; do not change vote rights automatically."]}),
  role({"id": "snakecharmer", "name": "舞蛇人", "officialName": "Snake Charmer", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：如果你选中了恶魔，你和他交换角色和阵营，然后他中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/snake_charmer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["New Snake Charmer poison is manual and the new character ability is normally used from the next night."], "identityChanges": ["If target is Demon, Snake Charmer and Demon swap character."], "teamChanges": ["Swap also swaps alignment; the new Snake Charmer is poisoned."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-swap identity, alignment, poison or wake order."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns count of dead evil players."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Recluse registration and misinformation remain storyteller-confirmed."]}),
  role({"id": "towncrier", "name": "城镇公告员", "officialName": "Town Crier", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知在今天白天时是否有爪牙发起过提名。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/town_crier.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Learns whether a Minion nominated today."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not infer from incomplete vote logs without ST review."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Returns a yes/no Demon ping across two chosen players and the red herring."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Red herring and poison/drunk effects are storyteller-confirmed."]}),
  role({"id": "juggler", "name": "杂耍艺人", "officialName": "Juggler", "team": "townsfolk", "abilityText": "在你的首个白天，你可以公开猜测任意玩家的角色最多五次。在当晚，你会得知猜测正确的角色数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/juggler.png", "inputKinds": ["players", "role"], "setupImpact": [], "possibleOutcomes": ["Learns number of correct public role guesses from first day."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only first-day public juggle guesses count."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["If chosen role is in play, that role becomes drunk."], "identityChanges": ["May gain one good character ability once per game."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-drunk the in-play role; save as draft only."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Receives once-per-game advice to help own team."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice draft: {advice}"], "highRiskNotes": ["Advice is ST-authored; AI can only draft wording."]}),
  role({"id": "ravenkeeper", "name": "守鸦人", "officialName": "Ravenkeeper", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，你会被唤醒，然后你要选择一名玩家：你会得知他的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/ravenkeeper.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["If dies at night, wakes and learns selected player character."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only night death triggers."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "barber", "name": "理发师", "officialName": "Barber", "team": "outsider", "abilityText": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["On death, Demon may swap two non-Demon players characters."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Demon choice and identity swap are manual; do not auto-update roles."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["On learning death, public choice of an evil living player makes own team lose."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss remains storyteller declaration."]}),
  role({"id": "recluse", "name": "陌客", "officialName": "Recluse", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": ["May register as evil, Minion or Demon even while dead."], "playerMessageTemplates": [], "highRiskNotes": ["Registration is contextual; never permanently change alignment."]}),
  role({"id": "pithag", "name": "麻脸巫婆", "officialName": "Pit-Hag", "team": "minion", "abilityText": "每个夜晚*，你要选择一名玩家和一个角色，如果该角色不在场，他变成该角色。如果因此创造了一个恶魔，当晚的死亡由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pit-hag.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["If a Demon is created, deaths that night are storyteller choice."], "identityChanges": ["If chosen character is not in play, target becomes that character."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-change identity or death; check in-play character first."]}),
  role({"id": "witch", "name": "女巫", "officialName": "Witch", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：如果他明天白天发起提名，他死亡。如果只有三名存活的玩家，你失去此能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/witch.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Chosen player may die when nominating tomorrow; ability off at 3 living players."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Nomination death requires day confirmation."]}),
  role({"id": "poisoner", "name": "投毒者", "officialName": "Poisoner", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：他在当晚和明天白天中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/poisoner.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Chosen player is poisoned tonight and tomorrow day."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Poison duration and affected info are manual."]}),
  role({"id": "harpy", "name": "鹰身女妖", "officialName": "Harpy", "team": "minion", "abilityText": "每个夜晚，你要选择两名玩家：明天第一名玩家需要“疯狂”地证明第二名玩家是邪恶的，否则他们可能会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202307/c_4331482099861_0db1bfaf.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Failure can make one or both players die."], "stateChanges": ["First target must be mad that second target is evil tomorrow."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You are mad that {seatB} is evil tomorrow."], "highRiskNotes": ["Madness judgment and death penalty are storyteller discretion."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Each night may kill one player."], "identityChanges": ["If Imp kills self this way, a Minion may become Imp."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Self-kill pass must be confirmed; do not auto-promote Minion."]}),
  role({"id": "kazali", "name": "卡扎力", "officialName": "Kazali", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。[由你决定谁是什么爪牙，-或+任意数量外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202312/c_7795403383071_0f9107d8.jpg", "inputKinds": ["player", "players", "role"], "setupImpact": ["At setup, Kazali chooses which players are which Minions.", "May add or remove any number of Outsiders."], "possibleOutcomes": [], "stateChanges": ["Each other night chooses a player to die."], "identityChanges": ["Opening Minion assignments are storyteller-confirmed."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; no automatic identity or outsider-count changes."]}),
  role({"id": "vigormortis", "name": "亡骨魔", "officialName": "Vigormortis", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vigormortis.png", "inputKinds": ["player"], "setupImpact": ["Removes 1 Outsider."], "possibleOutcomes": [], "stateChanges": ["Kills target; killed Minion keeps ability and one neighboring Townsfolk is poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; do not auto-poison neighbors."]}),
] as const satisfies readonly SmartRoleDefinition[]
