import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "mo-ni-zhi-jiao"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const moNiZhiJiaoSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["gossip", "savant", "philosopher", "seamstress", "nightwatchman", "assassin", "aohe"], bluffs: ["ravenkeeper", "drunk", "ogre"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["savant", "philosopher", "seamstress", "nightwatchman", "ravenkeeper", "widow", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["philosopher", "seamstress", "nightwatchman", "ravenkeeper", "xiuxingzhe", "cerenovus", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["savant", "philosopher", "seamstress", "nightwatchman", "ravenkeeper", "drunk", "widow", "aohe"], bluffs: ["ogre", "klutz", "plaguedoctor"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["philosopher", "seamstress", "nightwatchman", "ravenkeeper", "xiuxingzhe", "ogre", "cerenovus", "aohe"], bluffs: ["drunk", "klutz", "plaguedoctor"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["philosopher", "seamstress", "nightwatchman", "ravenkeeper", "xiuxingzhe", "ogre", "klutz", "cerenovus", "aohe"], bluffs: ["drunk", "plaguedoctor", "widow"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["seamstress", "nightwatchman", "ravenkeeper", "xiuxingzhe", "chef", "klutz", "plaguedoctor", "harpy", "aohe"], bluffs: ["drunk", "ogre", "widow"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["seamstress", "nightwatchman", "ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "harpy", "assassin", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["nightwatchman", "ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "empath", "assassin", "widow", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "empath", "undertaker", "widow", "cerenovus", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["nightwatchman", "ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "empath", "plaguedoctor", "assassin", "widow", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "empath", "undertaker", "drunk", "widow", "cerenovus", "aohe"], bluffs: ["ogre", "klutz", "plaguedoctor"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["ravenkeeper", "xiuxingzhe", "chef", "pixie", "dreamer", "empath", "undertaker", "drunk", "ogre", "widow", "cerenovus", "aohe"], bluffs: ["klutz", "plaguedoctor", "harpy"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["xiuxingzhe", "chef", "pixie", "dreamer", "empath", "undertaker", "monk", "ogre", "klutz", "cerenovus", "harpy", "aohe"], bluffs: ["drunk", "plaguedoctor", "widow"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["chef", "pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "klutz", "plaguedoctor", "harpy", "assassin", "aohe"], bluffs: ["ogre", "widow", "cerenovus"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["xiuxingzhe", "chef", "pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "savant", "cerenovus", "harpy", "assassin", "aohe"], bluffs: ["drunk", "ogre", "klutz"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["chef", "pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "savant", "philosopher", "harpy", "assassin", "widow", "aohe"], bluffs: ["ogre", "klutz", "plaguedoctor"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["chef", "pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "savant", "philosopher", "klutz", "harpy", "assassin", "widow", "aohe"], bluffs: ["ogre", "plaguedoctor", "cerenovus"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "savant", "philosopher", "seamstress", "plaguedoctor", "assassin", "widow", "cerenovus", "aohe"], bluffs: ["klutz", "harpy", "xiuxingzhe"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["pixie", "dreamer", "empath", "undertaker", "monk", "gossip", "savant", "philosopher", "seamstress", "plaguedoctor", "drunk", "assassin", "widow", "cerenovus", "aohe"], bluffs: ["klutz", "harpy", "xiuxingzhe"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["dreamer", "empath", "undertaker", "monk", "gossip", "savant", "philosopher", "seamstress", "nightwatchman", "drunk", "ogre", "widow", "cerenovus", "harpy", "aohe"], bluffs: ["plaguedoctor", "assassin", "xiuxingzhe"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["empath", "undertaker", "monk", "gossip", "savant", "philosopher", "seamstress", "nightwatchman", "ravenkeeper", "ogre", "klutz", "cerenovus", "harpy", "assassin", "aohe"], bluffs: ["widow", "xiuxingzhe", "chef"], note: "Verified setup; Baron/Lil Monsta/Vigormortis setup-changing paths stay out of normal templates; Aohe/Pit-Hag-style identity/death decisions remain ST-confirmed." }),
]
