import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20746_59942.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Quan Mian Su Qing', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const quanMianSuQingRoles = [
  role({"id": "chambermaid", "name": "侍女", "officialName": "Chambermaid", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Chambermaid result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Pixie result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "chef", "name": "厨师", "officialName": "Chef", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Chef result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Noble result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "empath", "name": "共情者", "officialName": "Empath", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Empath result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "balloonist", "name": "气球驾驶员", "officialName": "Balloonist", "team": "townsfolk", "abilityText": "每个夜晚，你会得知一名不同角色类型的玩家，直到场上所有的角色类型你都得知过一次。[+1 外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/balloonist.png", "inputKinds": ["none"], "setupImpact": ["[+1 外来者]", "[+1 Outsider reminder]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Balloonist setup count path stays manual; excluded from first normal templates."]}),
  role({"id": "flowergirl", "name": "卖花女孩", "officialName": "Flowergirl", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知在今天白天时是否有恶魔投过票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/flowergirl.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Flowergirl result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Oracle result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "monk", "name": "僧侣", "officialName": "Monk", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Monk result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Seamstress result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "slayer", "name": "猎手", "officialName": "Slayer", "team": "townsfolk", "abilityText": "每局游戏限一次，你可以在白天时公开选择一名玩家：如果他是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/slayer.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Slayer result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Cannibal result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "sage", "name": "贤者", "officialName": "Sage", "team": "townsfolk", "abilityText": "如果恶魔杀死了你，在当晚你会被唤醒并得知两名玩家，其中一名是杀死你的那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sage.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity or information result."], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Sage result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "butler", "name": "管家", "officialName": "Butler", "team": "outsider", "abilityText": "每个夜晚，你要选择除你以外的一名玩家：明天白天，只有他投票时你才能投票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/butler.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Butler result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "barber", "name": "理发师", "officialName": "Barber", "team": "outsider", "abilityText": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Barber swaps create identity changes only after storyteller confirmation."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Klutz loss condition is never auto-judged."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["Source setup reminder", "[Hidden Drunk identity]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Drunk hidden identity is manual/private; excluded from first normal templates."]}),
  role({"id": "mezepheles", "name": "灵言师", "officialName": "Mezepheles", "team": "minion", "abilityText": "在你的首个夜晚，你会得知一个关键词。首个说出该关键词的善良玩家会在当晚转变为邪恶阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mezepheles.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Secret-word alignment change must be confirmed before changing team."]}),
  role({"id": "widow", "name": "寡妇", "officialName": "Widow", "team": "minion", "abilityText": "在你的首个夜晚，你能查看魔典并选择一名玩家：他中毒。随后，始终会有一名善良玩家知道寡妇在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/widow.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Widow grimoire view and poison target are reminders only; no automatic poison."]}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "Cerenovus", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Cerenovus result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Scarlet Woman result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "lilmonsta", "name": "小怪宝", "officialName": "Lil' Monsta", "team": "demon", "abilityText": "每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，会有一名玩家死亡。[+1爪牙]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lil_monsta.png", "inputKinds": ["none"], "setupImpact": ["[+1爪牙]", "[Special Demon setup]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Lil' Monsta special Demon babysitter setup stays manual; excluded from first normal templates."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Imp result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "fanggu", "name": "方古", "officialName": "Fang Gu", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fang_gu.png", "inputKinds": ["none"], "setupImpact": ["[+1外来者]", "[+1 Outsider reminder]"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Fang Gu Outsider count and jump logic are manual; excluded from first normal templates."]}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "No Dashii", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "No Dashii neighbor poison must be checked by seating and current role snapshot."]}),
  role({"id": "djinn", "name": "灯神", "officialName": "Djinn", "team": "fabled", "abilityText": "使用灯神的相克规则。所有玩家都会知道其内容。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/djinn.png", "inputKinds": ["none"], "setupImpact": ["Fabled jinx reminder"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Fabled roles never enter normal setup templates or demon bluffs.", "Fabled roles never enter normal setup templates or demon bluffs."]}),
  role({"id": "spiritofivory", "name": "圣洁之魂", "officialName": "Spirit of Ivory", "team": "fabled", "abilityText": "游戏过程中邪恶玩家的总数最多能比初始设置多一名。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/spirit_of_ivory.png", "inputKinds": ["none"], "setupImpact": ["Fabled extra-evil limit reminder"], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply this role result; storyteller confirms before writing authority state.", "Setup bracket changes are reminders only until storyteller confirms.", "Fabled roles never enter normal setup templates or demon bluffs.", "Fabled roles never enter normal setup templates or demon bluffs."]}),
] as const satisfies readonly SmartRoleDefinition[]
