import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "quan-mian-su-qing"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const quanMianSuQingSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["chef", "noble", "empath", "seamstress", "slayer", "widow", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["chambermaid", "pixie", "flowergirl", "oracle", "sage", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["empath", "monk", "cannibal", "chef", "noble", "mezepheles", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["chef", "noble", "empath", "seamstress", "slayer", "butler", "widow", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["chambermaid", "pixie", "flowergirl", "oracle", "sage", "barber", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["chef", "noble", "empath", "seamstress", "slayer", "butler", "barber", "widow", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["chambermaid", "pixie", "flowergirl", "oracle", "monk", "barber", "klutz", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["chambermaid", "chef", "noble", "empath", "flowergirl", "seamstress", "slayer", "widow", "cerenovus", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["pixie", "oracle", "monk", "cannibal", "sage", "flowergirl", "seamstress", "mezepheles", "scarletwoman", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["chef", "empath", "flowergirl", "monk", "seamstress", "slayer", "cannibal", "widow", "cerenovus", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["chambermaid", "chef", "noble", "empath", "flowergirl", "seamstress", "slayer", "butler", "widow", "cerenovus", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["pixie", "oracle", "monk", "cannibal", "sage", "flowergirl", "seamstress", "klutz", "mezepheles", "scarletwoman", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["chambermaid", "chef", "noble", "empath", "flowergirl", "seamstress", "slayer", "butler", "barber", "widow", "cerenovus", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["pixie", "oracle", "monk", "cannibal", "sage", "seamstress", "slayer", "butler", "klutz", "mezepheles", "scarletwoman", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["chef", "empath", "flowergirl", "monk", "seamstress", "slayer", "cannibal", "barber", "klutz", "widow", "cerenovus", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["chambermaid", "pixie", "chef", "noble", "empath", "flowergirl", "oracle", "monk", "seamstress", "widow", "cerenovus", "scarletwoman", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["chambermaid", "pixie", "noble", "empath", "flowergirl", "oracle", "monk", "cannibal", "sage", "mezepheles", "widow", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["chambermaid", "pixie", "chef", "noble", "empath", "flowergirl", "oracle", "monk", "seamstress", "butler", "widow", "cerenovus", "scarletwoman", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["chambermaid", "pixie", "noble", "empath", "flowergirl", "oracle", "monk", "cannibal", "sage", "barber", "mezepheles", "widow", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["chambermaid", "pixie", "chef", "noble", "empath", "flowergirl", "oracle", "monk", "seamstress", "butler", "barber", "widow", "cerenovus", "scarletwoman", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["chambermaid", "pixie", "noble", "empath", "flowergirl", "oracle", "monk", "slayer", "cannibal", "barber", "klutz", "mezepheles", "widow", "cerenovus", "nodashii"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["chef", "noble", "empath", "flowergirl", "monk", "seamstress", "slayer", "cannibal", "sage", "barber", "klutz", "widow", "cerenovus", "scarletwoman", "imp"], "bluffs": ["balloonist", "drunk", "fanggu"], "note": "Verified normal setup; Balloonist, Drunk, Fang Gu and Lil' Monsta setup or hidden/special paths stay manual. Fabled roles stay outside templates/bluffs. Widow, Mezepheles, Cerenovus, Scarlet Woman, No Dashii, Barber, Klutz, Cannibal and Sage outcomes remain ST-confirmed."}),
]
