import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "tou-tian-huan-ri"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const touTianHuanRiSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "seamstress", "magician", "poisoner", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["fortuneteller", "towncrier", "general", "ravenkeeper", "mathematician", "cerenovus", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["innkeeper", "lycanthrope", "savant", "pixie", "mathematician", "witch", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "seamstress", "magician", "mutant", "poisoner", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["fortuneteller", "towncrier", "general", "ravenkeeper", "mathematician", "recluse", "cerenovus", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["clockmaker", "pixie", "empath", "seamstress", "magician", "mutant", "recluse", "poisoner", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["fortuneteller", "towncrier", "general", "ravenkeeper", "mathematician", "mutant", "recluse", "cerenovus", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "empath", "towncrier", "seamstress", "magician", "poisoner", "cerenovus", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["lycanthrope", "fortuneteller", "general", "ravenkeeper", "mathematician", "savant", "clockmaker", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["pixie", "innkeeper", "lycanthrope", "empath", "seamstress", "magician", "savant", "poisoner", "witch", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "empath", "towncrier", "seamstress", "magician", "mutant", "poisoner", "cerenovus", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["lycanthrope", "fortuneteller", "general", "ravenkeeper", "mathematician", "savant", "clockmaker", "recluse", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "empath", "towncrier", "seamstress", "magician", "mutant", "recluse", "poisoner", "cerenovus", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["lycanthrope", "fortuneteller", "general", "ravenkeeper", "mathematician", "savant", "clockmaker", "mutant", "recluse", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["pixie", "innkeeper", "lycanthrope", "empath", "seamstress", "magician", "savant", "mutant", "recluse", "poisoner", "witch", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "lycanthrope", "fortuneteller", "empath", "towncrier", "seamstress", "magician", "poisoner", "cerenovus", "scarletwoman", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["general", "ravenkeeper", "mathematician", "magician", "savant", "pixie", "fortuneteller", "seamstress", "clockmaker", "poisoner", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "lycanthrope", "fortuneteller", "empath", "towncrier", "seamstress", "magician", "mutant", "poisoner", "cerenovus", "scarletwoman", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["general", "ravenkeeper", "mathematician", "magician", "savant", "pixie", "fortuneteller", "seamstress", "clockmaker", "recluse", "poisoner", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["clockmaker", "pixie", "innkeeper", "lycanthrope", "fortuneteller", "empath", "towncrier", "seamstress", "magician", "mutant", "recluse", "poisoner", "cerenovus", "scarletwoman", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["general", "ravenkeeper", "mathematician", "magician", "savant", "pixie", "fortuneteller", "seamstress", "clockmaker", "mutant", "recluse", "poisoner", "witch", "scarletwoman", "pukka"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["pixie", "innkeeper", "lycanthrope", "empath", "towncrier", "seamstress", "magician", "savant", "mathematician", "mutant", "recluse", "poisoner", "cerenovus", "witch", "imp"], "bluffs": ["drunk", "lunatic", "goon"], "note": "Verified normal setup; Drunk, Lunatic, Goon and Fang Gu hidden/alignment/setup paths stay manual. Lycanthrope, Fortune Teller, Cerenovus, Poisoner, Scarlet Woman, Witch, Imp and Pukka outcomes remain ST-confirmed."}),
]
