import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "man-tang-hong"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const manTangHongSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "noble", "chef", "niangjiushi", "imp"], bluffs: ["savant", "gambler", "fisherman"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["yanshi", "chongfei", "savant", "cannibal", "gossip", "panguan", "jianning"], bluffs: ["slayer", "fisherman", "recluse"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["slayer", "gambler", "fisherman", "chef", "tixingguan", "pithag", "imp"], bluffs: ["flowergirl", "towncrier", "drunk"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["flowergirl", "towncrier", "savant", "noble", "chef", "drunk", "assassin", "jianning"], bluffs: ["tixingguan", "cannibal", "gossip"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["yanshi", "chongfei", "cannibal", "gossip", "gambler", "recluse", "panguan", "imp"], bluffs: ["slayer", "fisherman", "mutant"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "noble", "chef", "rulianshi", "drunk", "niangjiushi", "imp"], bluffs: ["savant", "cannibal", "gossip"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["yanshi", "chongfei", "savant", "cannibal", "gambler", "recluse", "mutant", "pithag", "jianning"], bluffs: ["flowergirl", "towncrier", "fisherman"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "noble", "chef", "gambler", "niangjiushi", "assassin", "imp"], bluffs: ["cannibal", "gossip", "slayer"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["yanshi", "chongfei", "cannibal", "gossip", "slayer", "fisherman", "chef", "panguan", "pithag", "jianning"], bluffs: ["flowergirl", "towncrier", "gambler"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["flowergirl", "towncrier", "savant", "cannibal", "gossip", "noble", "slayer", "pithag", "assassin", "imp"], bluffs: ["tixingguan", "yanshi", "chongfei"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "noble", "chef", "gambler", "drunk", "niangjiushi", "panguan", "jianning"], bluffs: ["cannibal", "gossip", "fisherman"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["yanshi", "chongfei", "cannibal", "gossip", "slayer", "fisherman", "chef", "recluse", "pithag", "assassin", "imp"], bluffs: ["tixingguan", "flowergirl", "towncrier"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "noble", "chef", "gambler", "rulianshi", "drunk", "niangjiushi", "assassin", "imp"], bluffs: ["yanshi", "cannibal", "gossip"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["yanshi", "chongfei", "cannibal", "gossip", "slayer", "fisherman", "chef", "recluse", "mutant", "panguan", "pithag", "jianning"], bluffs: ["tixingguan", "flowergirl", "towncrier"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["flowergirl", "towncrier", "savant", "cannibal", "gossip", "noble", "slayer", "drunk", "mutant", "pithag", "assassin", "imp"], bluffs: ["yanshi", "chongfei", "fisherman"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "noble", "chef", "gambler", "niangjiushi", "panguan", "assassin", "jianning"], bluffs: ["yanshi", "chongfei", "slayer"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["yanshi", "chongfei", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "slayer", "fisherman", "pithag", "panguan", "assassin", "imp"], bluffs: ["tixingguan", "noble", "chef"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "noble", "chef", "gambler", "drunk", "niangjiushi", "panguan", "assassin", "imp"], bluffs: ["yanshi", "chongfei", "slayer"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["yanshi", "chongfei", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "slayer", "fisherman", "mutant", "pithag", "panguan", "assassin", "jianning"], bluffs: ["tixingguan", "noble", "chef"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["tixingguan", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "noble", "chef", "gambler", "rulianshi", "drunk", "niangjiushi", "panguan", "assassin", "jianning"], bluffs: ["yanshi", "chongfei", "slayer"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["yanshi", "chongfei", "flowergirl", "towncrier", "savant", "cannibal", "gossip", "slayer", "fisherman", "recluse", "mutant", "pithag", "panguan", "assassin", "imp"], bluffs: ["tixingguan", "noble", "chef"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["tixingguan", "yanshi", "chongfei", "savant", "cannibal", "gossip", "noble", "slayer", "fisherman", "drunk", "mutant", "niangjiushi", "pithag", "assassin", "imp"], bluffs: ["flowergirl", "towncrier", "chef"], note: "Verified setup; Godfather and Lil Monsta setup-changing paths stay out of first normal templates; Yanshi/Rulianshi/Pit-Hag/Gambler/Slayer/Gossip/Panguan/Jianning outcomes remain ST-confirmed." }),
]
