import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "gui-jue-yi-xiang"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const guiJueYiXiangSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "chimei", "jianning"], "bluffs": ["langzhong", "wudaozhe", "dagengren"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "gudiao", "jianning"], "bluffs": ["fangshi", "wushiren", "zhanxingzhe"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["yinyangshi", "jinyiwei", "daoshi", "xionghaizi", "xingjiaoshang", "ganshiren", "dianyuzhang"], "bluffs": ["dagengren", "wudaozhe", "langzhong"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "nichen", "chimei", "jianning"], "bluffs": ["langzhong", "wudaozhe", "dagengren"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "nichen", "gudiao", "jianning"], "bluffs": ["fangshi", "wushiren", "zhanxingzhe"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "nichen", "jiubao", "chimei", "jianning"], "bluffs": ["langzhong", "wudaozhe", "dagengren"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "nichen", "rulianshi", "gudiao", "jianning"], "bluffs": ["fangshi", "wushiren", "zhanxingzhe"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "chimei", "gudiao", "jianning"], "bluffs": ["dagengren", "xingjiaoshang", "xionghaizi"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "gudiao", "chimei", "jianning"], "bluffs": ["zhanxingzhe", "dianxiaoer", "langzhong"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["yinyangshi", "jinyiwei", "daoshi", "xionghaizi", "xingjiaoshang", "dagengren", "wudaozhe", "ganshiren", "gudiao", "dianyuzhang"], "bluffs": ["langzhong", "dianxiaoer", "zhanxingzhe"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "nichen", "chimei", "gudiao", "jianning"], "bluffs": ["dagengren", "xingjiaoshang", "xionghaizi"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "nichen", "gudiao", "chimei", "jianning"], "bluffs": ["zhanxingzhe", "dianxiaoer", "langzhong"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "nichen", "jiubao", "chimei", "gudiao", "jianning"], "bluffs": ["dagengren", "xingjiaoshang", "xionghaizi"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "nichen", "rulianshi", "gudiao", "chimei", "jianning"], "bluffs": ["zhanxingzhe", "dianxiaoer", "langzhong"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["yinyangshi", "jinyiwei", "daoshi", "xionghaizi", "xingjiaoshang", "dagengren", "wudaozhe", "shaxing", "rulianshi", "ganshiren", "gudiao", "dianyuzhang"], "bluffs": ["langzhong", "dianxiaoer", "zhanxingzhe"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "dagengren", "xingjiaoshang", "chimei", "gudiao", "ganshiren", "jianning"], "bluffs": ["xionghaizi", "daoshi", "jinyiwei"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "gudiao", "chimei", "ganshiren", "jianning"], "bluffs": ["langzhong", "dagengren", "xingjiaoshang"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "dagengren", "xingjiaoshang", "nichen", "chimei", "gudiao", "ganshiren", "jianning"], "bluffs": ["xionghaizi", "daoshi", "jinyiwei"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "nichen", "gudiao", "chimei", "ganshiren", "jianning"], "bluffs": ["langzhong", "dagengren", "xingjiaoshang"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "langzhong", "wudaozhe", "dagengren", "xingjiaoshang", "nichen", "jiubao", "chimei", "gudiao", "ganshiren", "jianning"], "bluffs": ["xionghaizi", "daoshi", "jinyiwei"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["wudaozhe", "xionghaizi", "daoshi", "jinyiwei", "lingren", "fangshi", "wushiren", "zhanxingzhe", "dianxiaoer", "nichen", "rulianshi", "gudiao", "chimei", "ganshiren", "jianning"], "bluffs": ["langzhong", "dagengren", "xingjiaoshang"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["yinyangshi", "jinyiwei", "daoshi", "xionghaizi", "xingjiaoshang", "dagengren", "wudaozhe", "langzhong", "dianxiaoer", "shaxing", "rulianshi", "ganshiren", "gudiao", "chimei", "dianyuzhang"], "bluffs": ["zhanxingzhe", "wushiren", "fangshi"], "note": "Verified normal setup; Hun Dun, Tao Tie and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, registration, drunk/poison, fake identity and alignment shifts are AI suggestions only."}),
]
