import type { SetupRule } from '../../types'

export const yinHeManBuSetupRules: readonly SetupRule[] = [
  {"id": "godfather-setup", "roleId": "godfather", "summary": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "fanggu-setup", "roleId": "fanggu", "summary": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "vigormortis-setup", "roleId": "vigormortis", "summary": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "godfather-high-risk", "roleId": "godfather", "summary": "Godfather outsider-count adjustment and outsider-death extra kill stay setup/night reminders only.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "fanggu-high-risk", "roleId": "fanggu", "summary": "Fang Gu adds one Outsider and can jump once to an Outsider; old Fang Gu death and new Demon/alignment are manual confirmations.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "vigormortis-high-risk", "roleId": "vigormortis", "summary": "Vigormortis removes one Outsider; killed Minion keeps ability and neighbor poisoning must be tracked manually.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "pithag-high-risk", "roleId": "pithag", "summary": "Pit-Hag identity changes are candidate reminders; if a Demon is created, deaths that night are ST-authored.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "barber-high-risk", "roleId": "barber", "summary": "Barber swaps are Demon-choice identity changes and never auto-change roles.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "cannibal-high-risk", "roleId": "cannibal", "summary": "Cannibal gains last executed player ability and may be poisoned if that player was evil; current ability source must be confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "puzzlemaster-high-risk", "roleId": "puzzlemaster", "summary": "Puzzlemaster drunk choice and once-per-game guess are manual; never tell the Puzzlemaster whether the guess was correct—only give one player name (the Demon if correct, a non-Demon player if wrong). A dead Puzzlemaster cannot guess (his drunk effect persists), and only guessing the player made drunk by his own ability counts as correct.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
  {"id": "fortuneteller-high-risk", "roleId": "fortuneteller", "summary": "Fortune Teller result may include the red herring; do not compute from Demon identity alone.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20761_59924.json"], "reviewedAt": "2026-07-22"},
]
