import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"
const rolesSourceUrl = "https://clocktower.gstonegames.com/ct/grimoireRoleJson/"
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Chuan Qi Zhi Ye', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const chuanQiZhiYeRoles = [
  role({"id": "bountyhunter", "name": "赏金猎人", "officialName": "Bounty Hunter", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名邪恶玩家。每当你得知的玩家死亡，你会在当晚得知另一名邪恶玩家。[会有一名镇民转变为邪恶阵营]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/bounty_hunter.png", "inputKinds": ["player"], "setupImpact": ["One Townsfolk becomes evil."], "possibleOutcomes": ["Learns one evil player; when that player dies, learns another evil player that night."], "stateChanges": [], "identityChanges": [], "teamChanges": ["One Townsfolk is turned evil at setup."], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; extra evil Townsfolk must be chosen and recorded manually."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Learns an in-play Townsfolk; if mad as that role, gains that ability when the role dies."], "stateChanges": [], "identityChanges": ["May gain the learned Townsfolk ability later."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Madness judgment and gained ability are ST-confirmed."]}),
  role({"id": "investigator", "name": "调查员", "officialName": "Investigator", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两名玩家和一个爪牙角色：这两名玩家之一是该角色（或者你会得知没有爪牙在场）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/investigator.png", "inputKinds": ["players", "role"], "setupImpact": [], "possibleOutcomes": ["Learns two players and one Minion role; one is that Minion, or learns no Minion is in play."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Pair and Minion role are ST-authored and remain editable."]}),
  role({"id": "exorcist", "name": "驱魔人", "officialName": "Exorcist", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家（与上个夜晚不同）：如果你选中了恶魔，他会得知你是驱魔人，但他当晚不会因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/exorcist.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["If choosing the Demon, Demon learns Exorcist and does not wake from own ability tonight."], "stateChanges": ["May block Demon wake/action for the night."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If the Demon is chosen, tell the Demon: Exorcist chose you."], "highRiskNotes": ["Must choose a different player from previous night; do not auto-skip Demon action."]}),
  role({"id": "gambler", "name": "赌徒", "officialName": "Gambler", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家并猜测他的角色：如果你猜错了，你会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gambler.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Chooses a player and guesses their character; dies if wrong."], "stateChanges": ["May die if the guess is wrong."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["ST checks actual character and confirms death; AI may suggest only."]}),
  role({"id": "undertaker", "name": "送葬者", "officialName": "Undertaker", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天白天死于处决的玩家的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/undertaker.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Learns the character of the player executed today."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Execution record, false registration and shown role remain ST-confirmed."]}),
  role({"id": "towncrier", "name": "城镇公告员", "officialName": "Town Crier", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知在今天白天时是否有爪牙发起过提名。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/town_crier.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns whether a Minion nominated today."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Nomination records and Minion registration are ST-confirmed."]}),
  role({"id": "monk", "name": "僧侣", "officialName": "Monk", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Protects a non-self player from the Demon's harmful ability tonight."], "stateChanges": ["May prevent Demon-caused harm to the protected player."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Protection source and harmful effect are ST-confirmed; do not auto-prevent deaths."]}),
  role({"id": "gossip", "name": "造谣者", "officialName": "Gossip", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If public statement is true, one player dies tonight."], "stateChanges": ["May cause one night death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Truth check and death target are ST-confirmed."]}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Each day learns two statements: one true and one false."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Statements are ST-authored and should remain editable."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Once per game chooses two non-self players and learns whether they share alignment."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Alignment and registration exceptions are ST-confirmed."]}),
  role({"id": "nightwatchman", "name": "守夜人", "officialName": "Nightwatchman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名玩家：他会得知你是守夜人。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/nightwatchman.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Once per game chooses a player; that player learns Nightwatchman identity."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn that {seat} is the Nightwatchman."], "highRiskNotes": ["Use-once and target message are manual."]}),
  role({"id": "farmer", "name": "农夫", "officialName": "Farmer", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，一名存活的善良玩家会变成农夫。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/farmer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["If Farmer dies at night, a living good player becomes Farmer."], "stateChanges": [], "identityChanges": ["A living good player may become Farmer."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-change identity; ST chooses and informs the new Farmer."]}),
  role({"id": "saint", "name": "圣徒", "officialName": "Saint", "team": "outsider", "abilityText": "如果你死于处决，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/saint.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["If executed, Saint's team loses."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss remains manual; do not auto-end game."]}),
  role({"id": "mutant", "name": "畸形秀演员", "officialName": "Mutant", "team": "outsider", "abilityText": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mutant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If mad about being an Outsider, may be executed."], "stateChanges": ["May be executed for madness violation."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Madness judgment and execution are ST discretion."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Believes they are a Townsfolk but is actually the Drunk."], "stateChanges": [], "identityChanges": ["False role shown to player is ST-confirmed."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Keep hidden identity manual; never reveal through player-facing data."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["On learning they died, publicly chooses a living player; if evil, Klutz's team loses."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Death notification, public choice and win/loss remain manual."]}),
  role({"id": "assassin", "name": "刺客", "officialName": "Assassin", "team": "minion", "abilityText": "每局游戏限一次，在夜晚时*，你可以选择一名玩家：他死亡，即使因为任何原因让他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/assassin.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Once per game chooses a player to die, even if protected."], "stateChanges": ["May cause unstoppable death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Use-once and death are manual."]}),
  role({"id": "organgrinder", "name": "街头风琴手", "officialName": "Organ Grinder", "team": "minion", "abilityText": "所有玩家在投票时闭眼，且票数会秘密统计。对你的提名只在你投票时才会统计票数。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202303/c_1527286859761_46867343.jpg", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Votes are secret; nominations of Organ Grinder count only if Organ Grinder votes."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Voting UI remains manual; do not hide or rewrite vote records automatically."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["If Demon dies with five or more players alive, Scarlet Woman becomes that Demon."], "stateChanges": [], "identityChanges": ["May become the Demon."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Demon death, living count and transformation are ST-confirmed."]}),
  role({"id": "pithag", "name": "麻脸巫婆", "officialName": "Pit-Hag", "team": "minion", "abilityText": "每个夜晚*，你要选择一名玩家和一个角色，如果该角色不在场，他变成该角色。如果因此创造了一个恶魔，当晚的死亡由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pit-hag.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Changes a player into an out-of-play character; if a Demon is created, tonight's deaths are arbitrary."], "stateChanges": ["Created Demon may make deaths arbitrary tonight."], "identityChanges": ["Target may become chosen character."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Never auto-change identity; ST confirms timing and notifications."]}),
  role({"id": "pukka", "name": "普卡", "officialName": "Pukka", "team": "demon", "abilityText": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pukka.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Poisons tonight's target; previous poisoned target dies and becomes healthy."], "stateChanges": ["One target is poisoned; previous poisoned target may die and become healthy."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Poison chain and death timing are ST-confirmed."]}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "No Dashii", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses a player to die; nearest two Townsfolk neighbors are poisoned."], "stateChanges": ["May cause death and poison two neighboring Townsfolk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Neighbor selection and poison status are manual."]}),
  role({"id": "vigormortis", "name": "亡骨魔", "officialName": "Vigormortis", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vigormortis.png", "inputKinds": ["player"], "setupImpact": ["Reduce Outsider count by one."], "possibleOutcomes": ["Chooses a player to die; killed Minions keep abilities and one neighboring Townsfolk is poisoned."], "stateChanges": ["May cause death and poison one Townsfolk neighbor."], "identityChanges": ["Killed Minions may continue using ability while dead."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; death, retained ability and poison are manual."]}),
  role({"id": "po", "name": "珀", "officialName": "Po", "team": "demon", "abilityText": "每个夜晚*，你可以选择一名玩家：他死亡。如果你上次选择时没有选择任何玩家，当晚你要选择三名玩家：他们死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/po.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Kills one player, or after a no-kill charge night kills three players."], "stateChanges": ["May cause one or three deaths."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Charge state and death targets are ST-confirmed."]}),
] as const satisfies readonly SmartRoleDefinition[]
