import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "chuan-qi-zhi-ye"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const chuanQiZhiYeSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "assassin", "pukka"], "bluffs": ["towncrier", "monk", "gossip"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 7, "style": "long-game", "roles": ["towncrier", "monk", "gossip", "savant", "seamstress", "organgrinder", "nodashii"], "bluffs": ["pixie", "investigator", "nightwatchman"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["nightwatchman", "farmer", "pixie", "investigator", "monk", "pithag", "po"], "bluffs": ["exorcist", "gambler", "undertaker"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "saint", "assassin", "pukka"], "bluffs": ["towncrier", "monk", "gossip"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 8, "style": "long-game", "roles": ["towncrier", "monk", "gossip", "savant", "seamstress", "mutant", "organgrinder", "nodashii"], "bluffs": ["pixie", "investigator", "nightwatchman"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "saint", "drunk", "assassin", "pukka"], "bluffs": ["towncrier", "monk", "gossip"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 9, "style": "long-game", "roles": ["towncrier", "monk", "gossip", "savant", "seamstress", "mutant", "klutz", "organgrinder", "nodashii"], "bluffs": ["pixie", "investigator", "nightwatchman"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "assassin", "organgrinder", "pukka"], "bluffs": ["gossip", "savant", "seamstress"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 10, "style": "long-game", "roles": ["gossip", "savant", "seamstress", "nightwatchman", "farmer", "pixie", "investigator", "scarletwoman", "pithag", "nodashii"], "bluffs": ["exorcist", "gambler", "undertaker"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["monk", "gossip", "savant", "seamstress", "nightwatchman", "farmer", "exorcist", "assassin", "pithag", "po"], "bluffs": ["pixie", "investigator", "towncrier"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "mutant", "assassin", "organgrinder", "pukka"], "bluffs": ["gossip", "savant", "seamstress"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 11, "style": "long-game", "roles": ["gossip", "savant", "seamstress", "nightwatchman", "farmer", "pixie", "investigator", "drunk", "scarletwoman", "pithag", "nodashii"], "bluffs": ["exorcist", "gambler", "undertaker"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "saint", "mutant", "assassin", "organgrinder", "pukka"], "bluffs": ["gossip", "savant", "seamstress"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 12, "style": "long-game", "roles": ["gossip", "savant", "seamstress", "nightwatchman", "farmer", "pixie", "investigator", "drunk", "klutz", "scarletwoman", "pithag", "nodashii"], "bluffs": ["exorcist", "gambler", "undertaker"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["monk", "gossip", "savant", "seamstress", "nightwatchman", "farmer", "exorcist", "saint", "drunk", "assassin", "pithag", "po"], "bluffs": ["pixie", "investigator", "towncrier"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "gossip", "savant", "assassin", "organgrinder", "scarletwoman", "pukka"], "bluffs": ["seamstress", "nightwatchman", "farmer"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 13, "style": "long-game", "roles": ["seamstress", "nightwatchman", "farmer", "pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "organgrinder", "scarletwoman", "pithag", "nodashii"], "bluffs": ["monk", "gossip", "savant"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "gossip", "savant", "saint", "assassin", "organgrinder", "scarletwoman", "pukka"], "bluffs": ["seamstress", "nightwatchman", "farmer"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 14, "style": "long-game", "roles": ["seamstress", "nightwatchman", "farmer", "pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "mutant", "organgrinder", "scarletwoman", "pithag", "nodashii"], "bluffs": ["monk", "gossip", "savant"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "monk", "gossip", "savant", "saint", "mutant", "assassin", "organgrinder", "scarletwoman", "pukka"], "bluffs": ["seamstress", "nightwatchman", "farmer"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "long", "count": 15, "style": "long-game", "roles": ["seamstress", "nightwatchman", "farmer", "pixie", "investigator", "exorcist", "gambler", "undertaker", "towncrier", "drunk", "klutz", "organgrinder", "scarletwoman", "pithag", "nodashii"], "bluffs": ["monk", "gossip", "savant"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["monk", "gossip", "savant", "seamstress", "nightwatchman", "farmer", "pixie", "investigator", "exorcist", "saint", "drunk", "assassin", "scarletwoman", "pithag", "po"], "bluffs": ["gambler", "undertaker", "towncrier"], "note": "已核对配板。赏金猎人与亡骨魔的配板变更路径不进入首批常规模板；麻脸巫婆、红唇女郎、普卡、诺-达鲺、珀的结果由说书人确认。"}),
]
