import type { SetupRule } from '../../types'

export const chuanQiZhiYeSetupRules: readonly SetupRule[] = [
  {"id": "bountyhunter-extra-evil", "roleId": "bountyhunter", "summary": "Bounty Hunter adds one evil Townsfolk; excluded from first normal templates.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "pixie-madness-gain", "roleId": "pixie", "summary": "Pixie madness and gained ability are ST-confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "gambler-wrong-guess-death", "roleId": "gambler", "summary": "Wrong Gambler guess kills Gambler after ST confirms the real character.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "gossip-night-death", "roleId": "gossip", "summary": "True Gossip statement may cause one night death.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "farmer-night-death-change", "roleId": "farmer", "summary": "Farmer night death may create a new Farmer.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "saint-execution-loss", "roleId": "saint", "summary": "Saint execution loss remains manual.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "mutant-madness-execution", "roleId": "mutant", "summary": "Mutant madness execution is ST discretion.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "drunk-hidden-identity", "roleId": "drunk", "summary": "Drunk false role is hidden and manual.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "klutz-death-loss", "roleId": "klutz", "summary": "Klutz death choice and loss condition remain manual.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "assassin-unstoppable-death", "roleId": "assassin", "summary": "Assassin once-per-game death is ST-confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "organgrinder-secret-vote", "roleId": "organgrinder", "summary": "Organ Grinder changes voting procedure but does not rewrite logs automatically.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "scarletwoman-demon-transfer", "roleId": "scarletwoman", "summary": "Scarlet Woman Demon transfer is ST-confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "pithag-character-change", "roleId": "pithag", "summary": "Pit-Hag character change and created-Demon deaths are manual.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "pukka-poison-death-chain", "roleId": "pukka", "summary": "Pukka poison/death chain is manually confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "nodashii-neighbor-poison", "roleId": "nodashii", "summary": "No Dashii neighbor poison is manually tracked.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "vigormortis-outsider-setup", "roleId": "vigormortis", "summary": "Vigormortis reduces Outsiders and creates retained Minion abilities; excluded from first normal templates.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
  {"id": "po-charge-triple-kill", "roleId": "po", "summary": "Po charge and triple kill are ST-confirmed.", "knowledgeStatus": "confirmed", "sourceUrls": ["https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20771_78762.json"], "reviewedAt": "2026-07-22"},
]
