import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20943_46831.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-21'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return {
    id: input.id,
    name: input.name,
    officialName: input.officialName,
    team: input.team,
    abilityText: input.abilityText,
    iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`,
    inputKinds: input.inputKinds,
    knowledgeStatus: 'confirmed',
    research: research(input),
  }
}

function research(input: RoleInput): RoleResearchMetadata {
  return {
    edition: "护犊之征",
    setupImpact: input.setupImpact ?? [],
    possibleOutcomes: input.possibleOutcomes ?? [],
    stateChanges: input.stateChanges ?? [],
    identityChanges: input.identityChanges ?? [],
    teamChanges: input.teamChanges ?? [],
    playerMessageTemplates: input.playerMessageTemplates ?? [],
    highRiskNotes: input.highRiskNotes ?? [],
    sourceUrls: [sourceUrl, rolesSourceUrl],
    reviewedAt,
  }
}

export const huDuZhiZhengRoles = [
  role({
    id: "chef",
    name: "厨师",
    officialName: "chef",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn: {number}."],
    highRiskNotes: ["First-night source reminder: 给他展示数字手势来告诉他场上邻座邪恶玩家有多少对。"],
  }),
  role({
    id: "yinyangshi",
    name: "阴阳师",
    officialName: "yinyangshi",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知两个善良角色和两个邪恶角色。其中有且只有两个角色在场。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4630967694761_bd56d041.jpg",
    inputKinds: ["none"],
    highRiskNotes: ["First-night source reminder: 唤醒阴阳师，并对其展示两个善良角色，两个邪恶角色，共四个角色标记。其中正好只有两个角色在场。"],
  }),
  role({
    id: "grandmother",
    name: "祖母",
    officialName: "grandmother",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知一名善良玩家和他的角色。如果恶魔杀死了他，你也会死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/grandmother.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["You learn seat {seat} is {role}."],
    highRiskNotes: ["First-night source reminder: 指向她的孙子玩家，并展示该玩家的角色标记。", "Other-night source reminder: 如果孙子被恶魔杀死，祖母也会一同死亡。标记祖母死亡。"],
  }),
  role({
    id: "bountyhunter",
    name: "赏金猎人",
    officialName: "bounty_hunter",
    team: "townsfolk",
    abilityText: "在你的首个夜晚，你会得知一名邪恶玩家。每当你得知的玩家死亡，你会在当晚得知另一名邪恶玩家。[会有一名镇民转变为邪恶阵营]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/bounty_hunter.png",
    inputKinds: ["none"],
    setupImpact: ["Bounty Hunter adds an extra evil Townsfolk; excluded from first templates unless explicitly chosen."],
    stateChanges: ["One Townsfolk may be evil from setup."],
    teamChanges: ["One Townsfolk becomes evil during setup."],
    playerMessageTemplates: ["You learn evil seat {seat}."],
    highRiskNotes: ["Bounty Hunter creates one extra evil Townsfolk; alignment setup must be confirmed manually.", "First-night source reminder: 指向一名邪恶玩家。随后唤醒那名因赏金猎人而转变为邪恶的镇民，并告知他变成了邪恶阵营。", "Other-night source reminder: 如果赏金猎人知晓的邪恶玩家死亡，指向另一名邪恶玩家。"],
  }),
  role({
    id: "preacher",
    name: "传教士",
    officialName: "preacher",
    team: "townsfolk",
    abilityText: "每个夜晚，你要选择一名玩家：如果选中了爪牙，他会得知被传教士选中。所有被你选中的爪牙失去能力。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/preacher.png",
    inputKinds: ["none"],
    highRiskNotes: ["First-night source reminder: 传教士选择一名玩家。如果选中了爪牙，则唤醒并告知他被传教士选中。", "Other-night source reminder: 传教士选择一名玩家。如果选中了爪牙，则唤醒并告知他被传教士选中。"],
  }),
  role({
    id: "cultleader",
    name: "异教领袖",
    officialName: "cult_leader",
    team: "townsfolk",
    abilityText: "每个夜晚，你会转变为与你邻近的一名存活的玩家的阵营。每个白天，你可以提议所有玩家加入你的教派，如果所有善良玩家同意加入，你的阵营获胜。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/cult_leader.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May create a good win candidate if all good players join the cult."],
    teamChanges: ["May change alignment nightly."],
    playerMessageTemplates: ["Your alignment may have changed; storyteller will confirm."],
    highRiskNotes: ["Cult Leader changes alignment and can create a win candidate; never auto-change team or declare victory.", "First-night source reminder: 如果异教领袖改变了阵营，告诉他。", "Other-night source reminder: 如果异教领袖改变了阵营，告诉他。"],
  }),
  role({
    id: "lycanthrope",
    name: "半兽人",
    officialName: "lycanthrope",
    team: "townsfolk",
    abilityText: "每个夜晚*，你要选择一名存活玩家：如果他是善良的，他死亡，并且当晚恶魔不会造成死亡。会有一名善良玩家始终被当作邪恶阵营。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/lycanthrope.png",
    inputKinds: ["player"],
    possibleOutcomes: ["Good target may die and the Demon does not kill tonight."],
    highRiskNotes: ["Lycanthrope may kill a good target and suppress the Demon kill tonight; one good player always registers as evil and cannot be killed this way; death-prevention chain remains manual.", "Other-night source reminder: 半兽人指向一名存活玩家：如果那名玩家善良，则立刻死去且当晚只有恶魔不会造成死亡，其他来源仍可造成死亡。"],
  }),
  role({
    id: "flowergirl",
    name: "卖花女孩",
    officialName: "flowergirl",
    team: "townsfolk",
    abilityText: "每个夜晚*，你会得知在今天白天时是否有恶魔投过票。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/flowergirl.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["Your answer is {yesNo}."],
    highRiskNotes: ["Other-night source reminder: 对她点头或摇头来示意今天白天是否有恶魔投过票。"],
  }),
  role({
    id: "towncrier",
    name: "城镇公告员",
    officialName: "town_crier",
    team: "townsfolk",
    abilityText: "每个夜晚*，你会得知在今天白天时是否有爪牙发起过提名。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/town_crier.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["Your answer is {yesNo}."],
    highRiskNotes: ["Other-night source reminder: 对他点头或摇头示意今天白天是否有爪牙发起过提名。"],
  }),
  role({
    id: "gossip",
    name: "造谣者",
    officialName: "gossip",
    team: "townsfolk",
    abilityText: "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png",
    inputKinds: ["none"],
    possibleOutcomes: ["If the statement is true, a player may die tonight."],
    highRiskNotes: ["Gossip may create a night death if statement is true; storyteller confirms truth and death.", "Other-night source reminder: 如果白天的声明为真，会有一名玩家死亡，并由说书人来选择一名玩家，标记该玩家死亡。"],
  }),
  role({
    id: "mayor",
    name: "镇长",
    officialName: "mayor",
    team: "townsfolk",
    abilityText: "如果只有三名玩家存活且白天没有人被处决，你的阵营获胜。如果你在夜晚即将死亡，可能会有一名其他玩家代替你死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/mayor.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May create a good win candidate if three players live and no execution happens."],
    highRiskNotes: ["Mayor win and death bounce are storyteller-confirmed candidates; this tool never declares victory."],
  }),
  role({
    id: "cannibal",
    name: "食人族",
    officialName: "cannibal",
    team: "townsfolk",
    abilityText: "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png",
    inputKinds: ["none"],
    highRiskNotes: ["Cannibal gains executed player ability and may be poisoned by evil execution; ability source remains manual."],
  }),
  role({
    id: "soldier",
    name: "士兵",
    officialName: "soldier",
    team: "townsfolk",
    abilityText: "恶魔的负面能力对你无效。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/soldier.png",
    inputKinds: ["none"],
  }),
  role({
    id: "wudaozhe",
    name: "悟道者",
    officialName: "wudaozhe",
    team: "townsfolk",
    abilityText: "你以为你是一个外来者，但你实际上不是。如果有邪恶玩家的能力选择或影响了你，你会立即变成一个不在场的镇民角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/1697467794_197011_3491.png",
    inputKinds: ["none"],
    setupImpact: ["Wudaozhe believes they are an Outsider and may become a not-in-play Townsfolk after evil ability impact; keep as manual reminder."],
    identityChanges: ["May become a not-in-play Townsfolk."],
    playerMessageTemplates: ["You are now {role}."],
    highRiskNotes: ["Identity change after evil ability impact must be confirmed and affects future night order only."],
  }),
  role({
    id: "snitch",
    name: "告密者",
    officialName: "snitch",
    team: "outsider",
    abilityText: "爪牙会在其首个夜晚得知三个不在场的善良角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/snitch.png",
    inputKinds: ["none"],
    playerMessageTemplates: ["These good roles are not in play: {roles}."],
    highRiskNotes: ["First-night source reminder: 分别给爪牙们展示三个不在场角色，这些信息之间，包括与展示给恶魔的不在场角色之间可能会有重叠。"],
  }),
  role({
    id: "drunk",
    name: "酒鬼",
    officialName: "drunk",
    team: "outsider",
    abilityText: "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png",
    inputKinds: ["none"],
    setupImpact: ["Drunk is hidden and thinks they are a Townsfolk; assign and verify manually during setup."],
    highRiskNotes: ["Drunk hidden identity is a setup reminder; do not reveal or auto-correct without storyteller action."],
  }),
  role({
    id: "saint",
    name: "圣徒",
    officialName: "saint",
    team: "outsider",
    abilityText: "如果你死于处决，你的阵营落败。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/saint.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May create a team-loss candidate if the Saint dies by execution."],
    highRiskNotes: ["If the Saint dies by execution, the Saint's team loses (execution without death, e.g. Scapegoat substitution, does not trigger); only create a win/loss reminder."],
  }),
  role({
    id: "klutz",
    name: "呆瓜",
    officialName: "klutz",
    team: "outsider",
    abilityText: "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png",
    inputKinds: ["none"],
    possibleOutcomes: ["May create a good-loss candidate after death choice."],
    highRiskNotes: ["Klutz death choice may lose the game for good; only create a win/loss reminder."],
  }),
  role({
    id: "politician",
    name: "政客",
    officialName: "politician",
    team: "outsider",
    abilityText: "如果你是对你的阵营落败负最大责任的人，你转变阵营并获胜，即使你已死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/politician.png",
    inputKinds: ["none"],
    teamChanges: ["May change alignment for win/loss responsibility."],
    highRiskNotes: ["Politician win/alignment judgment is storyteller discretion; never auto-change team."],
  }),
  role({
    id: "barber",
    name: "理发师",
    officialName: "barber",
    team: "outsider",
    abilityText: "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png",
    inputKinds: ["none"],
    identityChanges: ["Demon may swap two characters after Barber dies."],
    highRiskNotes: ["Barber death may let Demon swap two characters; identity changes require confirmation.", "Other-night source reminder: 如果理发师今天死亡了，唤醒恶魔并展示“该角色的效果对你生效”信息标记和理发师角色标记。如果恶魔选择了两名玩家，将这两名玩家分别独自唤醒。对他们展示“你是”信息标记和他们的新角色标记。"],
  }),
  role({
    id: "godfather",
    name: "教父",
    officialName: "godfather",
    team: "minion",
    abilityText: "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png",
    inputKinds: ["none"],
    setupImpact: ["Godfather may add or remove one Outsider and wakes on Outsider day death; excluded from first templates here."],
    highRiskNotes: ["Godfather Outsider info and death after Outsider day death are manual reminders.", "First-night source reminder: 对他展示所有在场的外来者标记。", "Other-night source reminder: 如果有外来者在今天白天死亡，让教父选择一名玩家。标记那名玩家死亡。"],
  }),
  role({
    id: "gudiao",
    name: "蛊雕",
    officialName: "gudiao",
    team: "minion",
    abilityText: "蛊雕：每个夜晚，你要选择左或右：将你的飞行标记从当前位置移动到这个方向上的下一名存活善良玩家。他中毒且可能被当作邪恶阵营和爪牙角色，你会知道他原本的角色。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4078497694761_5c6ddcce.jpg",
    inputKinds: ["none"],
    stateChanges: ["Target may be poisoned and may register as evil/Minion."],
    highRiskNotes: ["Gudiao poisoning, registration and role knowledge are custom reminders; state changes remain manual.", "此包沿用旧版蛊雕文本（每晚自选左右方向、目标为下一名存活善良玩家、被当作邪恶阵营和爪牙角色）；百科现行版本为：每个夜晚得知顺时针方向上的下一名存活的镇民玩家的角色，他中毒且可能被当作邪恶的蛊雕，直到下个黄昏；每局游戏限一次，在夜晚时可以改变方向。同时判定角色和阵营时，该玩家只能被当作“邪恶的蛊雕”。", "First-night source reminder: 唤醒蛊雕，让其选择一个方向。将他的“中毒”标记移动至那个方向上的下一个存活玩家的角色标记旁。随后对他指向那名玩家，并展示“他是”提示标记和该玩家的角色标记。", "Other-night source reminder: 唤醒蛊雕，让其选择一个方向。将他的“中毒”标记移动至那个方向上的下一个存活玩家的角色标记旁。随后对他指向那名玩家，并展示“他是”提示标记和该玩家的角色标记。"],
  }),
  role({
    id: "witch",
    name: "女巫",
    officialName: "witch",
    team: "minion",
    abilityText: "每个夜晚，你要选择一名玩家：如果他明天白天发起提名，他死亡。如果只有三名存活的玩家，你失去此能力。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/witch.png",
    inputKinds: ["none"],
    possibleOutcomes: ["Cursed nominator may die."],
    stateChanges: ["Selected player is cursed until nomination check."],
    highRiskNotes: ["Witch curse may kill a nominator; death remains manual and disabled at three alive.", "First-night source reminder: 让女巫选择一名玩家。标记那名玩家被诅咒。", "Other-night source reminder: 让女巫选择一名玩家。标记那名玩家被诅咒。"],
  }),
  role({
    id: "spy",
    name: "间谍",
    officialName: "spy",
    team: "minion",
    abilityText: "每个夜晚，你能查看魔典。你可能会被当作善良阵营、镇民角色或外来者角色，即使你已死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/spy.png",
    inputKinds: ["none"],
    highRiskNotes: ["Spy may register as good; grimoire viewing is a reminder only.", "First-night source reminder: 将魔典展示给间谍，他想看多久就看多久。", "Other-night source reminder: 将魔典展示给间谍，他想看多久就看多久。"],
  }),
  role({
    id: "assassin",
    name: "刺客",
    officialName: "assassin",
    team: "minion",
    abilityText: "每局游戏限一次，在夜晚时*，你可以选择一名玩家：他死亡，即使因为任何原因让他不会死亡。",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/assassin.png",
    inputKinds: ["none"],
    possibleOutcomes: ["Chosen player may die despite protection."],
    highRiskNotes: ["Assassin death bypasses protection once per game; do not auto-mark death.", "Other-night source reminder: 刺客可以选择一名玩家。如果他这么做了，标记那名玩家死亡，且刺客失去能力，之后的夜晚无需再唤醒刺客。"],
  }),
  role({
    id: "baron",
    name: "男爵",
    officialName: "baron",
    team: "minion",
    abilityText: "会有额外的外来者在场。[+2 外来者]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/baron.png",
    inputKinds: ["none"],
    setupImpact: ["Baron adds two Outsiders; excluded from first templates here."],
    highRiskNotes: ["Baron setup change is not automatic in this first template set."],
  }),
  role({
    id: "lilmonsta",
    name: "小怪宝",
    officialName: "lil_monsta",
    team: "demon",
    abilityText: "每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，可能会有一名玩家死亡。[+1爪牙]",
    iconPath: "https://oss.gstonegames.com/data_file/clocktower/role_icon/lil_monsta.png",
    inputKinds: ["none"],
    setupImpact: ["Lil Monsta uses no Demon player and adds one Minion; templates model this with a manual composition adjustment."],
    possibleOutcomes: ["One player may die each other night; babysitter is chosen by Minions."],
    highRiskNotes: ["Lil Monsta babysitter and night death are storyteller-confirmed; no automatic Demon state.", "First-night source reminder: 唤醒所有爪牙，允许他们以指向的方式决定谁照看小怪宝，但不能产生其他交流，否则会有非常糟糕的事情发生。", "Other-night source reminder: 唤醒所有爪牙，允许他们以指向的方式决定谁照看小怪宝，但不能产生其他交流，否则会有非常糟糕的事情发生。说书人选择一名玩家，那名玩家死亡。"],
  })
] as const
