import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "yu-zhe-huan-yan"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const yuZheHuanYanSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "organgrinder", "imp"], "bluffs": ["bountyhunter", "balloonist", "empath"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 7, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "fearmonger", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["poppygrower", "snakecharmer", "fortuneteller", "empath", "towncrier", "goblin", "imp"], "bluffs": ["bountyhunter", "balloonist", "clockmaker"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "barber", "organgrinder", "imp"], "bluffs": ["bountyhunter", "balloonist", "empath"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 8, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "drunk", "fearmonger", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "barber", "saint", "organgrinder", "imp"], "bluffs": ["bountyhunter", "balloonist", "empath"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 9, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "drunk", "heretic", "fearmonger", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "organgrinder", "fearmonger", "imp"], "bluffs": ["bountyhunter", "balloonist", "virgin"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 10, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "fearmonger", "goblin", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["poppygrower", "snakecharmer", "fortuneteller", "empath", "towncrier", "virgin", "artist", "goblin", "organgrinder", "imp"], "bluffs": ["bountyhunter", "balloonist", "clockmaker"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "barber", "organgrinder", "fearmonger", "imp"], "bluffs": ["bountyhunter", "balloonist", "virgin"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 11, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "drunk", "fearmonger", "goblin", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "barber", "saint", "organgrinder", "fearmonger", "imp"], "bluffs": ["bountyhunter", "balloonist", "virgin"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 12, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "drunk", "heretic", "fearmonger", "goblin", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["poppygrower", "snakecharmer", "fortuneteller", "empath", "towncrier", "virgin", "artist", "golem", "saint", "goblin", "organgrinder", "imp"], "bluffs": ["bountyhunter", "balloonist", "clockmaker"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "virgin", "artist", "organgrinder", "fearmonger", "goblin", "imp"], "bluffs": ["bountyhunter", "balloonist", "snakecharmer"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 13, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "clockmaker", "artist", "fearmonger", "goblin", "organgrinder", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "virgin", "artist", "barber", "organgrinder", "fearmonger", "goblin", "imp"], "bluffs": ["bountyhunter", "balloonist", "snakecharmer"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 14, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "clockmaker", "artist", "drunk", "fearmonger", "goblin", "organgrinder", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["poppygrower", "clockmaker", "undertaker", "pixie", "noble", "empath", "towncrier", "virgin", "artist", "barber", "saint", "organgrinder", "fearmonger", "goblin", "imp"], "bluffs": ["bountyhunter", "balloonist", "snakecharmer"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "identity", "count": 15, "style": "long-game", "roles": ["snakecharmer", "fortuneteller", "pixie", "noble", "undertaker", "empath", "towncrier", "clockmaker", "artist", "drunk", "heretic", "fearmonger", "goblin", "organgrinder", "vortex"], "bluffs": ["bountyhunter", "balloonist", "poppygrower"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["poppygrower", "snakecharmer", "fortuneteller", "empath", "towncrier", "virgin", "artist", "clockmaker", "undertaker", "golem", "saint", "goblin", "organgrinder", "fearmonger", "imp"], "bluffs": ["bountyhunter", "balloonist", "pixie"], "note": "Verified normal setup; Vigormortis, Baron, Bounty Hunter and Balloonist setup-changing paths stay manual. Organ Grinder, Vortox, Imp, Fearmonger, Goblin, Barber, Heretic, Virgin and Snake Charmer outcomes remain ST-confirmed."}),
]
