import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20757_59931.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: "Man Tian Guo Hai", setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const manTianGuoHaiRoles = [
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not compute candidates from hidden state without ST confirmation."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Learns one in-play Townsfolk; may later gain that ability after madness and death condition."], "stateChanges": ["May gain another Townsfolk ability later."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness and later ability gain require ST confirmation."]}),
  role({"id": "balloonist", "name": "气球驾驶员", "officialName": "Balloonist", "team": "townsfolk", "abilityText": "每个夜晚，你会得知一名与上个夜晚得知的玩家角色类型不同的玩家。[+0~1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/balloonist.png", "inputKinds": ["players", "role"], "setupImpact": ["每个夜晚，你会得知一名与上个夜晚得知的玩家角色类型不同的玩家。[+0~1外来者]", "May add one Outsider (+0~1, storyteller's choice)."], "possibleOutcomes": ["Learns one player each night whose character type differs from the previous night's player."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Tracks the character type shown last night; default templates avoid setup-changing path."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns whether either of two chosen players is a Demon; red herring may register as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Red herring and registration anomalies require ST confirmation."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns number of dead evil players."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Recluse and registration effects remain ST-confirmed."]}),
  role({"id": "mathematician", "name": "数学家", "officialName": "Mathematician", "team": "townsfolk", "abilityText": "每个夜晚，你会得知有多少名玩家的能力因为其他角色的能力而未正常生效。(从上个黎明到你被唤醒时）", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mathematician.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns how many abilities malfunctioned due to another character since dawn."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Count depends on ST judgement of abnormal ability function."]}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Receives two private statements, one true and one false."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["One statement is true and one is false: {infoA}; {infoB}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Statements are authored by ST."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-apply this role result; storyteller confirms before writing authority state.", "Seamstress learns whether two selected players share alignment; answer stays ST-confirmed."]}),
  role({"id": "huntsman", "name": "巡山人", "officialName": "Huntsman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名存活的玩家：如果你选中了落难少女，她会变成一个不在场的镇民角色。[+落难少女]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/huntsman.png", "inputKinds": ["player", "role"], "setupImpact": ["每局游戏限一次，在夜晚时，你可以选择一名存活的玩家：如果你选中了落难少女，她会变成一个不在场的镇民角色。[+落难少女]", "Adds Damsel."], "possibleOutcomes": ["May transform Damsel into an out-of-play Townsfolk."], "stateChanges": [], "identityChanges": ["Damsel may become an out-of-play Townsfolk."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Huntsman because it adds Damsel and can change identity."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Once per game, receives ST advice that helps their team."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice: {text}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Advice is ST-authored, not generated as authority by AI."]}),
  role({"id": "slayer", "name": "猎手", "officialName": "Slayer", "team": "townsfolk", "abilityText": "每局游戏限一次，你可以在白天时公开选择一名玩家：如果他是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/slayer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["If chosen target is the Demon, they die."], "stateChanges": ["May cause Demon death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Public shot result and death require ST confirmation."]}),
  role({"id": "ravenkeeper", "name": "守鸦人", "officialName": "Ravenkeeper", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，你会被唤醒，然后你要选择一名玩家：你会得知他的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/ravenkeeper.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-apply this role result; storyteller confirms before writing authority state.", "Ravenkeeper death information is chosen after they die at night; answer stays ST-confirmed."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Gains ability of the last executed player; poisoned if that player was evil until next good execution death."], "stateChanges": ["May gain ability; may become poisoned."], "identityChanges": ["Ability source changes but character remains Cannibal."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Track ability source and poison end manually."]}),
  role({"id": "mutant", "name": "畸形秀演员", "officialName": "Mutant", "team": "outsider", "abilityText": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mutant.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["May be executed for being mad about being an Outsider."], "stateChanges": ["May be executed."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness and execution are ST discretion."]}),
  role({"id": "damsel", "name": "落难少女", "officialName": "Damsel", "team": "outsider", "abilityText": "所有爪牙都知道落难少女在场。每局游戏限一次，任意爪牙可以公开猜测你是落难少女，如果猜对，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/damsel.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Minions know Damsel is in play; once per game a Minion may guess Damsel to make good lose."], "stateChanges": ["May trigger good-team loss if guessed correctly."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-declare loss; ST confirms guess and result."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["On death, publicly chooses an alive player; if evil, their team loses."], "stateChanges": ["May trigger team loss."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-declare loss."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。"], "possibleOutcomes": ["Player thinks they are a Townsfolk but is actually Drunk."], "stateChanges": ["Ability does not function."], "identityChanges": ["Actual and perceived character differ."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Hidden identity; default templates avoid this role."]}),
  role({"id": "golem", "name": "魔像", "officialName": "Golem", "team": "outsider", "abilityText": "每局游戏你只能发起提名一次。当你发起提名时，如果被你提名的玩家不是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/golem.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Can nominate only once; if nominated player is not Demon, they die."], "stateChanges": ["May cause nomination death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Nomination count and death require ST confirmation."]}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "Cerenovus", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Chosen player must be mad as a chosen good character tomorrow day and night."], "stateChanges": ["May impose madness; may lead to execution."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["You are made mad as {roleName}; prove it or something bad may happen."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness prompt and consequences are ST-confirmed."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["May become the Demon if Demon dies with five or more players alive."], "stateChanges": [], "identityChanges": ["May become the Demon."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Demon replacement is manual and ST-confirmed."]}),
  role({"id": "baron", "name": "男爵", "officialName": "Baron", "team": "minion", "abilityText": "会有额外的外来者在场。[+2 外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/baron.png", "inputKinds": ["none"], "setupImpact": ["会有额外的外来者在场。[+2 外来者]", "Adds two Outsiders."], "possibleOutcomes": ["Adds two Outsiders during setup."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Baron setup-changing path."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "Marionette", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["none"], "setupImpact": ["你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]"], "possibleOutcomes": ["Player thinks they are good but is actually evil Minion."], "stateChanges": [], "identityChanges": ["Actual and perceived character differ."], "teamChanges": ["Actual alignment is evil while perceived role is good."], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Must neighbor Demon; high-player templates using it need ST adjacency check."]}),
  role({"id": "fanggu", "name": "方古", "officialName": "Fang Gu", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fang_gu.png", "inputKinds": ["player"], "setupImpact": ["每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "Adds one Outsider."], "possibleOutcomes": ["Kills each night; first Outsider killed this way may become evil Fang Gu while old Fang Gu dies."], "stateChanges": ["May cause death."], "identityChanges": ["An Outsider may become Fang Gu."], "teamChanges": ["Converted Outsider becomes evil."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Jump and old Demon death are manual; default templates avoid Fang Gu."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Kills each night; self-kill may make a Minion the new Imp."], "stateChanges": ["May cause death."], "identityChanges": ["Minion may become new Imp."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Self-kill handoff requires ST confirmation."]}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "No Dashii", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Kills each night; neighboring Townsfolk are poisoned."], "stateChanges": ["May cause death; neighboring Townsfolk may be poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Neighbor poisoning depends on seats/registration; no auto-poison or kill."]}),
] as const
