import type { SetupRule } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20908_17210.json"
const reviewedAt = '2026-07-21'

export const wenWuShuangQuanSetupRules: readonly SetupRule[] = [
  {
    id: "wen-wu-shuang-quan-drunk-reminder",
    roleId: "drunk",
    summary: "Drunk is hidden and thinks they are a Townsfolk; assign and verify manually during setup.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-balloonist-reminder",
    roleId: "balloonist",
    summary: "Balloonist setup and category-tracking information remain storyteller-confirmed.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-godfather-reminder",
    roleId: "godfather",
    summary: "Godfather may add or remove one Outsider and wakes on Outsider day death; excluded from first templates here.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-sailor-reminder",
    roleId: "sailor",
    summary: "Sailor drunkenness and death prevention require storyteller confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-cannibal-reminder",
    roleId: "cannibal",
    summary: "Cannibal gains executed player ability and may be poisoned by evil execution; ability source remains manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-barber-reminder",
    roleId: "barber",
    summary: "Barber death may let Demon swap two characters; identity changes require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-lleech-reminder",
    roleId: "lleech",
    summary: "Lleech host poison and Demon death dependency require manual host tracking.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-philosopher-reminder",
    roleId: "philosopher",
    summary: "Philosopher chosen ability may make an in-play good role drunk; never auto-apply the ability or drunk state.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-professor-reminder",
    roleId: "professor",
    summary: "Professor resurrection is a manual state-change candidate; do not auto-revive.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-gambler-reminder",
    roleId: "gambler",
    summary: "Gambler wrong guess may kill the Gambler; result is calculated as advice then confirmed.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-lycanthrope-reminder",
    roleId: "lycanthrope",
    summary: "Lycanthrope may kill a good target and suppress later night deaths; death-prevention chain remains manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-fool-reminder",
    roleId: "fool",
    summary: "Fool first death prevention is a reminder; do not auto-prevent death.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-lunatic-reminder",
    roleId: "lunatic",
    summary: "Lunatic false Demon information and Demon knowledge remain manual reminders.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-acrobat-reminder",
    roleId: "acrobat",
    summary: "Acrobat death due to drunk/poisoned good neighbor is a reminder; storyteller confirms.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-poisoner-reminder",
    roleId: "poisoner",
    summary: "Poisoned state is a candidate result until storyteller confirms it.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-assassin-reminder",
    roleId: "assassin",
    summary: "Assassin death bypasses protection once per game; do not auto-mark death.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-pithag-reminder",
    roleId: "pithag",
    summary: "Pit-Hag role changes and Demon creation produce storyteller-chosen death outcomes only after confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-imp-reminder",
    roleId: "imp",
    summary: "Imp self-kill may pass Demon to a Minion; identity and death changes require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-pukka-reminder",
    roleId: "pukka",
    summary: "Pukka poisons current target and kills previous poisoned target; chain state must be checked manually.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "wen-wu-shuang-quan-shabaloth-reminder",
    roleId: "shabaloth",
    summary: "Shabaloth may kill two players and regurgitate one; all death/revival states are manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
]
