import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20755_59933.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: "Yu Gai Mi Zhang", setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const yuGaiMiZhangRoles = [
  role({"id": "librarian", "name": "图书管理员", "officialName": "Librarian", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知两名玩家和一个外来者角色：这两名玩家之一是该角色（或者你会得知没有外来者在场）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/librarian.png", "inputKinds": ["players", "role"], "setupImpact": [], "possibleOutcomes": ["Learns two players and one Outsider role, or that no Outsider is in play."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["One of {seatA} or {seatB} is {roleName}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Outsider information can be affected by registration; ST confirms shown players/role."]}),
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not compute candidates from hidden state without ST confirmation."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Learns one in-play Townsfolk; may later gain that ability after madness and death condition."], "stateChanges": ["May gain another Townsfolk ability later."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness and later ability gain require ST confirmation."]}),
  role({"id": "balloonist", "name": "气球驾驶员", "officialName": "Balloonist", "team": "townsfolk", "abilityText": "每个夜晚，你会得知一名与上个夜晚得知的玩家角色类型不同的玩家。[+0~1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/balloonist.png", "inputKinds": ["players", "role"], "setupImpact": ["每个夜晚，你会得知一名与上个夜晚得知的玩家角色类型不同的玩家。[+0~1外来者]", "Storyteller may add zero or one Outsider."], "possibleOutcomes": ["Learns one player each night whose character type differs from the previous night's shown player; if drunk or poisoned, may be shown the same type."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Tracks the character type shown on the previous night; default templates avoid setup-changing path."]}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "Chambermaid", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Record this role choice, result and player-facing information."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Chambermaid result stays a storyteller-confirmed suggestion."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns whether either of two chosen players is a Demon; red herring may register as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Red herring and registration anomalies require ST confirmation."]}),
  role({"id": "general", "name": "将军", "officialName": "General", "team": "townsfolk", "abilityText": "每个夜晚，你会得知说书人认为哪个阵营当前更有优势（善良/邪恶/均势）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/general.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns ST view of which team is currently advantaged: good, evil, or even."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Current advantage: {text}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "General answer is ST judgement, not engine calculation."]}),
  role({"id": "sailor", "name": "水手", "officialName": "Sailor", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：你或他之一会醉酒直到下个黄昏。你不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sailor.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses an alive player; Sailor or target is drunk until dusk.", "Sailor cannot die."], "stateChanges": ["Sailor or target may be drunk until dusk.", "Sailor may survive death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Drunken target and death prevention are ST-confirmed."]}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Receives two private statements, one true and one false."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["One statement is true and one is false: {infoA}; {infoB}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Statements are authored by ST."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-apply this role result; storyteller confirms before writing authority state.", "Seamstress learns whether two selected players share alignment; answer stays ST-confirmed."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Once per game, chooses a good character and gains that ability; if in play, that character is drunk."], "stateChanges": ["May make an in-play chosen good character drunk."], "identityChanges": ["Philosopher gains another character ability but remains Philosopher."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not create a per-role state machine; record chosen ability and ST-confirmed consequences."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Once per game, receives ST advice that helps their team."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice: {text}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Advice is ST-authored, not automatic AI authority."]}),
  role({"id": "ravenkeeper", "name": "守鸦人", "officialName": "Ravenkeeper", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，你会被唤醒，然后你要选择一名玩家：你会得知他的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/ravenkeeper.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-apply this role result; storyteller confirms before writing authority state.", "Ravenkeeper death information is chosen after they die at night; answer stays ST-confirmed."]}),
  role({"id": "barber", "name": "理发师", "officialName": "Barber", "team": "outsider", "abilityText": "如果你死亡，在当晚恶魔可以选择两名玩家（不能选择其他恶魔）交换角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/barber.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["If Barber dies, Demon may choose two players to swap characters."], "stateChanges": ["May create, prevent, delay, redirect or react to death/execution, poison/drunk, or life state."], "identityChanges": ["Two non-other-Demon players may swap characters."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Character swap requires Demon choice and ST confirmation."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。"], "possibleOutcomes": ["Player thinks they are a Townsfolk but is actually Drunk."], "stateChanges": ["Ability does not function."], "identityChanges": ["Actual and perceived character differ."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Hidden identity; default templates avoid this role."]}),
  role({"id": "mutant", "name": "畸形秀演员", "officialName": "Mutant", "team": "outsider", "abilityText": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mutant.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["May be executed for being mad about being an Outsider."], "stateChanges": ["May be executed."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness and execution are ST discretion."]}),
  role({"id": "sweetheart", "name": "心上人", "officialName": "Sweetheart", "team": "outsider", "abilityText": "当你死亡时，会有一名玩家开始醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sweetheart.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["When Sweetheart dies, one player becomes drunk from now on."], "stateChanges": ["One player may become permanently drunk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Drunk target is chosen/confirmed by ST."]}),
  role({"id": "eviltwin", "name": "镜像双子", "officialName": "Evil Twin", "team": "minion", "abilityText": "你与一名对立阵营的玩家互相知道对方是什么角色。如果其中善良玩家被处决，邪恶阵营获胜。如果你们都存活，善良阵营无法获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/evil_twin.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Evil Twin and opposing good twin know each other and characters; if the good twin is executed while the Evil Twin is alive, evil wins—a dead Evil Twin loses this ability, so executing the good twin after the Evil Twin's death does not make evil win; while both live, good cannot win."], "stateChanges": ["May block good victory while both twins live.", "May trigger evil win if good twin is executed while the Evil Twin is alive."], "identityChanges": [], "teamChanges": ["Pairs players of opposite alignments."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-declare victory; twin pairing and execution result require ST confirmation."]}),
  role({"id": "goblin", "name": "哥布林", "officialName": "Goblin", "team": "minion", "abilityText": "如果你在被提名后公开声明自己是哥布林且在那个白天被处决，你的阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/goblin.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If nominated, claims Goblin and is executed that day, their team wins."], "stateChanges": ["May trigger team win on execution."], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-declare victory; claim timing and execution require ST confirmation."]}),
  role({"id": "widow", "name": "寡妇", "officialName": "Widow", "team": "minion", "abilityText": "在你的首个夜晚，你能查看魔典并选择一名玩家：他中毒。随后，始终会有一名善良玩家知道寡妇在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/widow.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["On first night, sees grimoire and poisons one player; one good player learns Widow is in play."], "stateChanges": ["Chosen player is poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["A Widow is in play."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Poison target and warning recipient are manual; do not expose full grimoire through UI."]}),
  role({"id": "fearmonger", "name": "恐惧之灵", "officialName": "Fearmonger", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：如果你提名他且他被处决，他的阵营落败。当你首次选择或更换目标时，所有玩家都会得知你选择了新的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fearmonger.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses a player; if Fearmonger nominates and executes them, their team loses. All players learn when target changes."], "stateChanges": ["May trigger target team loss if nominated and executed by Fearmonger."], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": ["Fearmonger has chosen a new player."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Target change announcement and loss condition require ST confirmation."]}),
  role({"id": "lilmonsta", "name": "小怪宝", "officialName": "Lil' Monsta", "team": "demon", "abilityText": "每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，可能会有一名玩家死亡。[+1爪牙]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lil_monsta.png", "inputKinds": ["none"], "setupImpact": ["每个夜晚，所有爪牙要秘密决定由哪名玩家来照看小怪宝并且“是恶魔”。每个夜晚*，可能会有一名玩家死亡。[+1爪牙]", "Adds one Minion and no Demon character player."], "possibleOutcomes": ["Minions secretly choose a babysitter who is the Demon; each night one player may die."], "stateChanges": ["Babysitter is treated as Demon; one player may die each night.", "If the babysitting player dies, the Demon is dead: the game ends and the good team wins."], "identityChanges": ["Demon responsibility moves to chosen babysitter."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Lil Monsta; babysitter and deaths remain manual.", "If the current babysitter dies (even a good babysitter, e.g. by execution), remind the ST to check game end: the Demon is dead and good wins."]}),
  role({"id": "fanggu", "name": "方古", "officialName": "Fang Gu", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fang_gu.png", "inputKinds": ["player"], "setupImpact": ["每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "Adds one Outsider."], "possibleOutcomes": ["Kills each night; first Outsider killed this way may become evil Fang Gu while old Fang Gu dies."], "stateChanges": ["May cause death."], "identityChanges": ["Outsider may become Fang Gu."], "teamChanges": ["Converted Outsider becomes evil."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Jump and old Demon death are manual; default templates avoid Fang Gu."]}),
  role({"id": "lleech", "name": "痢蛭", "officialName": "Lleech", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。在你的首个夜晚，你要选择一名存活的玩家：他中毒，只有他死亡时你才会一同死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lleech.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["First night chooses a host who is poisoned; each night kills a player; Lleech dies only if host dies."], "stateChanges": ["Host is poisoned.", "Chosen target may die.", "Lleech death is linked to host death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Host poison and death link require manual tracking; no automatic death."]}),
] as const
