import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21531_71622.json"
const rolesSourceUrl = "https://clocktower.gstonegames.com/ct/grimoireRoleJson/"
const reviewedAt = "2026-07-22"

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Shi Yan Jiao Chi', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const shiYanJiaoChiRoles = [
  role({"id": "ogre", "name": "食人魔", "officialName": "custom", "team": "outsider", "abilityText": "在你的首个夜晚，你要选择除你以外的一名玩家：你转变为他的阵营，即使你已醉酒或中毒，但你不知道你转变后的阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202405/c_0102424156171_21d2f372.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Choose one non-self player as the alignment anchor."], "stateChanges": ["Alignment changes immediately according to target alignment."], "identityChanges": ["No role change."], "teamChanges": ["Good target makes Ogre good; evil target makes Ogre evil."], "playerMessageTemplates": ["You chose that player; ST records your alignment."], "highRiskNotes": ["Check current target alignment; drunk/poisoned does not stop Ogre alignment change."], "setupImpact": []}),
  role({"id": "qintianjian", "name": "钦天监", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知离你最近的邪恶玩家位于你的哪一侧（左/右/相同）。如果与你邻近的玩家中有邪恶阵营，你会得知错误信息。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4484677694761_241d43f7.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Tell left, right, or same side."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Check current evil seats around the table."], "playerMessageTemplates": ["Nearest evil player is on: left / right / same."], "highRiskNotes": ["If neighboring players include evil, this ability gets false info."], "setupImpact": []}),
  role({"id": "steward", "name": "事务官", "officialName": "custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名善良玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202305/c_9219342584861_b889322f.jpg", "inputKinds": ["none"], "possibleOutcomes": ["Tell one good player."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Target must be good in the confirmed current state."], "playerMessageTemplates": ["You learn that seat X is good."], "highRiskNotes": ["AI only suggests a draft; ST must confirm before changing authority state."], "setupImpact": []}),
  role({"id": "tixingguan", "name": "提刑官", "officialName": "custom", "team": "townsfolk", "abilityText": "在你首次提名玩家后，你会在当晚得知他的角色。外来者会被你的能力当作爪牙或恶魔角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_7402377694761_cd9eb282.jpg", "inputKinds": ["role", "text"], "possibleOutcomes": ["At night, tell the role of the first nominated player."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn that the nominated player is role X."], "highRiskNotes": ["Outsider targets are treated as Minion or Demon roles by this ability."], "setupImpact": []}),
  role({"id": "empath", "name": "共情者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["number"], "possibleOutcomes": ["Tell 0, 1, or 2."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Count evil players among two living neighbors."], "playerMessageTemplates": ["Your living neighbors include 0 / 1 / 2 evil players."], "highRiskNotes": ["Skip dead players before finding living neighbors."], "setupImpact": []}),
  role({"id": "dreamer", "name": "筑梦师", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你及旅行者以外的一名玩家：你会得知一个善良角色和一个邪恶角色，该玩家是其中一个角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/dreamer.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Give one good role and one evil role; target is one of them."], "stateChanges": [], "identityChanges": [], "teamChanges": ["One candidate should match real role/alignment logic unless false info applies."], "playerMessageTemplates": ["This player is one of: good role / evil role."], "highRiskNotes": ["Cannot choose self or Traveler; check drunk/poison/false info."], "setupImpact": []}),
  role({"id": "cannibal", "name": "食人族", "officialName": "custom", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "possibleOutcomes": ["Gain the ability of the last player executed."], "stateChanges": ["If executed player was evil, Cannibal is poisoned until a good player is executed."], "identityChanges": [], "teamChanges": ["Check the alignment of latest executed player."], "playerMessageTemplates": [], "highRiskNotes": ["Source JSON duplicated Cannibal; this pack collapses it to one role."], "setupImpact": []}),
  role({"id": "yinluren", "name": "引路人", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择至多三名玩家：你会得知今晚是否有邪恶玩家的能力选择或影响了他们之中的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_2147287694761_01761fcb.jpg", "inputKinds": ["players"], "possibleOutcomes": ["Tell whether evil ability chose or affected one selected target tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Check evil ability choice and effect scope."], "playerMessageTemplates": ["Did evil ability choose or affect one of them tonight: yes / no."], "highRiskNotes": ["Up to three targets; include indirect effects as well as direct choices."], "setupImpact": []}),
  role({"id": "snakecharmer", "name": "舞蛇人", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：如果你选中了恶魔，你和他交换角色和阵营，然后他中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/snake_charmer.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["No effect if not Demon; swap role and alignment if target is Demon."], "stateChanges": ["Old Demon becomes poisoned new Snake Charmer."], "identityChanges": ["Snake Charmer and target Demon swap roles."], "teamChanges": ["Both alignments change with swapped roles."], "playerMessageTemplates": ["Your chosen player is / is not the Demon; if swapped, ST informs both sides."], "highRiskNotes": ["Swap changes identity and alignment immediately; old Demon becomes poisoned new Snake Charmer."], "setupImpact": []}),
  role({"id": "gossip", "name": "造谣者", "officialName": "custom", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "possibleOutcomes": ["If public statement is true, a player may die tonight."], "stateChanges": ["May cause extra death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Record the public statement and verify it tonight."], "highRiskNotes": ["AI may help evaluate truth and death candidate, but cannot kill automatically."], "setupImpact": []}),
  role({"id": "qianke", "name": "掮客", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名存活玩家：如果他们阵营相同，今晚任何玩家使用自身能力选择他们之一作为目标时，改为选中另一名玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_2978127816071_ab841bc9.jpg", "inputKinds": ["players"], "possibleOutcomes": ["If two living targets share alignment, relevant targets may be redirected tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": ["Check both targets current alignment."], "playerMessageTemplates": [], "highRiskNotes": ["This affects other ability targets; record this step for later resolution."], "setupImpact": []}),
  role({"id": "monk", "name": "僧侣", "officialName": "custom", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Protect one other player from Demon negative effects."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Protects against Demon negative effects, not every death or Minion ability."], "setupImpact": []}),
  role({"id": "bingbi", "name": "秉笔", "officialName": "custom", "team": "townsfolk", "abilityText": "如果你在白天死亡，当晚你会得知一名善良玩家。如果你在夜晚死亡，当晚你会得知一名邪恶玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_5918227760171_7f310c1b.jpg", "inputKinds": ["none"], "possibleOutcomes": ["If died by day, learn a good player; if died by night, learn an evil player."], "stateChanges": ["Trigger depends on day/night death timing."], "identityChanges": [], "teamChanges": ["Given player must match current alignment."], "playerMessageTemplates": ["You learn that seat X is good / evil."], "highRiskNotes": ["Confirm the day/night label before choosing good or evil info."], "setupImpact": []}),
  role({"id": "ranfangfangzhu", "name": "染坊坊主", "officialName": "custom", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，恶魔的能力变成“每个夜晚*，可能会有一名玩家死亡。”", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202404/c_0616062943171_bbdbbb4c.jpg", "inputKinds": ["role"], "possibleOutcomes": ["If killed at night, Demon ability becomes may-kill-one-player each night."], "stateChanges": ["Changes Demon kill cadence after night death."], "identityChanges": ["No Demon identity change; only ability effect changes."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only night death triggers this ability."], "setupImpact": []}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "custom", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["role"], "possibleOutcomes": ["Player thinks they are a Townsfolk, but the ability is inactive."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Send the false Townsfolk identity, not Drunk."], "highRiskNotes": ["Track false identity privately; do not expose it to player logs."], "setupImpact": []}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "custom", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["When learning death, publicly choose a living player; if evil, good loses."], "stateChanges": ["Death triggers public choice."], "identityChanges": [], "teamChanges": ["Check selected player current alignment."], "playerMessageTemplates": ["You must publicly choose a living player."], "highRiskNotes": ["Win/loss remains ST authority; AI only warns."], "setupImpact": []}),
  role({"id": "acrobat", "name": "杂技演员", "officialName": "custom", "team": "outsider", "abilityText": "每个夜晚*，如果与你邻近的存活善良玩家之一醉酒或中毒，你死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/acrobat.png", "inputKinds": ["none"], "possibleOutcomes": ["If a living good neighbor is drunk or poisoned, Acrobat dies."], "stateChanges": ["May die at night after checking neighbor state."], "identityChanges": [], "teamChanges": ["Only living good neighbors are checked."], "playerMessageTemplates": [], "highRiskNotes": ["Skip dead players, then check living good neighbor drunk/poison state."], "setupImpact": []}),
  role({"id": "godfather", "name": "教父", "officialName": "custom", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Learn in-play Outsiders; if Outsider died by day, choose a player to die tonight."], "stateChanges": ["May cause extra death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["In-play Outsiders are: roles / none."], "highRiskNotes": ["Templates using Godfather must explicitly record Outsider count adjustment."], "setupImpact": ["Outsider count may increase or decrease by 1.", "Godfather learns in-play Outsider roles."]}),
  role({"id": "widow", "name": "寡妇", "officialName": "custom", "team": "minion", "abilityText": "在你的首个夜晚，你能查看魔典并选择一名玩家：他中毒。随后，始终会有一名善良玩家知道寡妇在场。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/widow.png", "inputKinds": ["player"], "possibleOutcomes": ["View Grimoire and poison one player; one good player learns Widow is in play."], "stateChanges": ["Chosen target is poisoned."], "identityChanges": [], "teamChanges": ["ST chooses which good player learns Widow is in play."], "playerMessageTemplates": ["You know that Widow is in play."], "highRiskNotes": ["Grimoire view is sensitive; never send full state to player side."], "setupImpact": []}),
  role({"id": "summoner", "name": "召唤师", "officialName": "custom", "team": "minion", "abilityText": "在首个夜晚，你会得知三个伪装。在第三个夜晚，你要选择一名玩家：他变成由你选择的邪恶恶魔。[无恶魔在场]\n\n", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_2685000701171_6b776d07.jpg", "inputKinds": ["player", "role"], "possibleOutcomes": ["On night three choose a player to become the selected evil Demon."], "stateChanges": [], "identityChanges": ["Night three target becomes Demon role."], "teamChanges": ["Night three target becomes evil."], "playerMessageTemplates": ["You choose the player who becomes the selected Demon."], "highRiskNotes": ["High-risk setup-changing path; first normal templates only keep a reminder."], "setupImpact": ["No Demon starts in play.", "On night three a player becomes an evil Demon."]}),
  role({"id": "eviltwin", "name": "镜像双子", "officialName": "custom", "team": "minion", "abilityText": "你与一名对立阵营的玩家互相知道对方是什么角色。如果其中善良玩家被处决，邪恶阵营获胜。如果你们都存活，善良阵营无法获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/evil_twin.png", "inputKinds": ["role"], "possibleOutcomes": ["Pair with opposite-alignment player; good twin execution can make evil win."], "stateChanges": ["May affect win condition."], "identityChanges": [], "teamChanges": ["Twin pair must have opposite alignments."], "playerMessageTemplates": ["You and seat X are Evil Twin pair; their role is X."], "highRiskNotes": ["Win/loss remains ST authority; AI only warns about twin condition."], "setupImpact": []}),
  role({"id": "hundun", "name": "混沌", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式杀死了一名与你邻近的镇民玩家，所有善良玩家会中毒直到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9149178608961_89693def.jpg", "inputKinds": ["player"], "possibleOutcomes": ["Choose one player to die; if adjacent Townsfolk is killed, good players are poisoned until next dusk."], "stateChanges": ["Target dies; may poison all good players."], "identityChanges": [], "teamChanges": ["Check whether target is adjacent Townsfolk."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-apply mass poison; generate a confirmation draft only."], "setupImpact": []}),
  role({"id": "taotie", "name": "饕餮", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择任意数量的非旅行者玩家或一名旅行者玩家：如果他们的角色类型均不相同，他们死亡。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_5897997694761_fbe1f00c.jpg", "inputKinds": ["players", "role", "number"], "possibleOutcomes": ["Choose any number of non-Travelers or one Traveler; if role types all differ, they die."], "stateChanges": ["May cause multi-target death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Not used by first normal templates; if used, also apply Outsider count adjustment."], "setupImpact": ["Add 1 Outsider."]}),
  role({"id": "vortox", "name": "涡流", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。镇民玩家的能力都会产生错误信息。如果白天没人被处决，邪恶阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vortox.png", "inputKinds": ["player"], "possibleOutcomes": ["Choose one player to die; Townsfolk abilities receive false info."], "stateChanges": ["Target dies; no execution during day affects win condition."], "identityChanges": [], "teamChanges": ["All Townsfolk info abilities must be false."], "playerMessageTemplates": [], "highRiskNotes": ["AI can remind false info, but cannot decide win/loss automatically."], "setupImpact": []}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["players"], "possibleOutcomes": ["Choose one player to die; nearest two Townsfolk are poisoned."], "stateChanges": ["Target dies; nearest Townsfolk are poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Check nearest Townsfolk by seat and current living state."], "setupImpact": []}),
] as const satisfies readonly SmartRoleDefinition[]
