import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20753_59934.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Yao Wu Yin Xin', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const yaoWuYinXinRoles = [
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not compute candidates from hidden state without ST confirmation."]}),
  role({"id": "clockmaker", "name": "钟表匠", "officialName": "Clockmaker", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知恶魔与爪牙之间最近的距离。（邻座的玩家距离为1）", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/clockmaker.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns Demon distance to nearest Minion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Distance result depends on confirmed Demon/Minion positions and registration."]}),
  role({"id": "empath", "name": "共情者", "officialName": "Empath", "team": "townsfolk", "abilityText": "每个夜晚，你会得知与你邻近的两名存活的玩家中邪恶玩家的数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/empath.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns number of evil living neighbors."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Neighbor evil count depends on registration and death state; ST confirms."]}),
  role({"id": "general", "name": "将军", "officialName": "General", "team": "townsfolk", "abilityText": "每个夜晚，你会得知说书人认为哪个阵营当前更有优势（善良/邪恶/均势）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/general.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns ST judgement: good advantage, evil advantage, or even."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Current advantage: {text}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "General answer is ST judgement, not engine calculation."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns whether either chosen player registers as Demon; red herring may register as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Red herring and registration anomalies require ST confirmation."]}),
  role({"id": "mathematician", "name": "数学家", "officialName": "Mathematician", "team": "townsfolk", "abilityText": "每个夜晚，你会得知有多少名玩家的能力因为其他角色的能力而未正常生效。(从上个黎明到你被唤醒时）", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mathematician.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns how many players had abilities malfunction since dusk due to another character ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Malfunction count requires ST interpretation of drunk/poison/ability interactions."]}),
  role({"id": "monk", "name": "僧侣", "officialName": "Monk", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Protects one player from Demon killing until dusk."], "stateChanges": ["Protected player may not die to Demon attack."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Protection only blocks Demon kill paths that ST confirms."]}),
  role({"id": "gossip", "name": "造谣者", "officialName": "Gossip", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If public statement is true, one player may die that night."], "stateChanges": ["May cause a night death if statement is true."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Truth judgement and death choice are ST-confirmed."]}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Once per game, learns whether two chosen players are same alignment."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Same-alignment answer stays ST-confirmed."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Once per game, receives ST-authored advice that helps their team."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice: {text}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Advice is ST-authored, not automatic AI authority."]}),
  role({"id": "artist", "name": "艺术家", "officialName": "Artist", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以私下询问说书人一个是非问题，你会得知该问题的答案。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/artist.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Once per game, asks any yes/no question and receives ST answer."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Answer: {yesNo}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Answer is ST-authored and may consider registration/false info."]}),
  role({"id": "juggler", "name": "杂耍艺人", "officialName": "Juggler", "team": "townsfolk", "abilityText": "在你的首个白天，你可以公开猜测任意玩家的角色最多五次。在当晚，你会得知猜测正确的角色数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/juggler.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Day ability guess can produce a number at night; result is ST-confirmed."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Juggler result: {number}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Day claims and night number are manual records."]}),
  role({"id": "sage", "name": "贤者", "officialName": "Sage", "team": "townsfolk", "abilityText": "如果恶魔杀死了你，在当晚你会被唤醒并得知两名玩家，其中一名是杀死你的那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sage.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["If killed by Demon at night, learns two players with one being that Demon."], "stateChanges": ["Triggers information only after Demon night kill."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["One of {seatA} or {seatB} is the Demon."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Only Demon night kill should trigger; ST confirms."]}),
  role({"id": "snitch", "name": "告密者", "officialName": "Snitch", "team": "outsider", "abilityText": "爪牙会在其首个夜晚得知三个不在场的善良角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/snitch.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Minions learn three not-in-play characters."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Minion bluffs: {roleA}, {roleB}, {roleC}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Minion bluff information is setup-facing and not a player inbox."]}),
  role({"id": "acrobat", "name": "杂技演员", "officialName": "Acrobat", "team": "outsider", "abilityText": "每个夜晚*，如果与你邻近的存活善良玩家之一醉酒或中毒，你死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/acrobat.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["May die if neighboring good player is drunk or poisoned."], "stateChanges": ["May die from neighboring good drunk/poisoned player."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Death trigger depends on neighboring good drunk/poison state; ST confirms."]}),
  role({"id": "klutz", "name": "呆瓜", "officialName": "Klutz", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家：如果他是邪恶的，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/klutz.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["On death, chooses a player; if evil, their team loses."], "stateChanges": ["May trigger own team loss after death choice."], "identityChanges": [], "teamChanges": ["Wrong death choice can make their team lose."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-declare loss; death choice and alignment are ST-confirmed."]}),
  role({"id": "moonchild", "name": "月之子", "officialName": "Moonchild", "team": "outsider", "abilityText": "当你得知你死亡时，你要公开选择一名存活的玩家。如果他是善良的，在当晚他会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/moonchild.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["On death, chooses a good player; if correct, that player dies tonight."], "stateChanges": ["May cause chosen good player to die tonight."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Death trigger requires dead Moonchild and good target; ST confirms."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["none"], "setupImpact": ["在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]"], "possibleOutcomes": ["Knows out-of-play Outsiders; if an Outsider died today, may kill tonight; setup changes Outsider count."], "stateChanges": ["May add/remove Outsiders during setup and kill after Outsider death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Setup count and extra kill stay manual; default templates avoid this role."]}),
  role({"id": "pithag", "name": "麻脸巫婆", "officialName": "Pit Hag", "team": "minion", "abilityText": "每个夜晚*，你要选择一名玩家和一个角色，如果该角色不在场，他变成该角色。如果因此创造了一个恶魔，当晚的死亡由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pit-hag.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["May change a player into another character; Demon change may cause arbitrary death."], "stateChanges": ["May change character and possibly cause arbitrary death when Demon changes."], "identityChanges": ["Target may become another character."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Character changes and arbitrary death are manual; no per-role state machine."]}),
  role({"id": "assassin", "name": "刺客", "officialName": "Assassin", "team": "minion", "abilityText": "每局游戏限一次，在夜晚时*，你可以选择一名玩家：他死亡，即使因为任何原因让他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/assassin.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Once per game, kills a player even if protected."], "stateChanges": ["May kill through protection once."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Once-per-game kill through protection is manual."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["May become Demon if Demon dies with enough players alive."], "stateChanges": ["May become Demon."], "identityChanges": ["Scarlet Woman may become Demon."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Demon replacement is manual; no automatic role/identity change."]}),
  role({"id": "pukka", "name": "普卡", "officialName": "Pukka", "team": "demon", "abilityText": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pukka.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses a player to poison; previously poisoned player dies."], "stateChanges": ["Chosen player poisoned; previous poisoned target dies."], "identityChanges": ["Poison/death cadence may obscure Demon responsibility."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Poison/death sequence requires manual tracking."]}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "No Dashii", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Townsfolk neighbors are poisoned."], "stateChanges": ["Neighboring Townsfolk are poisoned."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Poison range uses seating and Townsfolk identity; ST confirms."]}),
  role({"id": "lleech", "name": "痢蛭", "officialName": "Lleech", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。在你的首个夜晚，你要选择一名存活的玩家：他中毒，只有他死亡时你才会一同死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lleech.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Poisons a host; kills at night; Lleech dies only when host dies."], "stateChanges": ["Host poisoned; target may die; Lleech death linked to host death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Host poison and death link require manual tracking; no automatic death."]}),
  role({"id": "vortox", "name": "涡流", "officialName": "Vortox", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。镇民玩家的能力都会产生错误信息。如果白天没人被处决，邪恶阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vortox.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Townsfolk information is false; each day must execute or evil wins."], "stateChanges": ["Forces false Townsfolk info and daily execution pressure."], "identityChanges": [], "teamChanges": ["Daily no-execution can make evil win."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "False information and daily execution loss condition are reminders only."]}),
] as const
