import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21265_94933.json"
const rolesSourceUrl = "https://clocktower.gstonegames.com/ct/grimoireRoleJson/"
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Yi Hua Jie Mu', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const yiHuaJieMuRoles = [
  role({"id": "mathematician", "name": "数学家", "officialName": "Mathematician", "team": "townsfolk", "abilityText": "每个夜晚，你会得知有多少名玩家的能力因为其他角色的能力而未正常生效。(从上个黎明到你被唤醒时）", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mathematician.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns how many player abilities malfunctioned due to other characters since last dawn."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Count only ability malfunction caused by other character abilities; ST confirms edge cases."]}),
  role({"id": "heshang", "name": "和尚", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚，当有邪恶玩家的能力首次选择或影响与你邻近的存活玩家时，改为此次能力不生效并持续至下个黎明，且你会得知你的能力被触发。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4432977694761_315f1863.jpg", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["First evil ability choosing or affecting a living neighbor fails until next dawn; Monk learns the trigger."], "stateChanges": ["Can cause an evil ability to fail for a bounded night window."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Trigger timing and neighbor status are manual; do not auto-cancel abilities."]}),
  role({"id": "gambler", "name": "赌徒", "officialName": "Gambler", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家并猜测他的角色：如果你猜错了，你会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gambler.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Chooses a player and guesses their character; wrong guess means the Gambler dies."], "stateChanges": ["May die after a wrong guess."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI can compare known role with guess, but ST confirms drunk/poisoned/registering exceptions."]}),
  role({"id": "langzhong", "name": "郎中", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的一名玩家：你会得知一个与他能力相关的词语。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_9255777694761_7594675d.jpg", "inputKinds": ["player", "text"], "setupImpact": [], "possibleOutcomes": ["Chooses one player and learns a word related to that player's ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["与你选择的玩家能力相关的词语是：{text}。"], "highRiskNotes": ["The word is ST-authored information, not a computed rule result."]}),
  role({"id": "qianke", "name": "掮客", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名存活玩家：如果他们阵营相同，今晚任何玩家使用自身能力选择他们之一作为目标时，改为选中另一名玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_2978127816071_ab841bc9.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["If two chosen living players share alignment, ability choices targeting either may redirect to the other tonight."], "stateChanges": ["Can redirect later ability targets between the two players."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track pair and alignment manually; do not auto-retarget downstream skills."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Chooses two players and learns whether either is a Demon; one good player may register as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Red herring and false registration are ST-confirmed."]}),
  role({"id": "chambermaid", "name": "侍女", "officialName": "Chambermaid", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的两名存活的玩家：你会得知他们中有几人在当晚因其自身能力而被唤醒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chambermaid.png", "inputKinds": ["players", "number"], "setupImpact": [], "possibleOutcomes": ["Chooses two living players and learns how many woke tonight due to their own ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only count ability wakeups, not ST administrative wakeups."]}),
  role({"id": "yinluren", "name": "引路人", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知今晚是否有邪恶玩家的能力选择或影响了他们之中的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_2147287694761_01761fcb.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Chooses two players and learns whether an evil ability chose or affected either tonight."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Include direct choices and indirect effects only after ST confirmation."]}),
  role({"id": "banxian", "name": "半仙", "officialName": "Custom", "team": "townsfolk", "abilityText": "任何在夜晚使用自身能力选择你的其他玩家，会改为选中另一名邪恶玩家作为替代。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_3833755308961_7e6f7e09.jpg", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Other night abilities choosing Banxian retarget to a different evil player."], "stateChanges": ["Can redirect night choices away from Banxian."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Retargeting is a reminder; ST must choose and confirm replacement target."]}),
  role({"id": "villageidiot", "name": "村夫", "officialName": "Village Idiot", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名玩家：你会得知他的阵营。[+0~2村夫，复数村夫中有一人醉酒]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1710949293_197011_77.png", "inputKinds": ["player"], "setupImpact": ["May add zero to two extra Village Idiots; if multiple, one Village Idiot is drunk."], "possibleOutcomes": ["Each Village Idiot learns a chosen player's alignment."], "stateChanges": ["One Village Idiot is drunk if more than one Village Idiot is in play."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates to avoid duplicate-role setup drift."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Has the ability of the last player executed; if that player was evil, Cannibal is poisoned until next good execution death."], "stateChanges": ["May become poisoned through evil executed character."], "identityChanges": ["Temporarily has another character's ability, not another identity."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Ability source and poison window are manual."]}),
  role({"id": "gossip", "name": "造谣者", "officialName": "Gossip", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If the public statement is true, one player may die that night."], "stateChanges": ["Can create an extra night death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Truth check and death target are ST-confirmed."]}),
  role({"id": "nightwatchman", "name": "守夜人", "officialName": "Nightwatchman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名玩家：他会得知你是守夜人。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/nightwatchman.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Once per game chooses a player who learns the Nightwatchman is the Nightwatchman."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["{seat}号是守夜人。"], "highRiskNotes": ["Choice and message are private; do not broadcast."]}),
  role({"id": "jiubao", "name": "酒保", "officialName": "Custom", "team": "outsider", "abilityText": "与你邻近的善良玩家（旅行者除外）之一醉酒，即使你死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4591987694761_11d3a855.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["One neighboring good player (not a Traveller) is drunk; the drunkenness persists if Jiubao dies by execution.","If Jiubao dies by any means other than execution, the drunkenness ends immediately."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Neighbor drunk target is ST-confirmed; do not auto-mark."]}),
  role({"id": "shijie", "name": "使节", "officialName": "Custom", "team": "outsider", "abilityText": "每个夜晚限一次，一名玩家在使用自身能力选择邪恶玩家时会改为选中你，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_8334197694761_80377ad9.jpg", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Once each night, one player using their ability to choose an evil player chooses the Envoy instead (ST decides whether to trigger)."], "stateChanges": ["Can redirect choices toward Envoy even while dead."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track the once-per-night redirect manually."]}),
  role({"id": "lunatic", "name": "疯子", "officialName": "Lunatic", "team": "outsider", "abilityText": "你以为你是一个恶魔，但其实你不是。恶魔知道你是疯子以及你在每个夜晚选择了哪些玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lunatic.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Thinks they are the Demon and may receive fake evil information and fake choices."], "stateChanges": [], "identityChanges": ["Receives false Demon identity information."], "teamChanges": [], "playerMessageTemplates": ["你以为自己是恶魔；你的信息由说书人安排。"], "highRiskNotes": ["Do not expose true Lunatic status in player-facing output."]}),
  role({"id": "goon", "name": "莽夫", "officialName": "Goon", "team": "outsider", "abilityText": "每个夜晚，首个使用其自身能力选择了你的玩家会醉酒直到下个黄昏。你会转变为他的阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/goon.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["First player each night to choose the Goon becomes drunk until dusk; Goon becomes that player's alignment."], "stateChanges": ["Chooser becomes drunk until dusk."], "identityChanges": [], "teamChanges": ["Goon changes alignment to the chooser's alignment."], "playerMessageTemplates": ["你的阵营发生了变化，请等待说书人确认。"], "highRiskNotes": ["Alignment and drunk change must be explicitly confirmed."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["role", "player"], "setupImpact": ["Adds or removes one Outsider."], "possibleOutcomes": ["Learns in-play Outsiders; if an Outsider dies by day, chooses a player to die that night."], "stateChanges": ["Can cause extra death after Outsider day death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Only appears in templates with explicit outsider setup adjustment."]}),
  role({"id": "gudiao", "name": "蛊雕", "officialName": "Custom", "team": "minion", "abilityText": "蛊雕：每个夜晚，你要选择左或右：将你的飞行标记从当前位置移动到这个方向上的下一名存活善良玩家。他中毒且可能被当作邪恶阵营和爪牙角色，你会知道他原本的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4078497694761_5c6ddcce.jpg", "inputKinds": ["text", "player"], "setupImpact": [], "possibleOutcomes": ["Moves marker left/right to next living good player, who is poisoned and may register as evil/Minion; learns original role."], "stateChanges": ["Poisons marked player."], "identityChanges": [], "teamChanges": ["Marked player may register as evil/Minion but true alignment does not change."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-move marker or apply poison/registering.","Version note: this script uses an older GStone text; the current wiki version differs (fixed clockwise direction with a once-per-game direction change, targets the next living Townsfolk only, the marked player registers only as the evil Gudiao, and effects last until the next dusk). Confirm with the storyteller which version applies."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "Marionette", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["role"], "setupImpact": ["Must neighbor the Demon and thinks they are a good character."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["Player thinks they are a good character but is actually Marionette."], "teamChanges": ["Actual alignment is evil."], "playerMessageTemplates": ["你的展示身份是说书人安排的善良角色。"], "highRiskNotes": ["Kept out of first normal templates to avoid adjacency/false-identity setup drift."]}),
  role({"id": "harpy", "name": "鹰身女妖", "officialName": "Harpy", "team": "minion", "abilityText": "每个夜晚，你要选择两名玩家：明天第一名玩家需要“疯狂”地证明第二名玩家是邪恶的，否则他们可能会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202307/c_4331482099861_0db1bfaf.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Chooses two players; first must be mad that second is evil or one/both might die."], "stateChanges": ["May cause death through madness pressure."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["明天你需要疯狂地证明{seat}号是邪恶的。"], "highRiskNotes": ["Madness judgment and death penalty are ST discretion."]}),
  role({"id": "taotie", "name": "饕餮", "officialName": "Custom", "team": "demon", "abilityText": "每个夜晚*，你要选择任意数量的非旅行者玩家或一名旅行者玩家：如果他们的角色类型均不相同，他们死亡。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_5897997694761_fbe1f00c.jpg", "inputKinds": ["players"], "setupImpact": ["Adds one Outsider."], "possibleOutcomes": ["Chooses any number of non-travelers or one traveler; if all character types differ, they die."], "stateChanges": ["May kill multiple players."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; multi-kill check remains ST-confirmed."]}),
  role({"id": "pukka", "name": "普卡", "officialName": "Pukka", "team": "demon", "abilityText": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pukka.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Poisons chosen player; previous Pukka-poisoned player dies and becomes healthy."], "stateChanges": ["Applies poison, death, and recovery over a rolling chain."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track previous poison target manually; do not auto-kill or auto-heal."]}),
  role({"id": "dianyuzhang", "name": "典狱长", "officialName": "Custom", "team": "demon", "abilityText": "每个夜晚，你要选择至多三名玩家：如果明天白天他们之一死于处决，被你上次选择的其他玩家会在当晚死亡。否则，当晚他们之中会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_5570117816071_2f5793fd.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Chooses up to three players; next day execution among them affects later deaths, otherwise one among them may die."], "stateChanges": ["Can create delayed conditional deaths."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Requires previous choice tracking and execution check; no automatic deaths.","Deaths resolve at Dianyuzhang's next night action: check whether a marked player died by execution before this action, even if Dianyuzhang is not woken that night.","Drunk/poison is judged at resolution time, not when choosing: '判罚' markers are always placed, but if Dianyuzhang is drunk or poisoned at resolution, no marked player dies and the markers are removed.","Acts from the first night and must choose one to three players (cannot skip)."]}),
  role({"id": "hundun", "name": "混沌", "officialName": "Custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式杀死了一名与你邻近的镇民玩家，除旅行者外的所有善良玩家会中毒直到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9149178608961_89693def.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Kills one player; if kills a neighboring Townsfolk, all good players except Travellers are poisoned until next dusk."], "stateChanges": ["Can kill and can poison all good players except Travellers until next dusk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Neighbor/Townsfolk check and global poison are ST-confirmed."]}),
  role({"id": "djinn", "name": "灯神", "officialName": "Djinn", "team": "fabled", "abilityText": "使用灯神的相克规则。所有玩家都会知道其内容。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/djinn.png", "inputKinds": ["none"], "setupImpact": ["Fabled reminder for jinxes or special rule interactions."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Never appears in setup templates or demon bluffs."]}),
] as const satisfies readonly SmartRoleDefinition[]
