import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "yi-hua-jie-mu"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string; setupAdjustments?: SetupTemplate['setupAdjustments'] }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, setupAdjustments: input.setupAdjustments, notes: [input.note], verified: true }
}

export const yiHuaJieMuSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["mathematician", "heshang", "gambler", "langzhong", "qianke", "gudiao", "pukka"], bluffs: ["fortuneteller", "chambermaid", "yinluren"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "harpy", "pukka"], bluffs: ["banxian", "cannibal", "gossip"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["chambermaid", "yinluren", "banxian", "cannibal", "gossip", "gudiao", "pukka"], bluffs: ["nightwatchman", "jiubao", "shijie"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["heshang", "gambler", "langzhong", "qianke", "fortuneteller", "shijie", "harpy", "dianyuzhang"], bluffs: ["chambermaid", "yinluren", "banxian"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "jiubao", "gudiao", "dianyuzhang"], bluffs: ["cannibal", "gossip", "nightwatchman"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "lunatic", "goon", "gudiao", "hundun"], bluffs: ["yinluren", "banxian", "cannibal"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "shijie", "lunatic", "harpy", "hundun"], bluffs: ["gossip", "nightwatchman", "jiubao"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["mathematician", "heshang", "gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "gudiao", "harpy", "pukka"], bluffs: ["yinluren", "banxian", "cannibal"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "harpy", "gudiao", "pukka"], bluffs: ["gossip", "nightwatchman", "jiubao"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["chambermaid", "yinluren", "banxian", "cannibal", "gossip", "nightwatchman", "mathematician", "gudiao", "harpy", "pukka"], bluffs: ["shijie", "lunatic", "goon"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["heshang", "gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "shijie", "harpy", "gudiao", "dianyuzhang"], bluffs: ["banxian", "cannibal", "gossip"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "gossip", "jiubao", "gudiao", "harpy", "dianyuzhang"], bluffs: ["nightwatchman", "shijie", "lunatic"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "lunatic", "goon", "gudiao", "harpy", "hundun"], bluffs: ["cannibal", "gossip", "nightwatchman"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "gossip", "nightwatchman", "shijie", "lunatic", "harpy", "gudiao", "hundun"], bluffs: ["jiubao", "goon", "mathematician"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["banxian", "cannibal", "gossip", "nightwatchman", "mathematician", "heshang", "gambler", "jiubao", "shijie", "gudiao", "harpy", "hundun"], bluffs: ["qianke", "fortuneteller", "chambermaid"], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["mathematician", "heshang", "gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "jiubao", "gudiao", "harpy", "godfather", "pukka"], bluffs: ["banxian", "cannibal", "gossip"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "gossip", "goon", "harpy", "gudiao", "godfather", "pukka"], bluffs: ["nightwatchman", "jiubao", "shijie"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "lunatic", "goon", "gudiao", "harpy", "godfather", "hundun"], bluffs: ["gossip", "nightwatchman", "jiubao"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "gossip", "nightwatchman", "mathematician", "shijie", "lunatic", "harpy", "gudiao", "godfather", "hundun"], bluffs: ["goon", "heshang", "gambler"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["heshang", "gambler", "langzhong", "qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "shijie", "lunatic", "goon", "harpy", "gudiao", "godfather", "dianyuzhang"], bluffs: ["cannibal", "gossip", "nightwatchman"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["qianke", "fortuneteller", "chambermaid", "yinluren", "banxian", "cannibal", "gossip", "nightwatchman", "jiubao", "shijie", "lunatic", "gudiao", "harpy", "godfather", "dianyuzhang"], bluffs: ["goon", "mathematician", "heshang"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["yinluren", "banxian", "cannibal", "gossip", "nightwatchman", "mathematician", "heshang", "gambler", "goon", "jiubao", "shijie", "harpy", "gudiao", "godfather", "dianyuzhang"], bluffs: ["fortuneteller", "chambermaid", "lunatic"], setupAdjustments: [{ ruleId: 'godfather-outsider-setup', compositionDelta: { townsfolk: -1, outsider: 1 }, choiceId: 'godfather-adds-outsider', note: 'Godfather +1 Outsider template path.' }], note: "Verified setup; Village Idiot, Taotie, Marionette and Djinn stay out of normal templates; Goon, Godfather, Gudiao, Harpy, Pukka, Dianyuzhang and Hundun outcomes remain ST-confirmed." }),
]
