import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20783_90331.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Fei Fan Ying Tian', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const feiFanYingTianRoles = [
  role({"id": "bountyhunter", "name": "赏金猎人", "officialName": "Bounty Hunter", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名邪恶玩家。每当你得知的玩家死亡，你会在当晚得知另一名邪恶玩家。[会有一名镇民转变为邪恶阵营]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/bounty_hunter.png", "inputKinds": ["player"], "setupImpact": ["Adds one evil Townsfolk at setup."], "possibleOutcomes": ["Learns an evil player; when that player dies, learns another at night."], "stateChanges": [], "identityChanges": [], "teamChanges": ["One Townsfolk becomes evil during setup."], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; do not auto-change alignment."]}),
  role({"id": "po", "name": "珀", "officialName": "Po", "team": "demon", "abilityText": "每个夜晚*，你可以选择一名玩家：他死亡。如果你上次选择时没有选择任何玩家，当晚你要选择三名玩家：他们死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/po.png", "inputKinds": ["player", "players"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["May kill one player, or after a no-kill choice may kill three players."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track previous no-kill choice before suggesting triple kill; do not auto-kill."]}),
  role({"id": "fanggu", "name": "方古", "officialName": "Fang Gu", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fang_gu.png", "inputKinds": ["player"], "setupImpact": ["Adds 1 Outsider."], "possibleOutcomes": [], "stateChanges": ["Kills nightly; first outsider killed by Fang Gu can transform."], "identityChanges": ["First outsider killed by Fang Gu becomes evil Fang Gu while old Fang Gu dies."], "teamChanges": ["Transformed outsider becomes evil."], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; transformation and death require ST confirmation."]}),
  role({"id": "zombuul", "name": "僵怖", "officialName": "Zombuul", "team": "demon", "abilityText": "每个夜晚*，如果今天白天没有人死亡，你会被唤醒并要选择一名玩家：他死亡。当你首次死亡后，你仍存活，但会被当作死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/zombuul.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Wakes to kill only if nobody died during the day; first death leaves it alive but registering dead."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-decide wake condition or death registration."]}),
  role({"id": "psychopath", "name": "精神病患者", "officialName": "Psychopath", "team": "minion", "abilityText": "每个白天，在提名开始前，你可以公开选择一名玩家：他死亡。如果你被处决，提名你的玩家需要和你猜拳，只有你输了你才会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/psychopath.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Can publicly choose a player to die before nominations; execution may require roshambo."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Day death and roshambo result are manual."]}),
  role({"id": "devilsadvocate", "name": "魔鬼代言人", "officialName": "Devil's Advocate", "team": "minion", "abilityText": "每个夜晚，你要选择一名存活的玩家（与上个夜晚不同）：如果明天白天他被处决，他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/devils_advocate.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Chosen living player survives execution tomorrow; cannot repeat previous target."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Protection does not auto-prevent death until ST confirms execution source."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["player", "text"], "setupImpact": ["May add or remove 1 Outsider."], "possibleOutcomes": [], "stateChanges": ["If an Outsider died today, wakes and may kill."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; outsider death trigger is manual."]}),
  role({"id": "witch", "name": "女巫", "officialName": "Witch", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：如果他明天白天发起提名，他死亡。如果只有三名存活的玩家，你失去此能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/witch.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Chosen player may die if they nominate tomorrow; ability off with three living players."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Nomination death is manual."]}),
  role({"id": "harpy", "name": "鹰身女妖", "officialName": "Harpy", "team": "minion", "abilityText": "每个夜晚，你要选择两名玩家：明天第一名玩家需要“疯狂”地证明第二名玩家是邪恶的，否则他们可能会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202307/c_4331482099861_0db1bfaf.jpg", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Failure may kill one or both players."], "stateChanges": ["Creates madness requirement for first target about second target being evil."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You are mad that {seatB} is evil tomorrow."], "highRiskNotes": ["Madness and death penalty are ST discretion."]}),
  role({"id": "damsel", "name": "落难少女", "officialName": "Damsel", "team": "outsider", "abilityText": "所有爪牙都知道落难少女在场。每局游戏限一次，任意爪牙可以公开猜测你是落难少女，如果猜对，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/damsel.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["If a Minion publicly guesses Damsel once and is correct, good loses."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss remains ST declaration."]}),
  role({"id": "puzzlemaster", "name": "解谜大师", "officialName": "Puzzlemaster", "team": "outsider", "abilityText": "一名玩家醉酒，即使你已死亡。每局游戏限一次，你可以猜测谁是那个醉酒的玩家，如果猜对了，你会得知谁是恶魔，但如果猜错了，你会得知错误的“谁是恶魔”信息。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/puzzlemaster.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Once-per-game guess can learn Demon if right or false Demon if wrong."], "stateChanges": ["One player is drunk even if Puzzlemaster is dead."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Drunk target and final answer are manual."]}),
  role({"id": "tinker", "name": "修补匠", "officialName": "Tinker", "team": "outsider", "abilityText": "你随时可能死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/tinker.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["May die at any time by ST choice."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Never auto-kill Tinker."]}),
  role({"id": "golem", "name": "魔像", "officialName": "Golem", "team": "outsider", "abilityText": "每局游戏你只能发起提名一次。当你发起提名时，如果被你提名的玩家不是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/golem.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Can nominate once; if nominee is not Demon, nominee dies."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Nomination limit and death are manual."]}),
  role({"id": "alchemist", "name": "炼金术士", "officialName": "Alchemist", "team": "townsfolk", "abilityText": "你拥有一个爪牙角色的能力。当你使用能力时，说书人可能会要求你更换选择。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/alchemist.png", "inputKinds": ["role"], "setupImpact": ["If the gained Minion ability adds or removes characters at setup (e.g. Baron), it also applies during setup."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["Has a Minion ability (usually out-of-play, may be in-play)."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Chosen Minion ability is setup/starter choice; do not auto-grant effects."]}),
  role({"id": "tealady", "name": "茶艺师", "officialName": "Tea Lady", "team": "townsfolk", "abilityText": "如果与你邻近的两名存活的玩家是善良的，他们不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/tea_lady.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Neighbors cannot die if both living neighbors are good."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Protection depends on living neighbors and alignment registration; ST confirms."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["If chosen role is in play, that role becomes drunk."], "identityChanges": ["May gain one good character ability once per game."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-drunk or grant ability."]}),
  role({"id": "huntsman", "name": "巡山人", "officialName": "Huntsman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名存活的玩家：如果你选中了落难少女，她会变成一个不在场的镇民角色。[+落难少女]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/huntsman.png", "inputKinds": ["player"], "setupImpact": ["Adds the Damsel."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["If chooses Damsel, she becomes an out-of-play Townsfolk."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; Damsel conversion is manual."]}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Madness requirement is social and manually judged."], "identityChanges": ["May later gain the shown Townsfolk ability if madness condition and death trigger are satisfied."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-grant ability."]}),
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not compute from hidden state without ST confirmation."]}),
  role({"id": "steward", "name": "事务官", "officialName": "Steward", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名善良玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202305/c_9219342584861_b889322f.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Learns one good player."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Registration and misinformation are ST-confirmed."]}),
  role({"id": "highpriestess", "name": "女祭司", "officialName": "High Priestess", "team": "townsfolk", "abilityText": "每个夜晚，你会得知一名说书人认为你最应该与其交流的玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202306/c_9934958657861_5ff1282a.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Learns one player ST thinks they should talk to."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["This is ST advice, not a computed best move."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Receives once-per-game advice."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice draft: {advice}"], "highRiskNotes": ["AI can draft wording only."]}),
  role({"id": "general", "name": "将军", "officialName": "General", "team": "townsfolk", "abilityText": "每个夜晚，你会得知说书人认为哪个阵营当前更有优势（善良/邪恶/均势）。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/general.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Learns ST view of which team is ahead or neither."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not compute advantage from logs automatically."]}),
  role({"id": "innkeeper", "name": "旅店老板", "officialName": "Innkeeper", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择两名玩家：他们当晚不会死亡，但其中一人会醉酒到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/innkeeper.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Two chosen players are safe from death tonight, but one becomes drunk until dusk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Protection and drunkenness are manual."]}),
  role({"id": "sailor", "name": "水手", "officialName": "Sailor", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：你或他之一会醉酒直到下个黄昏。你不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sailor.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Sailor or chosen player becomes drunk until dusk; Sailor cannot die."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Drunk choice and death immunity must be confirmed."]}),
] as const satisfies readonly SmartRoleDefinition[]
