import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20756_59931.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = "2026-07-22"

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: "Sheng Ri Yan Hui", setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const shengRiYanHuiRoles = [
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not compute candidates from hidden state without ST confirmation."]}),
  role({"id": "chef", "name": "厨师", "officialName": "Chef", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知场上邻座的邪恶玩家有多少对。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/chef.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Apply source ability only as an AI/ST-confirmed suggestion."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their count, role, new/perceived identity, advice or information result."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Do not auto-apply this role result; storyteller confirms before writing authority state.", "Chef result uses source ability text and stays a storyteller-confirmed suggestion."]}),
  role({"id": "sailor", "name": "水手", "officialName": "Sailor", "team": "townsfolk", "abilityText": "每个夜晚，你要选择一名存活的玩家：你或他之一会醉酒直到下个黄昏。你不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sailor.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses an alive player; Sailor or target is drunk until dusk.", "Sailor cannot die."], "stateChanges": ["Sailor or target may be drunk until dusk.", "Sailor may survive death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Drunken target and death prevention are ST-confirmed."]}),
  role({"id": "king", "name": "国王", "officialName": "King", "team": "townsfolk", "abilityText": "每个夜晚，如果死亡的玩家数量大于或等于存活的玩家数量，你会得知一个存活的角色。恶魔知道你是国王。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/king.png", "inputKinds": ["players", "role"], "setupImpact": [], "possibleOutcomes": ["If dead players equal or outnumber living players, learns one alive character.", "Demon knows who the King is."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn an alive character: {roleName}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "King information depends on dead/living counts and ST choice."]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns number of dead evil players."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Recluse and registration effects remain ST-confirmed."]}),
  role({"id": "innkeeper", "name": "旅店老板", "officialName": "Innkeeper", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择两名玩家：他们当晚不会死亡，但其中一人会醉酒到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/innkeeper.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Chooses two players; both are safe from death tonight, one is drunk until dusk."], "stateChanges": ["Two chosen players may be protected from death.", "One chosen player may be drunk until dusk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Protection and drunk target are ST-confirmed."]}),
  role({"id": "gambler", "name": "赌徒", "officialName": "Gambler", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家并猜测他的角色：如果你猜错了，你会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gambler.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Chooses a player and guesses their character; if wrong, Gambler dies."], "stateChanges": ["Gambler may die if guess is wrong."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Your guess is recorded; if wrong, you may die."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Guess correctness and death are ST-confirmed; do not auto-kill."]}),
  role({"id": "juggler", "name": "杂耍艺人", "officialName": "Juggler", "team": "townsfolk", "abilityText": "在你的首个白天，你可以公开猜测任意玩家的角色最多五次。在当晚，你会得知猜测正确的角色数量。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/juggler.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["On first day, may publicly guess up to five player-character pairs; learns correct count that night."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn {count} correct guesses."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Count depends on public first-day guesses and registration."]}),
  role({"id": "courtier", "name": "侍臣", "officialName": "Courtier", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个角色：如果该角色在场，该角色之一从当晚开始醉酒三天三夜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/courtier.png", "inputKinds": ["role"], "setupImpact": [], "possibleOutcomes": ["Once per game, chooses a character; one instance of that character is drunk for three days and nights if in play."], "stateChanges": ["Chosen character may be drunk for three days and nights."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Duration and matching in-play character are ST-confirmed."]}),
  role({"id": "fool", "name": "弄臣", "officialName": "Fool", "team": "townsfolk", "abilityText": "当你首次将要死亡时，你不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fool.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["First time Fool would die, they do not die."], "stateChanges": ["May prevent first death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Track whether Fool protection has been used; do not auto-prevent death."]}),
  role({"id": "magician", "name": "魔术师", "officialName": "Magician", "team": "townsfolk", "abilityText": "恶魔会以为你是爪牙。爪牙会以为你是恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/magician.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Demon may see Magician as a Minion; Minions may see Magician as Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": ["May involve alignment, registration or evil/good interpretation."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Affects evil info only; do not change actual identity or team."]}),
  role({"id": "choirboy", "name": "唱诗男孩", "officialName": "Choirboy", "team": "townsfolk", "abilityText": "如果恶魔杀死了国王，你会得知哪名玩家是恶魔。[+国王]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/choirboy.png", "inputKinds": ["none"], "setupImpact": ["如果恶魔杀死了国王，你会得知哪名玩家是恶魔。[+国王]", "Adds King."], "possibleOutcomes": ["If Demon kills King, learns which player is Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn the Demon is {seat}."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Choirboy because it requires King setup path."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Gains the last executed player ability; if the source is evil, becomes poisoned until next good execution death."], "stateChanges": ["May gain ability; may become poisoned."], "identityChanges": ["Ability source changes but identity remains Cannibal."], "teamChanges": [], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Track ability source and poison end manually."]}),
  role({"id": "butler", "name": "管家", "officialName": "Butler", "team": "outsider", "abilityText": "每个夜晚，你要选择除你以外的一名玩家：明天白天，只有他投票时你才能投票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/butler.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chooses a master; tomorrow can only vote if that player votes."], "stateChanges": ["Voting restriction for next day."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Vote eligibility is a reminder for vote UI; do not auto-block votes silently."]}),
  role({"id": "acrobat", "name": "杂技演员", "officialName": "杂技演员", "team": "outsider", "abilityText": "每个夜晚*，如果与你邻近的存活善良玩家之一醉酒或中毒，你死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/acrobat.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["If a neighboring alive good player is drunk or poisoned, Acrobat dies at night."], "stateChanges": ["May die due to neighbor poison/drunk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Requires checking neighbor, alive, good and poison/drunk state; do not auto-kill."]}),
  role({"id": "sweetheart", "name": "心上人", "officialName": "Sweetheart", "team": "outsider", "abilityText": "当你死亡时，会有一名玩家开始醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/sweetheart.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["When Sweetheart dies, one player becomes drunk from now on."], "stateChanges": ["One player may become permanently drunk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Drunk target is chosen/confirmed by ST."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": ["你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。"], "possibleOutcomes": ["Player thinks they are a Townsfolk but is actually Drunk."], "stateChanges": ["Ability does not function."], "identityChanges": ["Actual and perceived character differ."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Hidden identity; default templates avoid this role."]}),
  role({"id": "godfather", "name": "教父", "officialName": "Godfather", "team": "minion", "abilityText": "在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/godfather.png", "inputKinds": ["player", "role"], "setupImpact": ["在你的首个夜晚，你会得知有哪些外来者角色在场。如果有外来者在白天死亡，你会在当晚被唤醒并且你要选择一名玩家：他死亡。[-1或+1外来者]", "May add or remove one Outsider."], "possibleOutcomes": ["Learns in-play Outsiders on first night; may kill after daytime Outsider death."], "stateChanges": ["May cause extra night death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Godfather setup-changing path."]}),
  role({"id": "devilsadvocate", "name": "魔鬼代言人", "officialName": "Devil's Advocate", "team": "minion", "abilityText": "每个夜晚，你要选择一名存活的玩家（与上个夜晚不同）：如果明天白天他被处决，他不会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/devils_advocate.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Chosen living player survives execution tomorrow."], "stateChanges": ["Chosen player may be protected from execution death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Cannot choose same target as previous night; ST confirms survival."]}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "Cerenovus", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["player", "role"], "setupImpact": [], "possibleOutcomes": ["Chosen player is made mad as a chosen good character tomorrow day and night."], "stateChanges": ["May impose madness; may lead to execution."], "identityChanges": ["May grant, replace, fake, swap or transform an ability/character."], "teamChanges": [], "playerMessageTemplates": ["You are made mad as {roleName}; prove it or something bad may happen."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Madness prompt and consequence are ST-confirmed."]}),
  role({"id": "marionette", "name": "提线木偶", "officialName": "Marionette", "team": "minion", "abilityText": "你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/marionette.png", "inputKinds": ["none"], "setupImpact": ["你以为你是一个善良角色，但其实你不是。恶魔会知道你是提线木偶。[提线木偶会与恶魔邻座]"], "possibleOutcomes": ["Player thinks they are good but is actually evil Minion."], "stateChanges": [], "identityChanges": ["Actual and perceived character differ."], "teamChanges": ["Actual alignment is evil while perceived role is good."], "playerMessageTemplates": ["If adopted, storyteller may tell the target their new or perceived role information."], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Must neighbor Demon; templates using it need ST adjacency check."]}),
  role({"id": "lleech", "name": "痢蛭", "officialName": "Lleech", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。在你的首个夜晚，你要选择一名存活的玩家：他中毒，只有他死亡时你才会一同死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lleech.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["First night chooses a host who is poisoned; each night kills a player; Lleech dies only if host dies."], "stateChanges": ["Host is poisoned.", "Chosen target may die.", "Lleech death is linked to host death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Host poison and death link require manual tracking; no automatic death."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Kills each night; self-kill may make a Minion the new Imp."], "stateChanges": ["May cause death."], "identityChanges": ["Minion may become new Imp."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Self-kill handoff requires ST confirmation."]}),
  role({"id": "vigormortis", "name": "亡骨魔", "officialName": "Vigormortis", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/vigormortis.png", "inputKinds": ["players"], "setupImpact": ["每个夜晚*，你要选择一名玩家：他死亡。被你杀死的爪牙保留他的能力，且与他邻近的两名镇民之一中毒。[-1外来者]", "Removes one Outsider."], "possibleOutcomes": ["Kills each night; killed Minion keeps ability and one neighboring Townsfolk is poisoned."], "stateChanges": ["May cause death.", "May poison one neighboring Townsfolk."], "identityChanges": ["Killed Minions may keep ability while dead."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Default templates avoid Vigormortis setup-changing path."]}),
  role({"id": "fanggu", "name": "方古", "officialName": "Fang Gu", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fang_gu.png", "inputKinds": ["player"], "setupImpact": ["每个夜晚*，你要选择一名玩家：他死亡。被该能力杀死的外来者改为变成邪恶的方古且你代替他死亡，但每局游戏仅能成功转化一次。[+1外来者]", "Adds one Outsider."], "possibleOutcomes": ["Kills each night; first Outsider killed this way may become evil Fang Gu while old Fang Gu dies."], "stateChanges": ["May cause death."], "identityChanges": ["Outsider may become Fang Gu."], "teamChanges": ["Converted Outsider becomes evil."], "playerMessageTemplates": [], "highRiskNotes": ["AI only suggests settlement; ST must confirm identity, alignment, death, poison/drunk, madness and win/loss changes.", "Jump and old Demon death are manual; default templates avoid Fang Gu."]}),
] as const
