import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "nuo-fu-jiu-xing"

function template(input: { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }): SetupTemplate {
  return { scriptId, templateId: `${scriptId}-${input.count}-${input.id}`, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const nuoFuJiuXingSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["steward", "noble", "fortuneteller", "monk", "seamstress", "humeiniang", "lleech"], "bluffs": ["sailor", "highpriestess", "langzhong"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 7, "style": "long-game", "roles": ["sailor", "highpriestess", "langzhong", "savant", "fisherman", "goblin", "aohe"], "bluffs": ["steward", "noble", "philosopher"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["jinyiwei", "philosopher", "juggler", "noble", "monk", "harpy", "yaggababble"], "bluffs": ["steward", "fortuneteller", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["steward", "noble", "fortuneteller", "monk", "seamstress", "puzzlemaster", "humeiniang", "lleech"], "bluffs": ["sailor", "highpriestess", "langzhong"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 8, "style": "long-game", "roles": ["sailor", "highpriestess", "langzhong", "savant", "fisherman", "butler", "goblin", "aohe"], "bluffs": ["steward", "noble", "philosopher"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["steward", "noble", "fortuneteller", "monk", "seamstress", "puzzlemaster", "golem", "humeiniang", "lleech"], "bluffs": ["sailor", "highpriestess", "langzhong"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 9, "style": "long-game", "roles": ["sailor", "highpriestess", "langzhong", "savant", "fisherman", "butler", "drunk", "goblin", "aohe"], "bluffs": ["steward", "noble", "philosopher"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "monk", "humeiniang", "goblin", "lleech"], "bluffs": ["jinyiwei", "savant", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 10, "style": "long-game", "roles": ["jinyiwei", "savant", "philosopher", "fisherman", "seamstress", "juggler", "monk", "psychopath", "harpy", "aohe"], "bluffs": ["steward", "noble", "fortuneteller"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["steward", "highpriestess", "langzhong", "fortuneteller", "philosopher", "fisherman", "juggler", "psychopath", "humeiniang", "yaggababble"], "bluffs": ["noble", "sailor", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "monk", "puzzlemaster", "humeiniang", "goblin", "lleech"], "bluffs": ["jinyiwei", "savant", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 11, "style": "long-game", "roles": ["jinyiwei", "savant", "philosopher", "fisherman", "seamstress", "juggler", "monk", "butler", "psychopath", "harpy", "aohe"], "bluffs": ["steward", "noble", "fortuneteller"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "monk", "puzzlemaster", "golem", "humeiniang", "goblin", "lleech"], "bluffs": ["jinyiwei", "savant", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 12, "style": "long-game", "roles": ["jinyiwei", "savant", "philosopher", "fisherman", "seamstress", "juggler", "monk", "butler", "drunk", "psychopath", "harpy", "aohe"], "bluffs": ["steward", "noble", "fortuneteller"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["steward", "highpriestess", "langzhong", "fortuneteller", "philosopher", "fisherman", "juggler", "puzzlemaster", "drunk", "psychopath", "humeiniang", "yaggababble"], "bluffs": ["noble", "sailor", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "jinyiwei", "monk", "seamstress", "psychopath", "humeiniang", "goblin", "lleech"], "bluffs": ["savant", "philosopher", "fisherman"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 13, "style": "long-game", "roles": ["savant", "philosopher", "fisherman", "juggler", "steward", "noble", "sailor", "highpriestess", "monk", "humeiniang", "goblin", "harpy", "aohe"], "bluffs": ["langzhong", "fortuneteller", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "jinyiwei", "monk", "seamstress", "puzzlemaster", "psychopath", "humeiniang", "goblin", "lleech"], "bluffs": ["savant", "philosopher", "fisherman"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 14, "style": "long-game", "roles": ["savant", "philosopher", "fisherman", "juggler", "steward", "noble", "sailor", "highpriestess", "monk", "butler", "humeiniang", "goblin", "harpy", "aohe"], "bluffs": ["langzhong", "fortuneteller", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["steward", "noble", "sailor", "highpriestess", "langzhong", "fortuneteller", "jinyiwei", "monk", "seamstress", "puzzlemaster", "golem", "psychopath", "humeiniang", "goblin", "lleech"], "bluffs": ["savant", "philosopher", "fisherman"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "long", "count": 15, "style": "long-game", "roles": ["savant", "philosopher", "fisherman", "juggler", "steward", "noble", "sailor", "highpriestess", "monk", "butler", "drunk", "humeiniang", "goblin", "harpy", "aohe"], "bluffs": ["langzhong", "fortuneteller", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["steward", "highpriestess", "langzhong", "fortuneteller", "philosopher", "fisherman", "juggler", "noble", "sailor", "puzzlemaster", "drunk", "psychopath", "humeiniang", "harpy", "yaggababble"], "bluffs": ["jinyiwei", "monk", "seamstress"], "note": "已核对配板。会改变配板或影响胜负的效果只作提醒，由说书人确认。"}),
]
