import type { SetupRule } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_20949_46831.json"
const reviewedAt = '2026-07-21'

export const nanNanDiYuSetupRules: readonly SetupRule[] = [
  {
    id: "nan-nan-di-yu-monk-reminder",
    roleId: "monk",
    summary: "Monk protection is a reminder; do not auto-prevent Demon death.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-huntsman-reminder",
    roleId: "huntsman",
    summary: "Huntsman adds the Damsel and may change the Damsel into a not-in-play Townsfolk; excluded from first templates unless explicitly chosen.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-ravenkeeper-reminder",
    roleId: "ravenkeeper",
    summary: "Ravenkeeper wakes only if killed at night; role information is storyteller-confirmed.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-drunk-reminder",
    roleId: "drunk",
    summary: "Drunk is hidden and thinks they are a Townsfolk; assign and verify manually during setup.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-klutz-reminder",
    roleId: "klutz",
    summary: "Klutz death choice may lose the game for good; only create a win/loss reminder.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-recluse-reminder",
    roleId: "recluse",
    summary: "Recluse may register as evil, Minion or Demon; AI advice must expose registration as storyteller discretion.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-damsel-reminder",
    roleId: "damsel",
    summary: "Damsel is known to Minions and Minion guess may lose the game; never auto-declare loss.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-spy-reminder",
    roleId: "spy",
    summary: "Spy may register as good; grimoire viewing is a reminder only.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-poisoner-reminder",
    roleId: "poisoner",
    summary: "Poisoned state is a candidate result until storyteller confirms it.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-goblin-reminder",
    roleId: "goblin",
    summary: "Goblin claim and execution may win for evil; only create a win/loss reminder.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-scarletwoman-reminder",
    roleId: "scarletwoman",
    summary: "Scarlet Woman may become the Demon under strict alive-count conditions; identity change requires confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-pukka-reminder",
    roleId: "pukka",
    summary: "Pukka poisons current target and kills previous poisoned target; chain state must be checked manually.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-fanggu-reminder",
    roleId: "fanggu",
    summary: "Fang Gu adds 1 Outsider and may jump to the first Outsider it kills; excluded from first templates unless explicitly chosen.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-nodashii-reminder",
    roleId: "nodashii",
    summary: "No Dashii kills and poisons neighboring Townsfolk; death and poison markers remain manual.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
  {
    id: "nan-nan-di-yu-imp-reminder",
    roleId: "imp",
    summary: "Imp self-kill may pass Demon to a Minion; identity and death changes require confirmation.",
    knowledgeStatus: 'confirmed',
    sourceUrls: [sourceUrl],
    reviewedAt,
  },
]
