import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21489_56657.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Jing Hou Jia Yin', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const jingHouJiaYinRoles = [
  role({"id": "xiuxingzhe", "name": "修行者", "officialName": "Custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知距离最近的邪恶玩家位于你的顺时针还是逆时针方向。如果两侧的邪恶玩家与你距离相等，你得知的信息由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9833664308961_ad73c43b.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Learns whether nearest evil player is clockwise or counterclockwise; tie is storyteller choice."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "pixie", "name": "小精灵", "officialName": "Pixie", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一个在场的镇民角色。如果你“疯狂”地证明你是该角色，当他死亡时你获得该角色的能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pixie.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Madness pressure; execution remains storyteller-confirmed."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-punish madness failure."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "balloonist", "name": "气球驾驶员", "officialName": "Balloonist", "team": "townsfolk", "abilityText": "每个夜晚，你会得知一名不同角色类型的玩家，直到场上所有的角色类型你都得知过一次。[+1 外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/balloonist.png", "inputKinds": ["player"], "setupImpact": ["Adds 1 Outsider; keep out of first normal templates unless manually adjusted."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "monk", "name": "僧侣", "officialName": "Monk", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择除你以外的一名玩家：当晚恶魔的负面能力对他无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/monk.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "huntsman", "name": "巡山人", "officialName": "Huntsman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名存活的玩家：如果你选中了落难少女，她会变成一个不在场的镇民角色。[+落难少女]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/huntsman.png", "inputKinds": ["player"], "setupImpact": ["Adds the Damsel; keep out of first normal templates unless Damsel path is intentional."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "seamstress", "name": "女裁缝", "officialName": "Seamstress", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择除你以外的两名玩家：你会得知他们是否为同一阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/seamstress.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "nightwatchman", "name": "守夜人", "officialName": "Nightwatchman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名玩家：他会得知你是守夜人。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/nightwatchman.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "artist", "name": "艺术家", "officialName": "Artist", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以私下询问说书人一个是非问题，你会得知该问题的答案。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/artist.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "alsaahir", "name": "戏法师", "officialName": "Alsaahir", "team": "townsfolk", "abilityText": "每个白天限一次，你可以公开猜测谁是爪牙，谁是恶魔。如果你猜对，善良阵营获胜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1719566536_197011_3260.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": ["Public correct Minion/Demon guess can win for good."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win is never auto-applied."]}),
  role({"id": "soldier", "name": "士兵", "officialName": "Soldier", "team": "townsfolk", "abilityText": "恶魔的负面能力对你无效。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/soldier.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["May gain last executed player ability; poisoned if that player was evil."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Gained ability and poison are manually tracked."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "damsel", "name": "落难少女", "officialName": "Damsel", "team": "outsider", "abilityText": "所有爪牙都知道落难少女在场。每局游戏限一次，任意爪牙可以公开猜测你是落难少女，如果猜对，你的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/damsel.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["Minion public guess can cause good team to lose."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Loss is never auto-applied."]}),
  role({"id": "plaguedoctor", "name": "瘟疫医生", "officialName": "Plague Doctor", "team": "outsider", "abilityText": "如果你死亡，说书人获得一个不在场的爪牙能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9614144308961_fe5074b8.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["On death, storyteller may gain an out-of-play Minion ability."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["ST-owned ability is manual, not a player state mutation."]}),
  role({"id": "hatter", "name": "帽匠", "officialName": "Hatter", "team": "outsider", "abilityText": "如果你死亡，当晚爪牙和恶魔玩家可以选择变成新的爪牙和恶魔角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202312/c_9723021341071_86da6df4.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["On death, Minions and Demons may choose new characters."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Role changes require explicit storyteller confirmation."]}),
  role({"id": "poisoner", "name": "投毒者", "officialName": "Poisoner", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：他在当晚和明天白天中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/poisoner.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "cerenovus", "name": "洗脑师", "officialName": "Cerenovus", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家和一个善良角色。他明天白天和夜晚需要“疯狂”地证明自己是这个角色，不然他可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cerenovus.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Madness pressure; execution remains storyteller-confirmed."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-punish madness failure."]}),
  role({"id": "pithag", "name": "麻脸巫婆", "officialName": "Pit-Hag", "team": "minion", "abilityText": "每个夜晚*，你要选择一名玩家和一个角色，如果该角色不在场，他变成该角色。如果因此创造了一个恶魔，当晚的死亡由说书人决定。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pit-hag.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["If a Demon is created, night deaths are storyteller-decided."], "identityChanges": ["May change a player into another role."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Identity changes take effect only after storyteller confirmation; do not auto-kill."]}),
  role({"id": "mastermind", "name": "主谋", "officialName": "Mastermind", "team": "minion", "abilityText": "如果恶魔因为死于处决而因此导致游戏结束时，再额外进行一个夜晚和一个白天。在那个白天如果有玩家被处决，他的阵营落败。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mastermind.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["May add one extra day after Demon execution would end the game."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss remains storyteller-confirmed."]}),
  role({"id": "pukka", "name": "普卡", "officialName": "Pukka", "team": "demon", "abilityText": "每个夜晚，你要选择一名玩家：他中毒。上个因你的能力中毒的玩家会死亡并恢复健康。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/pukka.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Poisons a new target; previous poisoned target dies and becomes healthy."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track previous Pukka poison manually before applying death."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["May kill; self-kill can make a Minion the new Imp."], "identityChanges": ["Imp star-pass can create a new Demon."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Star-pass identity change is manual."]}),
  role({"id": "nodashii", "name": "诺-达鲺", "officialName": "No Dashii", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。与你邻近的两名镇民中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/no_dashii.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Kills at night and poisons nearest two Townsfolk neighbors."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Neighbor poison depends on current living seating and character type."]}),
  role({"id": "legion", "name": "军团", "officialName": "Legion", "team": "demon", "abilityText": "每个夜晚*，可能有一名玩家死亡。如果一项提名只有邪恶玩家投票，投票无效。你也会被当作是爪牙。[半数以上玩家为军团]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/legion.png", "inputKinds": ["player"], "setupImpact": ["Requires majority Legion setup and Djinn handling; excluded from normal templates."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
  role({"id": "djinn", "name": "灯神", "officialName": "Djinn", "team": "fabled", "abilityText": "使用灯神的相克规则。所有玩家都会知道其内容。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/djinn.png", "inputKinds": ["none"], "setupImpact": ["Fabled rule: announce jinxes publicly; not a seated player role."], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": []}),
] as const satisfies readonly SmartRoleDefinition[]
