import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21285_26731.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = { id: string; name: string; officialName: string; team: RoleTeam; abilityText: string; iconPath?: string; inputKinds: readonly AbilityInputKind[]; setupImpact?: readonly string[]; possibleOutcomes?: readonly string[]; stateChanges?: readonly string[]; identityChanges?: readonly string[]; teamChanges?: readonly string[]; playerMessageTemplates?: readonly string[]; highRiskNotes?: readonly string[] }

function role(input: RoleInput): SmartRoleDefinition {
  return { id: input.id, name: input.name, officialName: input.officialName, team: input.team, abilityText: input.abilityText, iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`, inputKinds: input.inputKinds, knowledgeStatus: 'confirmed', research: research(input) }
}

function research(input: RoleInput): RoleResearchMetadata {
  return { edition: 'Bai Zhou Wei Shi', setupImpact: input.setupImpact ?? [], possibleOutcomes: input.possibleOutcomes ?? [], stateChanges: input.stateChanges ?? [], identityChanges: input.identityChanges ?? [], teamChanges: input.teamChanges ?? [], playerMessageTemplates: input.playerMessageTemplates ?? [], highRiskNotes: input.highRiskNotes ?? [], sourceUrls: [sourceUrl, rolesSourceUrl], reviewedAt }
}

export const baiZhouWeiShiRoles = [
  role({"id": "noble", "name": "贵族", "officialName": "Noble", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知三名玩家：其中有且只有一名玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/noble.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Learns three players with exactly one evil."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not compute candidates from hidden state without ST confirmation."]}),
  role({"id": "fisherman", "name": "渔夫", "officialName": "Fisherman", "team": "townsfolk", "abilityText": "每局游戏限一次，在白天时，你可以让说书人给你一些能帮助你的阵营获胜的建议。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fisherman.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Receives once-per-game advice."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["Advice draft: {advice}"], "highRiskNotes": ["AI can draft wording only."]}),
  role({"id": "daoke", "name": "刀客", "officialName": "Custom", "team": "townsfolk", "abilityText": "在你的首个夜晚，你得知一个在场的爪牙角色。每局游戏限一次，你可以在白天公开选择一名玩家：如果他是你得知的角色，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_5751437760171_79dd1401.jpg", "inputKinds": ["role", "player"], "setupImpact": [], "possibleOutcomes": ["First night learns an in-play Minion; once per game public shot may kill if target is that role."], "stateChanges": ["May kill public target once."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Track learned Minion role and public shot before suggesting death."]}),
  role({"id": "slayer", "name": "猎手", "officialName": "Slayer", "team": "townsfolk", "abilityText": "每局游戏限一次，你可以在白天时公开选择一名玩家：如果他是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/slayer.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Once per game public shot can kill Demon."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Target death requires ST confirmation."]}),
  role({"id": "bingbi", "name": "秉笔", "officialName": "Custom", "team": "townsfolk", "abilityText": "如果你在白天死亡，当晚你会得知一名善良玩家。如果你在夜晚死亡，当晚你会得知一名邪恶玩家。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_5918227760171_7f310c1b.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["If died by day, learns a good player; if died by night, learns an evil player."], "stateChanges": ["Trigger depends on exact day/night death timing."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Check phase of death before choosing information."]}),
  role({"id": "chiren", "name": "痴人", "officialName": "Custom", "team": "outsider", "abilityText": "如果你未“疯狂”地阻止你的阵营在巨大优势下获胜，你落败，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202403/c_1221328760171_3cc5eb2b.jpg", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["May lose if not madly preventing own team winning by a huge advantage."], "stateChanges": ["Madness-like social burden persists even after death."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Win/loss and huge-advantage judgment are ST discretion."]}),
  role({"id": "tixingguan", "name": "提刑官", "officialName": "Custom", "team": "townsfolk", "abilityText": "在你首次提名玩家后，你会在当晚得知他的角色。外来者会被你的能力当作爪牙或恶魔角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_7402377694761_cd9eb282.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": ["After first nomination, learns nominee character at night; Outsiders may register as Minion/Demon."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Registration exception requires ST review.", "版本注记：本剧本沿用剧本发布源版本（外来者会被当作爪牙或恶魔角色）；百科现行版方向相反——恶魔会被提刑官的能力当作善良角色（提名恶魔时向提刑官展示一个镇民或外来者标记），外来者如实展示。结算前请说书人确认本局采用的版本。"]}),
  role({"id": "oracle", "name": "神谕者", "officialName": "Oracle", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知有多少名死亡的玩家是邪恶的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/oracle.png", "inputKinds": ["number"], "setupImpact": [], "possibleOutcomes": ["Learns number of dead evil players."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Recluse and registration effects remain ST-confirmed."]}),
  role({"id": "langzhong", "name": "郎中", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你以外的一名玩家：你会得知一个与他能力相关的词语。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_9255777694761_7594675d.jpg", "inputKinds": ["player", "text"], "setupImpact": [], "possibleOutcomes": ["Chooses a player and learns a word related to their ability."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": ["You learn this ability-related word: {word}."], "highRiskNotes": ["Word choice is ST-authored; AI can draft wording only."]}),
  role({"id": "savant", "name": "博学者", "officialName": "Savant", "team": "townsfolk", "abilityText": "每个白天，你可以私下询问说书人以得知两条信息：一个是正确的，一个是错误的。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/savant.png", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Each day receives two statements, one true and one false."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Statements should be ST-authored."]}),
  role({"id": "fortuneteller", "name": "占卜师", "officialName": "Fortune Teller", "team": "townsfolk", "abilityText": "每个夜晚，你要选择两名玩家：你会得知他们之中是否有恶魔。会有一名善良玩家始终被你的能力当作恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/fortune_teller.png", "inputKinds": ["players"], "setupImpact": [], "possibleOutcomes": ["Returns yes/no across two selected players and red herring."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Red herring and poisoning/drunkenness affect answer; ST confirms."]}),
  role({"id": "jinyiwei", "name": "锦衣卫", "officialName": "Custom", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名玩家：如果他在下个黄昏前死亡，你代替他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_5878087694761_691045fa.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["If protected target dies before next dusk, Jinyiwei dies instead."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Replacement death requires confirmed timing/source.", "锦衣卫的能力在白天也能触发：处决、流放等白天造成的死亡同样会由锦衣卫代替目标死亡。", "原本的死亡效果被锦衣卫的能力阻止后，不会再继续触发因原本死亡而导致的一系列效果（如小恶魔自杀不会传位、方古的转化会被阻止）。", "已死亡的锦衣卫失去能力，锦衣卫只能成功保护目标玩家一次；如果目标的死亡被其他效果阻止或无法被锦衣卫阻止，锦衣卫的能力不触发，也不会导致锦衣卫死亡。"]}),
  role({"id": "chongfei", "name": "宠妃", "officialName": "Custom", "team": "townsfolk", "abilityText": "每局游戏限一次，说书人会在关于你的事情上打破规则。随后，你会秘密得知说书人为此做了什么。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202401/c_3373896816071_be9c7270.jpg", "inputKinds": ["text"], "setupImpact": [], "possibleOutcomes": ["Once per game ST breaks a rule about her, then secretly tells what was done."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Rule break is deliberate ST discretion; tool only records explanation.", "如果宠妃中毒或醉酒，说书人不能为宠妃打破规则；但说书人可以在宠妃即将中毒或醉酒时打破规则，让宠妃保持健康且清醒。", "在说书人为宠妃打破规则后，在宠妃的角色标记旁放置“失去能力”标记（每局限一次，已用尽）。"]}),
  role({"id": "atheist", "name": "无神论者", "officialName": "Atheist", "team": "townsfolk", "abilityText": "说书人可以打破游戏规则。如果说书人被处决，善良阵营获胜，即使你已死亡。[无邪恶角色在场]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/atheist.png", "inputKinds": ["text"], "setupImpact": ["No evil characters are in play; ST may break rules."], "possibleOutcomes": ["If ST is executed, good wins."], "stateChanges": [], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; this is a special game mode, not ordinary setup."]}),
  role({"id": "drunk", "name": "酒鬼", "officialName": "Drunk", "team": "outsider", "abilityText": "你不知道你是酒鬼。你以为你是一个镇民角色，但其实你不是。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/drunk.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Believes they are a Townsfolk but has no ability."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Hidden identity is manual; do not reveal true role in player-facing context."]}),
  role({"id": "recluse", "name": "陌客", "officialName": "Recluse", "team": "outsider", "abilityText": "你可能会被当作邪恶阵营、爪牙角色或恶魔角色，即使你已死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/recluse.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": [], "teamChanges": ["May register as evil, Minion or Demon even dead."], "playerMessageTemplates": [], "highRiskNotes": ["Registration is contextual; true team does not change."]}),
  role({"id": "golem", "name": "魔像", "officialName": "Golem", "team": "outsider", "abilityText": "每局游戏你只能发起提名一次。当你发起提名时，如果被你提名的玩家不是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/golem.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Can nominate once; if nominee is not Demon, nominee dies."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Nomination limit and death require manual record."]}),
  role({"id": "gudiao", "name": "蛊雕", "officialName": "Custom", "team": "minion", "abilityText": "蛊雕：每个夜晚，你要选择左或右：将你的飞行标记从当前位置移动到这个方向上的下一名存活善良玩家。他中毒且可能被当作邪恶阵营和爪牙角色，你会知道他原本的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202301/c_4078497694761_5c6ddcce.jpg", "inputKinds": ["text", "player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Moves flying marker left/right to next living good player; that player is poisoned and may register evil/Minion."], "identityChanges": [], "teamChanges": ["Target may register as evil/Minion but true alignment does not change."], "playerMessageTemplates": [], "highRiskNotes": ["Do not auto-move marker or poison/register target.", "版本注记：本剧本沿用剧本发布源的旧自制版文本（每晚自选左右、目标为存活善良玩家）；百科现行版为：每晚得知顺时针方向下一名存活镇民玩家的角色（其他类型或已死亡玩家被跳过），他中毒且同时判定角色与阵营时只能被当作“邪恶的蛊雕”，持续到下个黄昏；每局游戏限一次可在夜晚改变方向。结算前请说书人确认本局采用的版本。"]}),
  role({"id": "mezepheles", "name": "灵言师", "officialName": "Mezepheles", "team": "minion", "abilityText": "在你的首个夜晚，你会得知一个关键词。首个说出该关键词的善良玩家会在当晚转变为邪恶阵营。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mezepheles.png", "inputKinds": ["text", "player"], "setupImpact": [], "possibleOutcomes": ["Learns a keyword on first night."], "stateChanges": [], "identityChanges": [], "teamChanges": ["First good player to say keyword becomes evil that night."], "playerMessageTemplates": [], "highRiskNotes": ["Keyword trigger and alignment change are manual; check extra-evil limits."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["none"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": [], "identityChanges": ["If Demon dies with five or more players alive, becomes that Demon."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Demon pass is manual and depends on living count."]}),
  role({"id": "psychopath", "name": "精神病患者", "officialName": "Psychopath", "team": "minion", "abilityText": "每个白天，在提名开始前，你可以公开选择一名玩家：他死亡。如果你被处决，提名你的玩家需要和你猜拳，只有你输了你才会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/psychopath.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Can publicly choose a player to die before nominations; execution may require roshambo."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Day death and roshambo survival are manual."]}),
  role({"id": "hundun", "name": "混沌", "officialName": "Custom", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式杀死了一名与你邻近的镇民玩家，除旅行者外的所有善良玩家会中毒直到下个黄昏。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_9149178608961_89693def.jpg", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Kills nightly; if kills neighboring Townsfolk, all good players except Travellers are poisoned until next dusk."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Neighbor/Townsfolk check and mass poison are ST-confirmed."]}),
  role({"id": "imp", "name": "小恶魔", "officialName": "Imp", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。如果你以这种方式自杀，一名爪牙会变成小恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/imp.png", "inputKinds": ["player"], "setupImpact": [], "possibleOutcomes": [], "stateChanges": ["Each night may kill one player."], "identityChanges": ["If Imp kills self this way, a Minion may become Imp."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Self-kill pass must be confirmed."]}),
  role({"id": "kazali", "name": "卡扎力", "officialName": "Kazali", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。[由你决定谁是什么爪牙，-或+任意数量外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202312/c_7795403383071_0f9107d8.jpg", "inputKinds": ["player", "players", "role"], "setupImpact": ["At setup, Kazali chooses which players are which Minions.", "May add or remove any number of Outsiders."], "possibleOutcomes": [], "stateChanges": ["Each other night chooses a player to die."], "identityChanges": ["Opening Minion assignments are storyteller-confirmed."], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Kept out of first normal templates; no automatic identity or outsider-count changes."]}),
  role({"id": "yaggababble", "name": "牙噶巴卜", "officialName": "Yaggababble", "team": "demon", "abilityText": "在你的首个夜晚，你会得知一段秘密短语。每次你在白天公开说出这段短语，当天便可能会有一名玩家在这之后死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202402/c_9719440568071_03aa8062.jpg", "inputKinds": ["text", "number", "player"], "setupImpact": [], "possibleOutcomes": ["Learns a secret phrase; for each public utterance today, a player might die."], "stateChanges": ["May cause deaths after public phrase use."], "identityChanges": [], "teamChanges": [], "playerMessageTemplates": [], "highRiskNotes": ["Do not listen to chat or auto-count phrase; ST records count and deaths."]}),
] as const satisfies readonly SmartRoleDefinition[]
