import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "bai-zhou-wei-shi"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const baiZhouWeiShiSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["langzhong", "savant", "fortuneteller", "jinyiwei", "chongfei", "psychopath", "imp"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["noble", "fisherman", "daoke", "slayer", "bingbi", "gudiao", "hundun"], bluffs: ["tixingguan", "oracle", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "mezepheles", "yaggababble"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["savant", "fortuneteller", "jinyiwei", "chongfei", "noble", "drunk", "gudiao", "yaggababble"], bluffs: ["fisherman", "daoke", "slayer"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["fisherman", "daoke", "slayer", "bingbi", "tixingguan", "recluse", "mezepheles", "imp"], bluffs: ["noble", "oracle", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["fortuneteller", "jinyiwei", "chongfei", "noble", "fisherman", "recluse", "golem", "mezepheles", "hundun"], bluffs: ["daoke", "slayer", "bingbi"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["daoke", "slayer", "bingbi", "tixingguan", "oracle", "golem", "chiren", "scarletwoman", "yaggababble"], bluffs: ["noble", "fisherman", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["jinyiwei", "chongfei", "noble", "fisherman", "daoke", "slayer", "bingbi", "scarletwoman", "psychopath", "imp"], bluffs: ["tixingguan", "oracle", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["slayer", "bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "psychopath", "gudiao", "hundun"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["savant", "fortuneteller", "jinyiwei", "chongfei", "noble", "fisherman", "daoke", "gudiao", "mezepheles", "yaggababble"], bluffs: ["slayer", "bingbi", "tixingguan"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["chongfei", "noble", "fisherman", "daoke", "slayer", "bingbi", "tixingguan", "chiren", "psychopath", "gudiao", "yaggababble"], bluffs: ["oracle", "langzhong", "savant"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "jinyiwei", "drunk", "gudiao", "mezepheles", "imp"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["noble", "fisherman", "daoke", "slayer", "bingbi", "tixingguan", "oracle", "drunk", "recluse", "gudiao", "mezepheles", "hundun"], bluffs: ["langzhong", "savant", "fortuneteller"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "jinyiwei", "chongfei", "recluse", "golem", "mezepheles", "scarletwoman", "yaggababble"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["jinyiwei", "chongfei", "noble", "fisherman", "daoke", "slayer", "bingbi", "golem", "chiren", "scarletwoman", "psychopath", "imp"], bluffs: ["tixingguan", "oracle", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["fisherman", "daoke", "slayer", "bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "mezepheles", "scarletwoman", "psychopath", "imp"], bluffs: ["noble", "jinyiwei", "chongfei"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["oracle", "langzhong", "savant", "fortuneteller", "jinyiwei", "chongfei", "noble", "fisherman", "daoke", "scarletwoman", "psychopath", "gudiao", "hundun"], bluffs: ["slayer", "bingbi", "tixingguan"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["daoke", "slayer", "bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "jinyiwei", "golem", "scarletwoman", "psychopath", "gudiao", "yaggababble"], bluffs: ["noble", "fisherman", "chongfei"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["langzhong", "savant", "fortuneteller", "jinyiwei", "chongfei", "noble", "fisherman", "daoke", "slayer", "chiren", "psychopath", "gudiao", "mezepheles", "imp"], bluffs: ["bingbi", "tixingguan", "oracle"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["slayer", "bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "jinyiwei", "chongfei", "chiren", "drunk", "psychopath", "gudiao", "mezepheles", "hundun"], bluffs: ["noble", "fisherman", "daoke"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["savant", "fortuneteller", "jinyiwei", "chongfei", "noble", "fisherman", "daoke", "slayer", "bingbi", "drunk", "recluse", "gudiao", "mezepheles", "scarletwoman", "yaggababble"], bluffs: ["tixingguan", "oracle", "langzhong"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["fisherman", "daoke", "slayer", "bingbi", "tixingguan", "oracle", "langzhong", "savant", "fortuneteller", "recluse", "golem", "mezepheles", "scarletwoman", "psychopath", "imp"], bluffs: ["noble", "jinyiwei", "chongfei"], note: "Verified setup; Atheist and Kazali special setup paths stay out of normal templates; Mezepheles, Scarlet Woman, Jinyiwei, Gudiao, Hundun, Yaggababble, Chiren and Golem outcomes remain ST-confirmed." }),
]
