import type { SmartRoleDefinition } from './types'

const localCharacterPrefix = '/assets/characters/'

const preferredCharacterExtensions: Readonly<Record<string, string>> = {
  "alchemist": ".webp",
  "alsaahir": ".webp",
  "amnesiac": ".webp",
  "aohe": ".jpg",
  "apprentice": ".webp",
  "artist": ".webp",
  "assassin": ".webp",
  "balloonist": ".webp",
  "banshee": ".png",
  "barber": ".webp",
  "barista": ".webp",
  "baron": ".webp",
  "beggar": ".webp",
  "bingbi": ".jpg",
  "bishop": ".webp",
  "boffin": ".webp",
  "bonecollector": ".webp",
  "boomdandy": ".webp",
  "bureaucrat": ".webp",
  "butcher": ".webp",
  "butler": ".webp",
  "cailianjun": ".png",
  "cannibal": ".webp",
  "cerenovus": ".webp",
  "chambermaid": ".webp",
  "chef": ".webp",
  "clockmaker": ".webp",
  "courtier": ".webp",
  "cultleader": ".webp",
  "dagengren": ".jpg",
  "damsel": ".webp",
  "daoke": ".png",
  "daoshi": ".jpg",
  "deviant": ".webp",
  "devilsadvocate": ".webp",
  "dianxiaoer": ".jpg",
  "dianyuzhang": ".jpg",
  "dreamer": ".webp",
  "drunk": ".webp",
  "empath": ".webp",
  "eviltwin": ".webp",
  "exorcist": ".webp",
  "fanggu": ".webp",
  "farmer": ".webp",
  "fengshuishi": ".jpg",
  "fisherman": ".webp",
  "flowergirl": ".webp",
  "fool": ".webp",
  "fortuneteller": ".webp",
  "gambler": ".webp",
  "ganshiren": ".jpg",
  "geling": ".jpg",
  "general": ".webp",
  "goblin": ".webp",
  "godfather": ".webp",
  "golem": ".webp",
  "goon": ".webp",
  "gossip": ".webp",
  "grandmother": ".webp",
  "gudiao": ".jpg",
  "gunslinger": ".webp",
  "harlot": ".webp",
  "harpy": ".webp",
  "hatter": ".png",
  "heshang": ".jpg",
  "highpriestess": ".webp",
  "hu_mei_niang": ".jpg",
  "huntsman": ".webp",
  "imp": ".webp",
  "innkeeper": ".webp",
  "investigator": ".webp",
  "jianning": ".jpg",
  "jiaohuazi": ".jpg",
  "jinweijun2": ".jpg",
  "jingzhongmo": ".png",
  "jiubao": ".jpg",
  "judge": ".webp",
  "juggler": ".webp",
  "kazali": ".webp",
  "klutz": ".webp",
  "knight": ".webp",
  "langzhong": ".jpg",
  "legion": ".webp",
  "librarian": ".webp",
  "lleech": ".webp",
  "limao": ".jpg",
  "lunatic": ".webp",
  "lycanthrope": ".webp",
  "magician": ".webp",
  "marionette": ".webp",
  "mastermind": ".webp",
  "mathematician": ".webp",
  "matron": ".webp",
  "mayor": ".webp",
  "mezepheles": ".webp",
  "minstrel": ".webp",
  "monk": ".webp",
  "moonchild": ".webp",
  "mutant": ".webp",
  "nightwatchman": ".webp",
  "noble": ".webp",
  "nodashii": ".webp",
  "ogre": ".webp",
  "ojo": ".webp",
  "oracle": ".webp",
  "pacifist": ".webp",
  "philosopher": ".webp",
  "pithag": ".webp",
  "pixie": ".webp",
  "plague_doctor": ".png",
  "plaguedoctor": ".webp",
  "po": ".webp",
  "poisoner": ".webp",
  "politician": ".webp",
  "poppygrower": ".webp",
  "preacher": ".webp",
  "professor": ".webp",
  "psychopath": ".webp",
  "pukka": ".webp",
  "puzzlemaster": ".webp",
  "qintianjian": ".jpg",
  "qiongqi": ".jpg",
  "ravenkeeper": ".webp",
  "recluse": ".webp",
  "riot": ".webp",
  "sage": ".webp",
  "sailor": ".webp",
  "saint": ".webp",
  "sao_ba_xing": ".jpg",
  "savant": ".webp",
  "scapegoat": ".webp",
  "scarletwoman": ".webp",
  "seamstress": ".webp",
  "shabaloth": ".webp",
  "shaxing": ".jpg",
  "shugenja": ".webp",
  "shusheng": ".jpg",
  "si_huo_shang_ren": ".jpg",
  "simin": ".jpg",
  "slayer": ".webp",
  "snakecharmer": ".webp",
  "snitch": ".webp",
  "soldier": ".webp",
  "spiritofivory": ".webp",
  "spy": ".webp",
  "steward": ".webp",
  "stormcatcher": ".webp",
  "summoner": ".webp",
  "sweetheart": ".webp",
  "taotie": ".jpg",
  "tealady": ".webp",
  "thief": ".webp",
  "tinker": ".webp",
  "tixingguan": ".jpg",
  "towncrier": ".webp",
  "undertaker": ".webp",
  "vigormortis": ".webp",
  "villageidiot": ".webp",
  "virgin": ".webp",
  "vizier": ".webp",
  "vortox": ".webp",
  "voudon": ".webp",
  "washerwoman": ".webp",
  "widow": ".webp",
  "witch": ".webp",
  "wudaozhe": ".jpg",
  "yaggababble": ".webp",
  "yangguren": ".jpg",
  "yanluo": ".jpg",
  "yinluren": ".jpg",
  "yinyangshi": ".jpg",
  "yongjiang": ".jpg",
  "zombuul": ".webp",
}

function extensionFromUrl(url: string) {
  const pathname = new URL(url).pathname
  const extension = pathname.slice(pathname.lastIndexOf('.')).toLowerCase()
  return /^\.(?:png|jpe?g|webp|gif|svg)$/.test(extension) ? extension : '.png'
}

function isCommunityLocalRole(role: SmartRoleDefinition) {
  return role.research?.sourceUrls.some((url) =>
    url.includes('oss.gstonegames.com') || url.includes('clocktower.gstonegames.com'),
  ) ?? false
}

export function resolveCharacterIconPath(role: SmartRoleDefinition) {
  const preferredExtension = preferredCharacterExtensions[role.id]
  if (preferredExtension) return `${localCharacterPrefix}${role.id}${preferredExtension}`

  const iconPath = role.iconPath ?? `${localCharacterPrefix}${role.id}.webp`
  if (/^https?:\/\//.test(iconPath)) {
    return `${localCharacterPrefix}${role.id}${extensionFromUrl(iconPath)}`
  }
  if (iconPath.startsWith(localCharacterPrefix) && iconPath.endsWith('.webp') && isCommunityLocalRole(role)) {
    return `${localCharacterPrefix}${role.id}.png`
  }
  return iconPath
}
