import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "sheng-shi-qi-wen"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const shengShiQiWenSetupTemplates: readonly SetupTemplate[] = [
  template({"id": "steady", "count": 7, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "chimei", "qiongqi"], "bluffs": ["dagengren", "wushiren", "heshang"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 7, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "panguan", "qiongqi"], "bluffs": ["wushiren", "dagengren", "lingren"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 7, "style": "chaos", "roles": ["qianke", "heshang", "dagengren", "langzhong", "yinyangshi", "panguan", "dianyuzhang"], "bluffs": ["zhanxingzhe", "tixingguan", "fengshuishi"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 8, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "jiubao", "chimei", "qiongqi"], "bluffs": ["dagengren", "wushiren", "heshang"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 8, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "rulianshi", "panguan", "qiongqi"], "bluffs": ["wushiren", "dagengren", "lingren"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 9, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "jiubao", "shijie", "chimei", "qiongqi"], "bluffs": ["dagengren", "wushiren", "heshang"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 9, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "rulianshi", "shusheng", "panguan", "qiongqi"], "bluffs": ["wushiren", "dagengren", "lingren"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 10, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "chimei", "jinweijun", "qiongqi"], "bluffs": ["heshang", "langzhong", "qianke"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 10, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "panguan", "jinweijun", "qiongqi"], "bluffs": ["lingren", "fengshuishi", "tixingguan"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 10, "style": "chaos", "roles": ["qianke", "heshang", "dagengren", "langzhong", "yinyangshi", "zhanxingzhe", "tixingguan", "panguan", "chimei", "dianyuzhang"], "bluffs": ["fengshuishi", "lingren", "wushiren"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 11, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "jiubao", "chimei", "jinweijun", "qiongqi"], "bluffs": ["heshang", "langzhong", "qianke"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 11, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "rulianshi", "panguan", "jinweijun", "qiongqi"], "bluffs": ["lingren", "fengshuishi", "tixingguan"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 12, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "jiubao", "shijie", "chimei", "jinweijun", "qiongqi"], "bluffs": ["heshang", "langzhong", "qianke"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 12, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "rulianshi", "shusheng", "panguan", "jinweijun", "qiongqi"], "bluffs": ["lingren", "fengshuishi", "tixingguan"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 12, "style": "chaos", "roles": ["qianke", "heshang", "dagengren", "langzhong", "yinyangshi", "zhanxingzhe", "tixingguan", "shusheng", "rulianshi", "panguan", "chimei", "dianyuzhang"], "bluffs": ["fengshuishi", "lingren", "wushiren"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 13, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "heshang", "langzhong", "chimei", "jinweijun", "panguan", "qiongqi"], "bluffs": ["qianke", "yinyangshi", "dianxiaoer"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 13, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "lingren", "fengshuishi", "panguan", "jinweijun", "chimei", "qiongqi"], "bluffs": ["tixingguan", "banxian", "zhanxingzhe"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 14, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "heshang", "langzhong", "jiubao", "chimei", "jinweijun", "panguan", "qiongqi"], "bluffs": ["qianke", "yinyangshi", "dianxiaoer"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 14, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "lingren", "fengshuishi", "rulianshi", "panguan", "jinweijun", "chimei", "qiongqi"], "bluffs": ["tixingguan", "banxian", "zhanxingzhe"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "steady", "count": 15, "style": "balanced", "roles": ["zhanxingzhe", "banxian", "tixingguan", "fengshuishi", "lingren", "dagengren", "wushiren", "heshang", "langzhong", "jiubao", "shijie", "chimei", "jinweijun", "panguan", "qiongqi"], "bluffs": ["qianke", "yinyangshi", "dianxiaoer"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "redirect", "count": 15, "style": "long-game", "roles": ["dianxiaoer", "yinyangshi", "qianke", "langzhong", "heshang", "wushiren", "dagengren", "lingren", "fengshuishi", "rulianshi", "shusheng", "panguan", "jinweijun", "chimei", "qiongqi"], "bluffs": ["tixingguan", "banxian", "zhanxingzhe"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
  template({"id": "pressure", "count": 15, "style": "chaos", "roles": ["qianke", "heshang", "dagengren", "langzhong", "yinyangshi", "zhanxingzhe", "tixingguan", "fengshuishi", "lingren", "shusheng", "rulianshi", "panguan", "chimei", "jinweijun", "dianyuzhang"], "bluffs": ["wushiren", "banxian", "dianxiaoer"], "note": "Verified normal setup; Xi Zi, Tao Wu, Shi Meng Mo and Niang Jiu Shi setup-changing paths stay manual. Custom deaths, redirections, drunk/poison and alignment/identity shifts are AI suggestions only."}),
]
