import type { AbilityInputKind, RoleResearchMetadata, RoleTeam, SmartRoleDefinition } from '../../types'

const sourceUrl = "https://oss.gstonegames.com/data_file/clocktower/json/ct_edition_21685_36800.json"
const rolesSourceUrl = 'https://clocktower.gstonegames.com/ct/grimoireRoleJson/'
const reviewedAt = '2026-07-22'

type RoleInput = {
  id: string
  name: string
  officialName: string
  team: RoleTeam
  abilityText: string
  iconPath?: string
  inputKinds: readonly AbilityInputKind[]
  setupImpact?: readonly string[]
  possibleOutcomes?: readonly string[]
  stateChanges?: readonly string[]
  identityChanges?: readonly string[]
  teamChanges?: readonly string[]
  playerMessageTemplates?: readonly string[]
  highRiskNotes?: readonly string[]
}

function role(input: RoleInput): SmartRoleDefinition {
  return {
    id: input.id,
    name: input.name,
    officialName: input.officialName,
    team: input.team,
    abilityText: input.abilityText,
    iconPath: input.iconPath ?? `/assets/characters/${input.id}.webp`,
    inputKinds: input.inputKinds,
    knowledgeStatus: 'confirmed',
    research: research(input),
  }
}

function research(input: RoleInput): RoleResearchMetadata {
  return {
    edition: "信口雌黄",
    setupImpact: input.setupImpact ?? [],
    possibleOutcomes: input.possibleOutcomes ?? [],
    stateChanges: input.stateChanges ?? [],
    identityChanges: input.identityChanges ?? [],
    teamChanges: input.teamChanges ?? [],
    playerMessageTemplates: input.playerMessageTemplates ?? [],
    highRiskNotes: input.highRiskNotes ?? [],
    sourceUrls: [sourceUrl, rolesSourceUrl],
    reviewedAt,
  }
}

export const xinKouCiHuangRoles = [
  role({"id": "grandmother", "name": "祖母", "officialName": "Grandmother", "team": "townsfolk", "abilityText": "在你的首个夜晚，你会得知一名善良玩家和他的角色。如果恶魔杀死了他，你也会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/grandmother.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 祖母. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "dreamer", "name": "筑梦师", "officialName": "Dreamer", "team": "townsfolk", "abilityText": "每个夜晚，你要选择除你及旅行者以外的一名玩家：你会得知一个善良角色和一个邪恶角色，该玩家是其中一个角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/dreamer.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "playerMessageTemplates": ["You are 筑梦师. Wait for the Storyteller to provide the current information."]}),
  role({"id": "undertaker", "name": "送葬者", "officialName": "Undertaker", "team": "townsfolk", "abilityText": "每个夜晚*，你会得知今天白天死于处决的玩家的角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/undertaker.png", "inputKinds": ["none"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 送葬者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "lycanthrope", "name": "半兽人", "officialName": "Lycanthrope", "team": "townsfolk", "abilityText": "每个夜晚*，你要选择一名存活的玩家，如果他是善良的，他死亡，并且当晚不会再有其他玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/lycanthrope.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 半兽人. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "gossip", "name": "造谣者", "officialName": "Gossip", "team": "townsfolk", "abilityText": "每个白天，你可以公开发表一个声明。如果该声明正确，在当晚会有一名玩家死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/gossip.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 造谣者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "virgin", "name": "贞洁者", "officialName": "Virgin", "team": "townsfolk", "abilityText": "当你首次被提名时，如果提名你的玩家是镇民，他立刻被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/virgin.png", "inputKinds": ["text"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "playerMessageTemplates": ["You are 贞洁者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "cannibal", "name": "食人族", "officialName": "Cannibal", "team": "townsfolk", "abilityText": "你拥有上个死于处决的玩家的能力。如果该玩家属于邪恶阵营，你中毒直到下个善良玩家死于处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/cannibal.png", "inputKinds": ["none"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May apply or remove poisoned state.", "May cause, prevent, delay, or disguise death."], "teamChanges": ["May affect alignment or win/loss judgment."], "playerMessageTemplates": ["You are 食人族. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "philosopher", "name": "哲学家", "officialName": "Philosopher", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个善良角色：你获得该角色的能力。如果这个角色在场，他醉酒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/philosopher.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply drunk state or make an ability fail."], "playerMessageTemplates": ["You are 哲学家. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "slayer", "name": "猎手", "officialName": "Slayer", "team": "townsfolk", "abilityText": "每局游戏限一次，你可以在白天时公开选择一名玩家：如果他是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/slayer.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 猎手. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "nightwatchman", "name": "守夜人", "officialName": "Nightwatchman", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一名玩家：他会得知你是守夜人。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/nightwatchman.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "playerMessageTemplates": ["You are 守夜人. Wait for the Storyteller to provide the current information."]}),
  role({"id": "courtier", "name": "侍臣", "officialName": "Courtier", "team": "townsfolk", "abilityText": "每局游戏限一次，在夜晚时，你可以选择一个角色：如果该角色在场，该角色之一从当晚开始醉酒三天三夜。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/courtier.png", "inputKinds": ["player", "role"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply drunk state or make an ability fail."], "playerMessageTemplates": ["You are 侍臣. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "banshee", "name": "报丧女妖", "officialName": "Banshee", "team": "townsfolk", "abilityText": "如果恶魔杀死了你，所有玩家都会得知此事。从现在开始，你每天可以发起两次提名，每次投票时可以投两票。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1728367972_197011_575.png", "inputKinds": ["text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 报丧女妖. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically.", "只有报丧女妖被恶魔杀死且此时清醒健康，能力才会触发；如果她在被恶魔杀死的时候醉酒或中毒，或是被恶魔以外的能力杀死，说书人不会宣布她的能力被触发，她无法发起提名且投票需要消耗投票标记。", "如果报丧女妖在获得死亡能力时清醒健康，但在随后醉酒中毒，她无法发起提名，且投票需要消耗投票标记。", "报丧女妖觉醒后，即使所有善良玩家都已死亡，游戏继续——善良阵营仍可能因报丧女妖还能发起提名而获胜。"]}),
  role({"id": "farmer", "name": "农夫", "officialName": "Farmer", "team": "townsfolk", "abilityText": "如果你在夜晚死亡，一名存活的善良玩家会变成农夫。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/farmer.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "identityChanges": ["May involve character, registration, or special alive/dead state changes."], "playerMessageTemplates": ["You are 农夫. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "hatter", "name": "帽匠", "officialName": "Hatter", "team": "outsider", "abilityText": "如果你死亡，当晚爪牙和恶魔玩家可以选择变成新的爪牙和恶魔角色。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202312/c_9723021341071_86da6df4.jpg", "inputKinds": ["player", "role"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "identityChanges": ["May involve character, registration, or special alive/dead state changes."], "playerMessageTemplates": ["You are 帽匠. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically.", "只有帽匠死亡时清醒健康，才会触发当晚的茶会。", "如果帽匠在夜晚时由于恶魔的攻击而死亡，在茶会中产生的新恶魔在当晚无法再次攻击。", "角色不可重复：如果某名玩家选择变成了一个已在场的角色，那个角色对应的玩家必须选择变成一个新的角色。"]}),
  role({"id": "tinker", "name": "修补匠", "officialName": "Tinker", "team": "outsider", "abilityText": "你随时可能死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/tinker.png", "inputKinds": ["none"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 修补匠. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "mutant", "name": "畸形秀演员", "officialName": "Mutant", "team": "outsider", "abilityText": "如果你“疯狂”地证明自己是外来者，你可能被处决。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/mutant.png", "inputKinds": ["none"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May create madness pressure that must be judged by the Storyteller."], "playerMessageTemplates": ["You are 畸形秀演员. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "golem", "name": "魔像", "officialName": "Golem", "team": "outsider", "abilityText": "每局游戏你只能发起提名一次。当你发起提名时，如果被你提名的玩家不是恶魔，他死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/golem.png", "inputKinds": ["text"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 魔像. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically."]}),
  role({"id": "boffin", "name": "科学怪人", "officialName": "Boffin", "team": "minion", "abilityText": "恶魔拥有一个不在场的善良角色的能力，即使他醉酒或中毒。你和他都知道他获得了什么能力。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/1728367972_197011_5602.png", "inputKinds": ["none"], "setupImpact": ["科学怪人 has setup or composition impact; Storyteller confirms before play."], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply or remove poisoned state.", "May apply drunk state or make an ability fail."], "playerMessageTemplates": ["You are 科学怪人. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically."]}),
  role({"id": "poisoner", "name": "投毒者", "officialName": "Poisoner", "team": "minion", "abilityText": "每个夜晚，你要选择一名玩家：他在当晚和明天白天中毒。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/poisoner.png", "inputKinds": ["player"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May apply or remove poisoned state."], "playerMessageTemplates": ["You are 投毒者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "scarletwoman", "name": "红唇女郎", "officialName": "Scarlet Woman", "team": "minion", "abilityText": "如果大于等于五名玩家存活时（旅行者不计算在内）恶魔死亡，你变成那个恶魔。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/scarlet_woman.png", "inputKinds": ["none"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "identityChanges": ["May involve character, registration, or special alive/dead state changes."], "playerMessageTemplates": ["You are 红唇女郎. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "psychopath", "name": "精神病患者", "officialName": "Psychopath", "team": "minion", "abilityText": "每个白天，在提名开始前，你可以公开选择一名玩家：他死亡。如果你被处决，提名你的玩家需要和你猜拳，只有你输了你才会死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/role_icon/psychopath.png", "inputKinds": ["player", "text"], "possibleOutcomes": ["Record trigger state, targets, and information given by the Storyteller."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 精神病患者. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically."]}),
  role({"id": "yaggababble", "name": "牙噶巴卜", "officialName": "Yaggababble", "team": "demon", "abilityText": "在你的首个夜晚，你会得知一段秘密短语。每次你在白天公开说出这段短语，当天便可能会有一名玩家在这之后死亡。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202402/c_9719440568071_03aa8062.jpg", "inputKinds": ["player", "number", "text"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 牙噶巴卜. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically."]}),
  role({"id": "ojo", "name": "奥赫", "officialName": "Ojo", "team": "demon", "abilityText": "每个夜晚*，你要选择一个角色：他死亡。如果该角色不在场，则由说书人来决定谁会被你杀死。", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202310/c_6886084308961_f221dd48.jpg", "inputKinds": ["player", "role"], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 奥赫. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation."]}),
  role({"id": "lordoftyphon", "name": "堤丰之首", "officialName": "Lord of Typhon", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。[邪恶玩家全部邻座，你靠近正中，+1爪牙，-或+任意数量外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202408/c_3707150105271_e57fc482.jpg", "inputKinds": ["players"], "setupImpact": ["堤丰之首 has setup or composition impact; Storyteller confirms before play."], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 堤丰之首. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically."]}),
  role({"id": "kazali", "name": "卡扎力", "officialName": "Kazali", "team": "demon", "abilityText": "每个夜晚*，你要选择一名玩家：他死亡。[由你决定谁是什么爪牙，-或+任意数量外来者]", "iconPath": "https://oss.gstonegames.com/data_file/clocktower/upload/202312/c_7795403383071_0f9107d8.jpg", "inputKinds": ["players"], "setupImpact": ["卡扎力 has setup or composition impact; Storyteller confirms before play."], "possibleOutcomes": ["Use the source night reminder to record choices, results, and player-facing information."], "stateChanges": ["May cause, prevent, delay, or disguise death."], "playerMessageTemplates": ["You are 卡扎力. Wait for the Storyteller to provide the current information."], "highRiskNotes": ["Draft reminder only; authoritative state changes require explicit Storyteller confirmation.", "High-risk role; use AI as a checklist and do not apply results automatically.", "卡扎力不能选择让多名玩家变成同一个爪牙角色；他进行的选择次数等同于初始设置的爪牙数量。", "如果卡扎力在游戏中途被创造，他不会选择玩家成为新的爪牙。"]}),
] as const satisfies readonly SmartRoleDefinition[]
