import type { PlayerCount, RoleId, SetupTemplate, SetupTemplateStyle } from '../../types'

const scriptId = "wang-bu-jian-wang"

type TemplateInput = { id: string; count: PlayerCount; style: SetupTemplateStyle; roles: readonly RoleId[]; bluffs: readonly RoleId[]; note: string }

function template(input: TemplateInput): SetupTemplate {
  return { templateId: `${scriptId}-${input.count}-${input.id}`, scriptId, playerCount: input.count, style: input.style, roles: input.roles, bluffs: input.bluffs, notes: [input.note], verified: true }
}

export const wangBuJianWangSetupTemplates: readonly SetupTemplate[] = [
  template({ id: "steady", count: 7, style: "balanced", roles: ["empath", "dreamer", "chef", "investigator", "banshee", "spy", "alhadikhia"], bluffs: ["librarian", "fisherman", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 7, style: "long-game", roles: ["dreamer", "chef", "investigator", "banshee", "librarian", "marionette", "alhadikhia"], bluffs: ["fisherman", "seamstress", "plaguedoctor"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 7, style: "chaos", roles: ["chef", "investigator", "banshee", "librarian", "fisherman", "poisoner", "alhadikhia"], bluffs: ["seamstress", "savant", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 8, style: "balanced", roles: ["dreamer", "chef", "investigator", "banshee", "librarian", "barber", "marionette", "alhadikhia"], bluffs: ["fisherman", "seamstress", "plaguedoctor"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 8, style: "long-game", roles: ["chef", "investigator", "banshee", "librarian", "fisherman", "recluse", "poisoner", "alhadikhia"], bluffs: ["seamstress", "savant", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 9, style: "balanced", roles: ["chef", "investigator", "banshee", "librarian", "fisherman", "recluse", "sweetheart", "poisoner", "alhadikhia"], bluffs: ["seamstress", "savant", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 9, style: "long-game", roles: ["investigator", "banshee", "librarian", "fisherman", "seamstress", "sweetheart", "plaguedoctor", "harpy", "alhadikhia"], bluffs: ["savant", "alsaahir", "general"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 10, style: "balanced", roles: ["investigator", "banshee", "librarian", "fisherman", "seamstress", "savant", "alsaahir", "harpy", "spy", "alhadikhia"], bluffs: ["general", "empath", "dreamer"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 10, style: "long-game", roles: ["banshee", "librarian", "fisherman", "seamstress", "savant", "alsaahir", "general", "spy", "marionette", "alhadikhia"], bluffs: ["empath", "dreamer", "chef"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 10, style: "chaos", roles: ["librarian", "fisherman", "seamstress", "savant", "alsaahir", "general", "empath", "marionette", "poisoner", "alhadikhia"], bluffs: ["dreamer", "chef", "investigator"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 11, style: "balanced", roles: ["banshee", "librarian", "fisherman", "seamstress", "savant", "alsaahir", "general", "plaguedoctor", "spy", "marionette", "alhadikhia"], bluffs: ["empath", "dreamer", "chef"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 11, style: "long-game", roles: ["librarian", "fisherman", "seamstress", "savant", "alsaahir", "general", "empath", "drunk", "marionette", "poisoner", "alhadikhia"], bluffs: ["dreamer", "chef", "investigator"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 12, style: "balanced", roles: ["librarian", "fisherman", "seamstress", "savant", "alsaahir", "general", "empath", "drunk", "barber", "marionette", "poisoner", "alhadikhia"], bluffs: ["dreamer", "chef", "investigator"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 12, style: "long-game", roles: ["fisherman", "seamstress", "savant", "alsaahir", "general", "empath", "dreamer", "barber", "recluse", "poisoner", "harpy", "alhadikhia"], bluffs: ["chef", "investigator", "banshee"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 12, style: "chaos", roles: ["seamstress", "savant", "alsaahir", "general", "empath", "dreamer", "chef", "recluse", "sweetheart", "harpy", "spy", "alhadikhia"], bluffs: ["investigator", "banshee", "librarian"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 13, style: "balanced", roles: ["fisherman", "seamstress", "savant", "alsaahir", "general", "empath", "dreamer", "chef", "investigator", "poisoner", "harpy", "spy", "alhadikhia"], bluffs: ["banshee", "librarian", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 13, style: "long-game", roles: ["seamstress", "savant", "alsaahir", "general", "empath", "dreamer", "chef", "investigator", "banshee", "harpy", "spy", "marionette", "alhadikhia"], bluffs: ["librarian", "fisherman", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 14, style: "balanced", roles: ["seamstress", "savant", "alsaahir", "general", "empath", "dreamer", "chef", "investigator", "banshee", "recluse", "harpy", "spy", "marionette", "alhadikhia"], bluffs: ["librarian", "fisherman", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 14, style: "long-game", roles: ["savant", "alsaahir", "general", "empath", "dreamer", "chef", "investigator", "banshee", "librarian", "sweetheart", "spy", "marionette", "poisoner", "alhadikhia"], bluffs: ["fisherman", "seamstress", "plaguedoctor"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "steady", count: 15, style: "balanced", roles: ["savant", "alsaahir", "general", "empath", "dreamer", "chef", "investigator", "banshee", "librarian", "sweetheart", "plaguedoctor", "spy", "marionette", "poisoner", "alhadikhia"], bluffs: ["fisherman", "seamstress", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "long", count: 15, style: "long-game", roles: ["alsaahir", "general", "empath", "dreamer", "chef", "investigator", "banshee", "librarian", "fisherman", "plaguedoctor", "drunk", "marionette", "poisoner", "harpy", "alhadikhia"], bluffs: ["seamstress", "savant", "barber"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
  template({ id: "pressure", count: 15, style: "chaos", roles: ["general", "empath", "dreamer", "chef", "investigator", "banshee", "librarian", "fisherman", "seamstress", "drunk", "barber", "poisoner", "harpy", "spy", "alhadikhia"], bluffs: ["savant", "alsaahir", "plaguedoctor"], note: "Verified setup; Baron, Balloonist and Bounty Hunter setup-changing paths stay out of normal templates; Al-Hadikhia and Alsaahir outcomes remain ST-confirmed." }),
]
